// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AuditObjectStorePolicy struct {
	pulumi.CustomResourceState

	// Whether the audit object store policy is enabled.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Whether the policy is defined on the local array (read-only).
	IsLocal pulumi.BoolOutput `pulumi:"isLocal"`
	// List of log target names to receive audit events from this policy.
	LogTargets pulumi.StringArrayOutput `pulumi:"logTargets"`
	// The name of the audit object store policy. Not renameable; changing forces replacement.
	Name pulumi.StringOutput `pulumi:"name"`
	// The type of the policy (e.g. 'audit'). Read-only, set by the array.
	PolicyType pulumi.StringOutput `pulumi:"policyType"`
}

// NewAuditObjectStorePolicy registers a new resource with the given unique name, arguments, and options.
func NewAuditObjectStorePolicy(ctx *pulumi.Context,
	name string, args *AuditObjectStorePolicyArgs, opts ...pulumi.ResourceOption) (*AuditObjectStorePolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AuditObjectStorePolicy
	err := ctx.RegisterResource("flashblade:index/auditObjectStorePolicy:AuditObjectStorePolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAuditObjectStorePolicy gets an existing AuditObjectStorePolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAuditObjectStorePolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AuditObjectStorePolicyState, opts ...pulumi.ResourceOption) (*AuditObjectStorePolicy, error) {
	var resource AuditObjectStorePolicy
	err := ctx.ReadResource("flashblade:index/auditObjectStorePolicy:AuditObjectStorePolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AuditObjectStorePolicy resources.
type auditObjectStorePolicyState struct {
	// Whether the audit object store policy is enabled.
	Enabled *bool `pulumi:"enabled"`
	// Whether the policy is defined on the local array (read-only).
	IsLocal *bool `pulumi:"isLocal"`
	// List of log target names to receive audit events from this policy.
	LogTargets []string `pulumi:"logTargets"`
	// The name of the audit object store policy. Not renameable; changing forces replacement.
	Name *string `pulumi:"name"`
	// The type of the policy (e.g. 'audit'). Read-only, set by the array.
	PolicyType *string `pulumi:"policyType"`
}

type AuditObjectStorePolicyState struct {
	// Whether the audit object store policy is enabled.
	Enabled pulumi.BoolPtrInput
	// Whether the policy is defined on the local array (read-only).
	IsLocal pulumi.BoolPtrInput
	// List of log target names to receive audit events from this policy.
	LogTargets pulumi.StringArrayInput
	// The name of the audit object store policy. Not renameable; changing forces replacement.
	Name pulumi.StringPtrInput
	// The type of the policy (e.g. 'audit'). Read-only, set by the array.
	PolicyType pulumi.StringPtrInput
}

func (AuditObjectStorePolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*auditObjectStorePolicyState)(nil)).Elem()
}

type auditObjectStorePolicyArgs struct {
	// Whether the audit object store policy is enabled.
	Enabled *bool `pulumi:"enabled"`
	// List of log target names to receive audit events from this policy.
	LogTargets []string `pulumi:"logTargets"`
	// The name of the audit object store policy. Not renameable; changing forces replacement.
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a AuditObjectStorePolicy resource.
type AuditObjectStorePolicyArgs struct {
	// Whether the audit object store policy is enabled.
	Enabled pulumi.BoolPtrInput
	// List of log target names to receive audit events from this policy.
	LogTargets pulumi.StringArrayInput
	// The name of the audit object store policy. Not renameable; changing forces replacement.
	Name pulumi.StringInput
}

func (AuditObjectStorePolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*auditObjectStorePolicyArgs)(nil)).Elem()
}

type AuditObjectStorePolicyInput interface {
	pulumi.Input

	ToAuditObjectStorePolicyOutput() AuditObjectStorePolicyOutput
	ToAuditObjectStorePolicyOutputWithContext(ctx context.Context) AuditObjectStorePolicyOutput
}

func (*AuditObjectStorePolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**AuditObjectStorePolicy)(nil)).Elem()
}

func (i *AuditObjectStorePolicy) ToAuditObjectStorePolicyOutput() AuditObjectStorePolicyOutput {
	return i.ToAuditObjectStorePolicyOutputWithContext(context.Background())
}

func (i *AuditObjectStorePolicy) ToAuditObjectStorePolicyOutputWithContext(ctx context.Context) AuditObjectStorePolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AuditObjectStorePolicyOutput)
}

type AuditObjectStorePolicyOutput struct{ *pulumi.OutputState }

func (AuditObjectStorePolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AuditObjectStorePolicy)(nil)).Elem()
}

func (o AuditObjectStorePolicyOutput) ToAuditObjectStorePolicyOutput() AuditObjectStorePolicyOutput {
	return o
}

func (o AuditObjectStorePolicyOutput) ToAuditObjectStorePolicyOutputWithContext(ctx context.Context) AuditObjectStorePolicyOutput {
	return o
}

// Whether the audit object store policy is enabled.
func (o AuditObjectStorePolicyOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *AuditObjectStorePolicy) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Whether the policy is defined on the local array (read-only).
func (o AuditObjectStorePolicyOutput) IsLocal() pulumi.BoolOutput {
	return o.ApplyT(func(v *AuditObjectStorePolicy) pulumi.BoolOutput { return v.IsLocal }).(pulumi.BoolOutput)
}

// List of log target names to receive audit events from this policy.
func (o AuditObjectStorePolicyOutput) LogTargets() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AuditObjectStorePolicy) pulumi.StringArrayOutput { return v.LogTargets }).(pulumi.StringArrayOutput)
}

// The name of the audit object store policy. Not renameable; changing forces replacement.
func (o AuditObjectStorePolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AuditObjectStorePolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The type of the policy (e.g. 'audit'). Read-only, set by the array.
func (o AuditObjectStorePolicyOutput) PolicyType() pulumi.StringOutput {
	return o.ApplyT(func(v *AuditObjectStorePolicy) pulumi.StringOutput { return v.PolicyType }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AuditObjectStorePolicyInput)(nil)).Elem(), &AuditObjectStorePolicy{})
	pulumi.RegisterOutputType(AuditObjectStorePolicyOutput{})
}
