// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CertificateGroupMember struct {
	pulumi.CustomResourceState

	// The name of the certificate to add to the group. Changing this forces a new resource.
	CertificateName pulumi.StringOutput `pulumi:"certificateName"`
	// The name of the certificate group. Changing this forces a new resource.
	GroupName pulumi.StringOutput `pulumi:"groupName"`
}

// NewCertificateGroupMember registers a new resource with the given unique name, arguments, and options.
func NewCertificateGroupMember(ctx *pulumi.Context,
	name string, args *CertificateGroupMemberArgs, opts ...pulumi.ResourceOption) (*CertificateGroupMember, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CertificateName == nil {
		return nil, errors.New("invalid value for required argument 'CertificateName'")
	}
	if args.GroupName == nil {
		return nil, errors.New("invalid value for required argument 'GroupName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CertificateGroupMember
	err := ctx.RegisterResource("flashblade:index/certificateGroupMember:CertificateGroupMember", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCertificateGroupMember gets an existing CertificateGroupMember resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCertificateGroupMember(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CertificateGroupMemberState, opts ...pulumi.ResourceOption) (*CertificateGroupMember, error) {
	var resource CertificateGroupMember
	err := ctx.ReadResource("flashblade:index/certificateGroupMember:CertificateGroupMember", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CertificateGroupMember resources.
type certificateGroupMemberState struct {
	// The name of the certificate to add to the group. Changing this forces a new resource.
	CertificateName *string `pulumi:"certificateName"`
	// The name of the certificate group. Changing this forces a new resource.
	GroupName *string `pulumi:"groupName"`
}

type CertificateGroupMemberState struct {
	// The name of the certificate to add to the group. Changing this forces a new resource.
	CertificateName pulumi.StringPtrInput
	// The name of the certificate group. Changing this forces a new resource.
	GroupName pulumi.StringPtrInput
}

func (CertificateGroupMemberState) ElementType() reflect.Type {
	return reflect.TypeOf((*certificateGroupMemberState)(nil)).Elem()
}

type certificateGroupMemberArgs struct {
	// The name of the certificate to add to the group. Changing this forces a new resource.
	CertificateName string `pulumi:"certificateName"`
	// The name of the certificate group. Changing this forces a new resource.
	GroupName string `pulumi:"groupName"`
}

// The set of arguments for constructing a CertificateGroupMember resource.
type CertificateGroupMemberArgs struct {
	// The name of the certificate to add to the group. Changing this forces a new resource.
	CertificateName pulumi.StringInput
	// The name of the certificate group. Changing this forces a new resource.
	GroupName pulumi.StringInput
}

func (CertificateGroupMemberArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*certificateGroupMemberArgs)(nil)).Elem()
}

type CertificateGroupMemberInput interface {
	pulumi.Input

	ToCertificateGroupMemberOutput() CertificateGroupMemberOutput
	ToCertificateGroupMemberOutputWithContext(ctx context.Context) CertificateGroupMemberOutput
}

func (*CertificateGroupMember) ElementType() reflect.Type {
	return reflect.TypeOf((**CertificateGroupMember)(nil)).Elem()
}

func (i *CertificateGroupMember) ToCertificateGroupMemberOutput() CertificateGroupMemberOutput {
	return i.ToCertificateGroupMemberOutputWithContext(context.Background())
}

func (i *CertificateGroupMember) ToCertificateGroupMemberOutputWithContext(ctx context.Context) CertificateGroupMemberOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CertificateGroupMemberOutput)
}

type CertificateGroupMemberOutput struct{ *pulumi.OutputState }

func (CertificateGroupMemberOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CertificateGroupMember)(nil)).Elem()
}

func (o CertificateGroupMemberOutput) ToCertificateGroupMemberOutput() CertificateGroupMemberOutput {
	return o
}

func (o CertificateGroupMemberOutput) ToCertificateGroupMemberOutputWithContext(ctx context.Context) CertificateGroupMemberOutput {
	return o
}

// The name of the certificate to add to the group. Changing this forces a new resource.
func (o CertificateGroupMemberOutput) CertificateName() pulumi.StringOutput {
	return o.ApplyT(func(v *CertificateGroupMember) pulumi.StringOutput { return v.CertificateName }).(pulumi.StringOutput)
}

// The name of the certificate group. Changing this forces a new resource.
func (o CertificateGroupMemberOutput) GroupName() pulumi.StringOutput {
	return o.ApplyT(func(v *CertificateGroupMember) pulumi.StringOutput { return v.GroupName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CertificateGroupMemberInput)(nil)).Elem(), &CertificateGroupMember{})
	pulumi.RegisterOutputType(CertificateGroupMemberOutput{})
}
