// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupArrayDns(ctx *pulumi.Context, args *LookupArrayDnsArgs, opts ...pulumi.InvokeOption) (*LookupArrayDnsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupArrayDnsResult
	err := ctx.Invoke("flashblade:index/getArrayDns:getArrayDns", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getArrayDns.
type LookupArrayDnsArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getArrayDns.
type LookupArrayDnsResult struct {
	Domain      string   `pulumi:"domain"`
	Id          string   `pulumi:"id"`
	Name        string   `pulumi:"name"`
	Nameservers []string `pulumi:"nameservers"`
	Services    []string `pulumi:"services"`
	Sources     []string `pulumi:"sources"`
}

func LookupArrayDnsOutput(ctx *pulumi.Context, args LookupArrayDnsOutputArgs, opts ...pulumi.InvokeOption) LookupArrayDnsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupArrayDnsResultOutput, error) {
			args := v.(LookupArrayDnsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("flashblade:index/getArrayDns:getArrayDns", args, LookupArrayDnsResultOutput{}, options).(LookupArrayDnsResultOutput), nil
		}).(LookupArrayDnsResultOutput)
}

// A collection of arguments for invoking getArrayDns.
type LookupArrayDnsOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupArrayDnsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupArrayDnsArgs)(nil)).Elem()
}

// A collection of values returned by getArrayDns.
type LookupArrayDnsResultOutput struct{ *pulumi.OutputState }

func (LookupArrayDnsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupArrayDnsResult)(nil)).Elem()
}

func (o LookupArrayDnsResultOutput) ToLookupArrayDnsResultOutput() LookupArrayDnsResultOutput {
	return o
}

func (o LookupArrayDnsResultOutput) ToLookupArrayDnsResultOutputWithContext(ctx context.Context) LookupArrayDnsResultOutput {
	return o
}

func (o LookupArrayDnsResultOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupArrayDnsResult) string { return v.Domain }).(pulumi.StringOutput)
}

func (o LookupArrayDnsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupArrayDnsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupArrayDnsResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupArrayDnsResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupArrayDnsResultOutput) Nameservers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupArrayDnsResult) []string { return v.Nameservers }).(pulumi.StringArrayOutput)
}

func (o LookupArrayDnsResultOutput) Services() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupArrayDnsResult) []string { return v.Services }).(pulumi.StringArrayOutput)
}

func (o LookupArrayDnsResultOutput) Sources() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupArrayDnsResult) []string { return v.Sources }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupArrayDnsResultOutput{})
}
