// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCertificateGroup(ctx *pulumi.Context, args *LookupCertificateGroupArgs, opts ...pulumi.InvokeOption) (*LookupCertificateGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupCertificateGroupResult
	err := ctx.Invoke("flashblade:index/getCertificateGroup:getCertificateGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCertificateGroup.
type LookupCertificateGroupArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getCertificateGroup.
type LookupCertificateGroupResult struct {
	Id     string   `pulumi:"id"`
	Name   string   `pulumi:"name"`
	Realms []string `pulumi:"realms"`
}

func LookupCertificateGroupOutput(ctx *pulumi.Context, args LookupCertificateGroupOutputArgs, opts ...pulumi.InvokeOption) LookupCertificateGroupResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupCertificateGroupResultOutput, error) {
			args := v.(LookupCertificateGroupArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("flashblade:index/getCertificateGroup:getCertificateGroup", args, LookupCertificateGroupResultOutput{}, options).(LookupCertificateGroupResultOutput), nil
		}).(LookupCertificateGroupResultOutput)
}

// A collection of arguments for invoking getCertificateGroup.
type LookupCertificateGroupOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupCertificateGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCertificateGroupArgs)(nil)).Elem()
}

// A collection of values returned by getCertificateGroup.
type LookupCertificateGroupResultOutput struct{ *pulumi.OutputState }

func (LookupCertificateGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCertificateGroupResult)(nil)).Elem()
}

func (o LookupCertificateGroupResultOutput) ToLookupCertificateGroupResultOutput() LookupCertificateGroupResultOutput {
	return o
}

func (o LookupCertificateGroupResultOutput) ToLookupCertificateGroupResultOutputWithContext(ctx context.Context) LookupCertificateGroupResultOutput {
	return o
}

func (o LookupCertificateGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCertificateGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupCertificateGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCertificateGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupCertificateGroupResultOutput) Realms() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupCertificateGroupResult) []string { return v.Realms }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCertificateGroupResultOutput{})
}
