// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"github.com/numberly/opentofu-provider-flashblade/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupDirectoryServiceManagement(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupDirectoryServiceManagementResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDirectoryServiceManagementResult
	err := ctx.Invoke("flashblade:index/getDirectoryServiceManagement:getDirectoryServiceManagement", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getDirectoryServiceManagement.
type LookupDirectoryServiceManagementResult struct {
	BaseDn                string                                          `pulumi:"baseDn"`
	BindUser              string                                          `pulumi:"bindUser"`
	CaCertificate         GetDirectoryServiceManagementCaCertificate      `pulumi:"caCertificate"`
	CaCertificateGroup    GetDirectoryServiceManagementCaCertificateGroup `pulumi:"caCertificateGroup"`
	Enabled               bool                                            `pulumi:"enabled"`
	Id                    string                                          `pulumi:"id"`
	Services              []string                                        `pulumi:"services"`
	SshPublicKeyAttribute string                                          `pulumi:"sshPublicKeyAttribute"`
	Uris                  []string                                        `pulumi:"uris"`
	UserLoginAttribute    string                                          `pulumi:"userLoginAttribute"`
	UserObjectClass       string                                          `pulumi:"userObjectClass"`
}

func LookupDirectoryServiceManagementOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupDirectoryServiceManagementResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (LookupDirectoryServiceManagementResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("flashblade:index/getDirectoryServiceManagement:getDirectoryServiceManagement", nil, LookupDirectoryServiceManagementResultOutput{}, options).(LookupDirectoryServiceManagementResultOutput), nil
	}).(LookupDirectoryServiceManagementResultOutput)
}

// A collection of values returned by getDirectoryServiceManagement.
type LookupDirectoryServiceManagementResultOutput struct{ *pulumi.OutputState }

func (LookupDirectoryServiceManagementResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDirectoryServiceManagementResult)(nil)).Elem()
}

func (o LookupDirectoryServiceManagementResultOutput) ToLookupDirectoryServiceManagementResultOutput() LookupDirectoryServiceManagementResultOutput {
	return o
}

func (o LookupDirectoryServiceManagementResultOutput) ToLookupDirectoryServiceManagementResultOutputWithContext(ctx context.Context) LookupDirectoryServiceManagementResultOutput {
	return o
}

func (o LookupDirectoryServiceManagementResultOutput) BaseDn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDirectoryServiceManagementResult) string { return v.BaseDn }).(pulumi.StringOutput)
}

func (o LookupDirectoryServiceManagementResultOutput) BindUser() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDirectoryServiceManagementResult) string { return v.BindUser }).(pulumi.StringOutput)
}

func (o LookupDirectoryServiceManagementResultOutput) CaCertificate() GetDirectoryServiceManagementCaCertificateOutput {
	return o.ApplyT(func(v LookupDirectoryServiceManagementResult) GetDirectoryServiceManagementCaCertificate {
		return v.CaCertificate
	}).(GetDirectoryServiceManagementCaCertificateOutput)
}

func (o LookupDirectoryServiceManagementResultOutput) CaCertificateGroup() GetDirectoryServiceManagementCaCertificateGroupOutput {
	return o.ApplyT(func(v LookupDirectoryServiceManagementResult) GetDirectoryServiceManagementCaCertificateGroup {
		return v.CaCertificateGroup
	}).(GetDirectoryServiceManagementCaCertificateGroupOutput)
}

func (o LookupDirectoryServiceManagementResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDirectoryServiceManagementResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupDirectoryServiceManagementResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDirectoryServiceManagementResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDirectoryServiceManagementResultOutput) Services() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupDirectoryServiceManagementResult) []string { return v.Services }).(pulumi.StringArrayOutput)
}

func (o LookupDirectoryServiceManagementResultOutput) SshPublicKeyAttribute() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDirectoryServiceManagementResult) string { return v.SshPublicKeyAttribute }).(pulumi.StringOutput)
}

func (o LookupDirectoryServiceManagementResultOutput) Uris() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupDirectoryServiceManagementResult) []string { return v.Uris }).(pulumi.StringArrayOutput)
}

func (o LookupDirectoryServiceManagementResultOutput) UserLoginAttribute() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDirectoryServiceManagementResult) string { return v.UserLoginAttribute }).(pulumi.StringOutput)
}

func (o LookupDirectoryServiceManagementResultOutput) UserObjectClass() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDirectoryServiceManagementResult) string { return v.UserObjectClass }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDirectoryServiceManagementResultOutput{})
}
