// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"github.com/numberly/opentofu-provider-flashblade/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetLinkAggregationGroup(ctx *pulumi.Context, args *GetLinkAggregationGroupArgs, opts ...pulumi.InvokeOption) (*GetLinkAggregationGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetLinkAggregationGroupResult
	err := ctx.Invoke("flashblade:index/getLinkAggregationGroup:getLinkAggregationGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLinkAggregationGroup.
type GetLinkAggregationGroupArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getLinkAggregationGroup.
type GetLinkAggregationGroupResult struct {
	Id         string   `pulumi:"id"`
	LagSpeed   int      `pulumi:"lagSpeed"`
	MacAddress string   `pulumi:"macAddress"`
	Name       string   `pulumi:"name"`
	PortSpeed  int      `pulumi:"portSpeed"`
	Ports      []string `pulumi:"ports"`
	Status     string   `pulumi:"status"`
}

func GetLinkAggregationGroupOutput(ctx *pulumi.Context, args GetLinkAggregationGroupOutputArgs, opts ...pulumi.InvokeOption) GetLinkAggregationGroupResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetLinkAggregationGroupResultOutput, error) {
			args := v.(GetLinkAggregationGroupArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("flashblade:index/getLinkAggregationGroup:getLinkAggregationGroup", args, GetLinkAggregationGroupResultOutput{}, options).(GetLinkAggregationGroupResultOutput), nil
		}).(GetLinkAggregationGroupResultOutput)
}

// A collection of arguments for invoking getLinkAggregationGroup.
type GetLinkAggregationGroupOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetLinkAggregationGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLinkAggregationGroupArgs)(nil)).Elem()
}

// A collection of values returned by getLinkAggregationGroup.
type GetLinkAggregationGroupResultOutput struct{ *pulumi.OutputState }

func (GetLinkAggregationGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLinkAggregationGroupResult)(nil)).Elem()
}

func (o GetLinkAggregationGroupResultOutput) ToGetLinkAggregationGroupResultOutput() GetLinkAggregationGroupResultOutput {
	return o
}

func (o GetLinkAggregationGroupResultOutput) ToGetLinkAggregationGroupResultOutputWithContext(ctx context.Context) GetLinkAggregationGroupResultOutput {
	return o
}

func (o GetLinkAggregationGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetLinkAggregationGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetLinkAggregationGroupResultOutput) LagSpeed() pulumi.IntOutput {
	return o.ApplyT(func(v GetLinkAggregationGroupResult) int { return v.LagSpeed }).(pulumi.IntOutput)
}

func (o GetLinkAggregationGroupResultOutput) MacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v GetLinkAggregationGroupResult) string { return v.MacAddress }).(pulumi.StringOutput)
}

func (o GetLinkAggregationGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetLinkAggregationGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetLinkAggregationGroupResultOutput) PortSpeed() pulumi.IntOutput {
	return o.ApplyT(func(v GetLinkAggregationGroupResult) int { return v.PortSpeed }).(pulumi.IntOutput)
}

func (o GetLinkAggregationGroupResultOutput) Ports() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetLinkAggregationGroupResult) []string { return v.Ports }).(pulumi.StringArrayOutput)
}

func (o GetLinkAggregationGroupResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetLinkAggregationGroupResult) string { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetLinkAggregationGroupResultOutput{})
}
