// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNetworkInterface(ctx *pulumi.Context, args *LookupNetworkInterfaceArgs, opts ...pulumi.InvokeOption) (*LookupNetworkInterfaceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNetworkInterfaceResult
	err := ctx.Invoke("flashblade:index/getNetworkInterface:getNetworkInterface", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkInterface.
type LookupNetworkInterfaceArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getNetworkInterface.
type LookupNetworkInterfaceResult struct {
	Address         string   `pulumi:"address"`
	AttachedServers []string `pulumi:"attachedServers"`
	Enabled         bool     `pulumi:"enabled"`
	Gateway         string   `pulumi:"gateway"`
	Id              string   `pulumi:"id"`
	Mtu             int      `pulumi:"mtu"`
	Name            string   `pulumi:"name"`
	Netmask         string   `pulumi:"netmask"`
	Realms          []string `pulumi:"realms"`
	Services        string   `pulumi:"services"`
	SubnetName      string   `pulumi:"subnetName"`
	Type            string   `pulumi:"type"`
	Vlan            int      `pulumi:"vlan"`
}

func LookupNetworkInterfaceOutput(ctx *pulumi.Context, args LookupNetworkInterfaceOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkInterfaceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNetworkInterfaceResultOutput, error) {
			args := v.(LookupNetworkInterfaceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("flashblade:index/getNetworkInterface:getNetworkInterface", args, LookupNetworkInterfaceResultOutput{}, options).(LookupNetworkInterfaceResultOutput), nil
		}).(LookupNetworkInterfaceResultOutput)
}

// A collection of arguments for invoking getNetworkInterface.
type LookupNetworkInterfaceOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupNetworkInterfaceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkInterfaceArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkInterface.
type LookupNetworkInterfaceResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkInterfaceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkInterfaceResult)(nil)).Elem()
}

func (o LookupNetworkInterfaceResultOutput) ToLookupNetworkInterfaceResultOutput() LookupNetworkInterfaceResultOutput {
	return o
}

func (o LookupNetworkInterfaceResultOutput) ToLookupNetworkInterfaceResultOutputWithContext(ctx context.Context) LookupNetworkInterfaceResultOutput {
	return o
}

func (o LookupNetworkInterfaceResultOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.Address }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) AttachedServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) []string { return v.AttachedServers }).(pulumi.StringArrayOutput)
}

func (o LookupNetworkInterfaceResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupNetworkInterfaceResultOutput) Gateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.Gateway }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) Mtu() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) int { return v.Mtu }).(pulumi.IntOutput)
}

func (o LookupNetworkInterfaceResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) Netmask() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.Netmask }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) Realms() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) []string { return v.Realms }).(pulumi.StringArrayOutput)
}

func (o LookupNetworkInterfaceResultOutput) Services() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.Services }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) SubnetName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.SubnetName }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) string { return v.Type }).(pulumi.StringOutput)
}

func (o LookupNetworkInterfaceResultOutput) Vlan() pulumi.IntOutput {
	return o.ApplyT(func(v LookupNetworkInterfaceResult) int { return v.Vlan }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkInterfaceResultOutput{})
}
