// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupQuotaGroup(ctx *pulumi.Context, args *LookupQuotaGroupArgs, opts ...pulumi.InvokeOption) (*LookupQuotaGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupQuotaGroupResult
	err := ctx.Invoke("flashblade:index/getQuotaGroup:getQuotaGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getQuotaGroup.
type LookupQuotaGroupArgs struct {
	FileSystemName string `pulumi:"fileSystemName"`
	Gid            string `pulumi:"gid"`
}

// A collection of values returned by getQuotaGroup.
type LookupQuotaGroupResult struct {
	FileSystemName string `pulumi:"fileSystemName"`
	Gid            string `pulumi:"gid"`
	Id             string `pulumi:"id"`
	Quota          int    `pulumi:"quota"`
	Usage          int    `pulumi:"usage"`
}

func LookupQuotaGroupOutput(ctx *pulumi.Context, args LookupQuotaGroupOutputArgs, opts ...pulumi.InvokeOption) LookupQuotaGroupResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupQuotaGroupResultOutput, error) {
			args := v.(LookupQuotaGroupArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("flashblade:index/getQuotaGroup:getQuotaGroup", args, LookupQuotaGroupResultOutput{}, options).(LookupQuotaGroupResultOutput), nil
		}).(LookupQuotaGroupResultOutput)
}

// A collection of arguments for invoking getQuotaGroup.
type LookupQuotaGroupOutputArgs struct {
	FileSystemName pulumi.StringInput `pulumi:"fileSystemName"`
	Gid            pulumi.StringInput `pulumi:"gid"`
}

func (LookupQuotaGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupQuotaGroupArgs)(nil)).Elem()
}

// A collection of values returned by getQuotaGroup.
type LookupQuotaGroupResultOutput struct{ *pulumi.OutputState }

func (LookupQuotaGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupQuotaGroupResult)(nil)).Elem()
}

func (o LookupQuotaGroupResultOutput) ToLookupQuotaGroupResultOutput() LookupQuotaGroupResultOutput {
	return o
}

func (o LookupQuotaGroupResultOutput) ToLookupQuotaGroupResultOutputWithContext(ctx context.Context) LookupQuotaGroupResultOutput {
	return o
}

func (o LookupQuotaGroupResultOutput) FileSystemName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupQuotaGroupResult) string { return v.FileSystemName }).(pulumi.StringOutput)
}

func (o LookupQuotaGroupResultOutput) Gid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupQuotaGroupResult) string { return v.Gid }).(pulumi.StringOutput)
}

func (o LookupQuotaGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupQuotaGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupQuotaGroupResultOutput) Quota() pulumi.IntOutput {
	return o.ApplyT(func(v LookupQuotaGroupResult) int { return v.Quota }).(pulumi.IntOutput)
}

func (o LookupQuotaGroupResultOutput) Usage() pulumi.IntOutput {
	return o.ApplyT(func(v LookupQuotaGroupResult) int { return v.Usage }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupQuotaGroupResultOutput{})
}
