// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSubnet(ctx *pulumi.Context, args *LookupSubnetArgs, opts ...pulumi.InvokeOption) (*LookupSubnetResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSubnetResult
	err := ctx.Invoke("flashblade:index/getSubnet:getSubnet", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSubnet.
type LookupSubnetArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getSubnet.
type LookupSubnetResult struct {
	Enabled    bool     `pulumi:"enabled"`
	Gateway    string   `pulumi:"gateway"`
	Id         string   `pulumi:"id"`
	Interfaces []string `pulumi:"interfaces"`
	LagName    string   `pulumi:"lagName"`
	Mtu        int      `pulumi:"mtu"`
	Name       string   `pulumi:"name"`
	Prefix     string   `pulumi:"prefix"`
	Services   []string `pulumi:"services"`
	Vlan       int      `pulumi:"vlan"`
}

func LookupSubnetOutput(ctx *pulumi.Context, args LookupSubnetOutputArgs, opts ...pulumi.InvokeOption) LookupSubnetResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSubnetResultOutput, error) {
			args := v.(LookupSubnetArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("flashblade:index/getSubnet:getSubnet", args, LookupSubnetResultOutput{}, options).(LookupSubnetResultOutput), nil
		}).(LookupSubnetResultOutput)
}

// A collection of arguments for invoking getSubnet.
type LookupSubnetOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupSubnetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSubnetArgs)(nil)).Elem()
}

// A collection of values returned by getSubnet.
type LookupSubnetResultOutput struct{ *pulumi.OutputState }

func (LookupSubnetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSubnetResult)(nil)).Elem()
}

func (o LookupSubnetResultOutput) ToLookupSubnetResultOutput() LookupSubnetResultOutput {
	return o
}

func (o LookupSubnetResultOutput) ToLookupSubnetResultOutputWithContext(ctx context.Context) LookupSubnetResultOutput {
	return o
}

func (o LookupSubnetResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSubnetResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupSubnetResultOutput) Gateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubnetResult) string { return v.Gateway }).(pulumi.StringOutput)
}

func (o LookupSubnetResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubnetResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSubnetResultOutput) Interfaces() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSubnetResult) []string { return v.Interfaces }).(pulumi.StringArrayOutput)
}

func (o LookupSubnetResultOutput) LagName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubnetResult) string { return v.LagName }).(pulumi.StringOutput)
}

func (o LookupSubnetResultOutput) Mtu() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSubnetResult) int { return v.Mtu }).(pulumi.IntOutput)
}

func (o LookupSubnetResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubnetResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSubnetResultOutput) Prefix() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSubnetResult) string { return v.Prefix }).(pulumi.StringOutput)
}

func (o LookupSubnetResultOutput) Services() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSubnetResult) []string { return v.Services }).(pulumi.StringArrayOutput)
}

func (o LookupSubnetResultOutput) Vlan() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSubnetResult) int { return v.Vlan }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSubnetResultOutput{})
}
