// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupTlsPolicy(ctx *pulumi.Context, args *LookupTlsPolicyArgs, opts ...pulumi.InvokeOption) (*LookupTlsPolicyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupTlsPolicyResult
	err := ctx.Invoke("flashblade:index/getTlsPolicy:getTlsPolicy", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTlsPolicy.
type LookupTlsPolicyArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getTlsPolicy.
type LookupTlsPolicyResult struct {
	ApplianceCertificate              string   `pulumi:"applianceCertificate"`
	ClientCertificatesRequired        bool     `pulumi:"clientCertificatesRequired"`
	DisabledTlsCiphers                []string `pulumi:"disabledTlsCiphers"`
	Enabled                           bool     `pulumi:"enabled"`
	EnabledTlsCiphers                 []string `pulumi:"enabledTlsCiphers"`
	Id                                string   `pulumi:"id"`
	IsLocal                           bool     `pulumi:"isLocal"`
	MinTlsVersion                     string   `pulumi:"minTlsVersion"`
	Name                              string   `pulumi:"name"`
	PolicyType                        string   `pulumi:"policyType"`
	TrustedClientCertificateAuthority string   `pulumi:"trustedClientCertificateAuthority"`
	VerifyClientCertificateTrust      bool     `pulumi:"verifyClientCertificateTrust"`
}

func LookupTlsPolicyOutput(ctx *pulumi.Context, args LookupTlsPolicyOutputArgs, opts ...pulumi.InvokeOption) LookupTlsPolicyResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupTlsPolicyResultOutput, error) {
			args := v.(LookupTlsPolicyArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("flashblade:index/getTlsPolicy:getTlsPolicy", args, LookupTlsPolicyResultOutput{}, options).(LookupTlsPolicyResultOutput), nil
		}).(LookupTlsPolicyResultOutput)
}

// A collection of arguments for invoking getTlsPolicy.
type LookupTlsPolicyOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupTlsPolicyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTlsPolicyArgs)(nil)).Elem()
}

// A collection of values returned by getTlsPolicy.
type LookupTlsPolicyResultOutput struct{ *pulumi.OutputState }

func (LookupTlsPolicyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTlsPolicyResult)(nil)).Elem()
}

func (o LookupTlsPolicyResultOutput) ToLookupTlsPolicyResultOutput() LookupTlsPolicyResultOutput {
	return o
}

func (o LookupTlsPolicyResultOutput) ToLookupTlsPolicyResultOutputWithContext(ctx context.Context) LookupTlsPolicyResultOutput {
	return o
}

func (o LookupTlsPolicyResultOutput) ApplianceCertificate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTlsPolicyResult) string { return v.ApplianceCertificate }).(pulumi.StringOutput)
}

func (o LookupTlsPolicyResultOutput) ClientCertificatesRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTlsPolicyResult) bool { return v.ClientCertificatesRequired }).(pulumi.BoolOutput)
}

func (o LookupTlsPolicyResultOutput) DisabledTlsCiphers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupTlsPolicyResult) []string { return v.DisabledTlsCiphers }).(pulumi.StringArrayOutput)
}

func (o LookupTlsPolicyResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTlsPolicyResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupTlsPolicyResultOutput) EnabledTlsCiphers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupTlsPolicyResult) []string { return v.EnabledTlsCiphers }).(pulumi.StringArrayOutput)
}

func (o LookupTlsPolicyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTlsPolicyResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupTlsPolicyResultOutput) IsLocal() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTlsPolicyResult) bool { return v.IsLocal }).(pulumi.BoolOutput)
}

func (o LookupTlsPolicyResultOutput) MinTlsVersion() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTlsPolicyResult) string { return v.MinTlsVersion }).(pulumi.StringOutput)
}

func (o LookupTlsPolicyResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTlsPolicyResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupTlsPolicyResultOutput) PolicyType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTlsPolicyResult) string { return v.PolicyType }).(pulumi.StringOutput)
}

func (o LookupTlsPolicyResultOutput) TrustedClientCertificateAuthority() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTlsPolicyResult) string { return v.TrustedClientCertificateAuthority }).(pulumi.StringOutput)
}

func (o LookupTlsPolicyResultOutput) VerifyClientCertificateTrust() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTlsPolicyResult) bool { return v.VerifyClientCertificateTrust }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTlsPolicyResultOutput{})
}
