// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/opentofu-provider-flashblade/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type LifecycleRule struct {
	pulumi.CustomResourceState

	// Duration in milliseconds after which incomplete multipart uploads are aborted.
	AbortIncompleteMultipartUploadsAfter pulumi.IntPtrOutput `pulumi:"abortIncompleteMultipartUploadsAfter"`
	// The name of the bucket this rule belongs to. Changing this forces a new resource.
	BucketName pulumi.StringOutput `pulumi:"bucketName"`
	// Whether expired object delete markers are cleaned up. Read-only, managed by the array.
	CleanupExpiredObjectDeleteMarker pulumi.BoolOutput `pulumi:"cleanupExpiredObjectDeleteMarker"`
	// Whether the lifecycle rule is enabled. Defaults to true.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Duration in milliseconds to keep current object versions before expiration.
	KeepCurrentVersionFor pulumi.IntPtrOutput `pulumi:"keepCurrentVersionFor"`
	// Timestamp in milliseconds until which current object versions are kept.
	KeepCurrentVersionUntil pulumi.IntPtrOutput `pulumi:"keepCurrentVersionUntil"`
	// Duration in milliseconds to keep previous object versions before expiration.
	KeepPreviousVersionFor pulumi.IntPtrOutput `pulumi:"keepPreviousVersionFor"`
	// Object key prefix filter for the rule. Defaults to empty string (all objects).
	Prefix pulumi.StringOutput `pulumi:"prefix"`
	// The rule identifier within the bucket. Changing this forces a new resource.
	RuleId pulumi.StringOutput `pulumi:"ruleId"`
}

// NewLifecycleRule registers a new resource with the given unique name, arguments, and options.
func NewLifecycleRule(ctx *pulumi.Context,
	name string, args *LifecycleRuleArgs, opts ...pulumi.ResourceOption) (*LifecycleRule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.BucketName == nil {
		return nil, errors.New("invalid value for required argument 'BucketName'")
	}
	if args.RuleId == nil {
		return nil, errors.New("invalid value for required argument 'RuleId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource LifecycleRule
	err := ctx.RegisterResource("flashblade:index/lifecycleRule:LifecycleRule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLifecycleRule gets an existing LifecycleRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLifecycleRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LifecycleRuleState, opts ...pulumi.ResourceOption) (*LifecycleRule, error) {
	var resource LifecycleRule
	err := ctx.ReadResource("flashblade:index/lifecycleRule:LifecycleRule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LifecycleRule resources.
type lifecycleRuleState struct {
	// Duration in milliseconds after which incomplete multipart uploads are aborted.
	AbortIncompleteMultipartUploadsAfter *int `pulumi:"abortIncompleteMultipartUploadsAfter"`
	// The name of the bucket this rule belongs to. Changing this forces a new resource.
	BucketName *string `pulumi:"bucketName"`
	// Whether expired object delete markers are cleaned up. Read-only, managed by the array.
	CleanupExpiredObjectDeleteMarker *bool `pulumi:"cleanupExpiredObjectDeleteMarker"`
	// Whether the lifecycle rule is enabled. Defaults to true.
	Enabled *bool `pulumi:"enabled"`
	// Duration in milliseconds to keep current object versions before expiration.
	KeepCurrentVersionFor *int `pulumi:"keepCurrentVersionFor"`
	// Timestamp in milliseconds until which current object versions are kept.
	KeepCurrentVersionUntil *int `pulumi:"keepCurrentVersionUntil"`
	// Duration in milliseconds to keep previous object versions before expiration.
	KeepPreviousVersionFor *int `pulumi:"keepPreviousVersionFor"`
	// Object key prefix filter for the rule. Defaults to empty string (all objects).
	Prefix *string `pulumi:"prefix"`
	// The rule identifier within the bucket. Changing this forces a new resource.
	RuleId *string `pulumi:"ruleId"`
}

type LifecycleRuleState struct {
	// Duration in milliseconds after which incomplete multipart uploads are aborted.
	AbortIncompleteMultipartUploadsAfter pulumi.IntPtrInput
	// The name of the bucket this rule belongs to. Changing this forces a new resource.
	BucketName pulumi.StringPtrInput
	// Whether expired object delete markers are cleaned up. Read-only, managed by the array.
	CleanupExpiredObjectDeleteMarker pulumi.BoolPtrInput
	// Whether the lifecycle rule is enabled. Defaults to true.
	Enabled pulumi.BoolPtrInput
	// Duration in milliseconds to keep current object versions before expiration.
	KeepCurrentVersionFor pulumi.IntPtrInput
	// Timestamp in milliseconds until which current object versions are kept.
	KeepCurrentVersionUntil pulumi.IntPtrInput
	// Duration in milliseconds to keep previous object versions before expiration.
	KeepPreviousVersionFor pulumi.IntPtrInput
	// Object key prefix filter for the rule. Defaults to empty string (all objects).
	Prefix pulumi.StringPtrInput
	// The rule identifier within the bucket. Changing this forces a new resource.
	RuleId pulumi.StringPtrInput
}

func (LifecycleRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*lifecycleRuleState)(nil)).Elem()
}

type lifecycleRuleArgs struct {
	// Duration in milliseconds after which incomplete multipart uploads are aborted.
	AbortIncompleteMultipartUploadsAfter *int `pulumi:"abortIncompleteMultipartUploadsAfter"`
	// The name of the bucket this rule belongs to. Changing this forces a new resource.
	BucketName string `pulumi:"bucketName"`
	// Whether the lifecycle rule is enabled. Defaults to true.
	Enabled *bool `pulumi:"enabled"`
	// Duration in milliseconds to keep current object versions before expiration.
	KeepCurrentVersionFor *int `pulumi:"keepCurrentVersionFor"`
	// Timestamp in milliseconds until which current object versions are kept.
	KeepCurrentVersionUntil *int `pulumi:"keepCurrentVersionUntil"`
	// Duration in milliseconds to keep previous object versions before expiration.
	KeepPreviousVersionFor *int `pulumi:"keepPreviousVersionFor"`
	// Object key prefix filter for the rule. Defaults to empty string (all objects).
	Prefix *string `pulumi:"prefix"`
	// The rule identifier within the bucket. Changing this forces a new resource.
	RuleId string `pulumi:"ruleId"`
}

// The set of arguments for constructing a LifecycleRule resource.
type LifecycleRuleArgs struct {
	// Duration in milliseconds after which incomplete multipart uploads are aborted.
	AbortIncompleteMultipartUploadsAfter pulumi.IntPtrInput
	// The name of the bucket this rule belongs to. Changing this forces a new resource.
	BucketName pulumi.StringInput
	// Whether the lifecycle rule is enabled. Defaults to true.
	Enabled pulumi.BoolPtrInput
	// Duration in milliseconds to keep current object versions before expiration.
	KeepCurrentVersionFor pulumi.IntPtrInput
	// Timestamp in milliseconds until which current object versions are kept.
	KeepCurrentVersionUntil pulumi.IntPtrInput
	// Duration in milliseconds to keep previous object versions before expiration.
	KeepPreviousVersionFor pulumi.IntPtrInput
	// Object key prefix filter for the rule. Defaults to empty string (all objects).
	Prefix pulumi.StringPtrInput
	// The rule identifier within the bucket. Changing this forces a new resource.
	RuleId pulumi.StringInput
}

func (LifecycleRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*lifecycleRuleArgs)(nil)).Elem()
}

type LifecycleRuleInput interface {
	pulumi.Input

	ToLifecycleRuleOutput() LifecycleRuleOutput
	ToLifecycleRuleOutputWithContext(ctx context.Context) LifecycleRuleOutput
}

func (*LifecycleRule) ElementType() reflect.Type {
	return reflect.TypeOf((**LifecycleRule)(nil)).Elem()
}

func (i *LifecycleRule) ToLifecycleRuleOutput() LifecycleRuleOutput {
	return i.ToLifecycleRuleOutputWithContext(context.Background())
}

func (i *LifecycleRule) ToLifecycleRuleOutputWithContext(ctx context.Context) LifecycleRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LifecycleRuleOutput)
}

type LifecycleRuleOutput struct{ *pulumi.OutputState }

func (LifecycleRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LifecycleRule)(nil)).Elem()
}

func (o LifecycleRuleOutput) ToLifecycleRuleOutput() LifecycleRuleOutput {
	return o
}

func (o LifecycleRuleOutput) ToLifecycleRuleOutputWithContext(ctx context.Context) LifecycleRuleOutput {
	return o
}

// Duration in milliseconds after which incomplete multipart uploads are aborted.
func (o LifecycleRuleOutput) AbortIncompleteMultipartUploadsAfter() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *LifecycleRule) pulumi.IntPtrOutput { return v.AbortIncompleteMultipartUploadsAfter }).(pulumi.IntPtrOutput)
}

// The name of the bucket this rule belongs to. Changing this forces a new resource.
func (o LifecycleRuleOutput) BucketName() pulumi.StringOutput {
	return o.ApplyT(func(v *LifecycleRule) pulumi.StringOutput { return v.BucketName }).(pulumi.StringOutput)
}

// Whether expired object delete markers are cleaned up. Read-only, managed by the array.
func (o LifecycleRuleOutput) CleanupExpiredObjectDeleteMarker() pulumi.BoolOutput {
	return o.ApplyT(func(v *LifecycleRule) pulumi.BoolOutput { return v.CleanupExpiredObjectDeleteMarker }).(pulumi.BoolOutput)
}

// Whether the lifecycle rule is enabled. Defaults to true.
func (o LifecycleRuleOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *LifecycleRule) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Duration in milliseconds to keep current object versions before expiration.
func (o LifecycleRuleOutput) KeepCurrentVersionFor() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *LifecycleRule) pulumi.IntPtrOutput { return v.KeepCurrentVersionFor }).(pulumi.IntPtrOutput)
}

// Timestamp in milliseconds until which current object versions are kept.
func (o LifecycleRuleOutput) KeepCurrentVersionUntil() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *LifecycleRule) pulumi.IntPtrOutput { return v.KeepCurrentVersionUntil }).(pulumi.IntPtrOutput)
}

// Duration in milliseconds to keep previous object versions before expiration.
func (o LifecycleRuleOutput) KeepPreviousVersionFor() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *LifecycleRule) pulumi.IntPtrOutput { return v.KeepPreviousVersionFor }).(pulumi.IntPtrOutput)
}

// Object key prefix filter for the rule. Defaults to empty string (all objects).
func (o LifecycleRuleOutput) Prefix() pulumi.StringOutput {
	return o.ApplyT(func(v *LifecycleRule) pulumi.StringOutput { return v.Prefix }).(pulumi.StringOutput)
}

// The rule identifier within the bucket. Changing this forces a new resource.
func (o LifecycleRuleOutput) RuleId() pulumi.StringOutput {
	return o.ApplyT(func(v *LifecycleRule) pulumi.StringOutput { return v.RuleId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LifecycleRuleInput)(nil)).Elem(), &LifecycleRule{})
	pulumi.RegisterOutputType(LifecycleRuleOutput{})
}
