// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/opentofu-provider-flashblade/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetworkInterface struct {
	pulumi.CustomResourceState

	// The IPv4 address for this network interface.
	Address pulumi.StringOutput `pulumi:"address"`
	// List of server names attached to this interface. Required for data/sts; forbidden for egress-only/replication.
	AttachedServers pulumi.StringArrayOutput `pulumi:"attachedServers"`
	// Whether the network interface is enabled.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// The gateway address for this network interface.
	Gateway pulumi.StringOutput `pulumi:"gateway"`
	// Maximum transmission unit (MTU) in bytes.
	Mtu pulumi.IntOutput `pulumi:"mtu"`
	// The name of the network interface. Changing this forces a new resource.
	Name pulumi.StringOutput `pulumi:"name"`
	// The subnet mask for this network interface.
	Netmask pulumi.StringOutput `pulumi:"netmask"`
	// List of realms associated with this network interface.
	Realms pulumi.StringArrayOutput `pulumi:"realms"`
	// The service type for this network interface. One of: data, sts, egress-only, replication.
	Services pulumi.StringOutput `pulumi:"services"`
	// The name of the subnet this interface is attached to. Changing this forces a new resource.
	SubnetName pulumi.StringOutput `pulumi:"subnetName"`
	// The network interface type (e.g. vip). Changing this forces a new resource.
	Type pulumi.StringOutput `pulumi:"type"`
	// VLAN ID. 0 means untagged.
	Vlan pulumi.IntOutput `pulumi:"vlan"`
}

// NewNetworkInterface registers a new resource with the given unique name, arguments, and options.
func NewNetworkInterface(ctx *pulumi.Context,
	name string, args *NetworkInterfaceArgs, opts ...pulumi.ResourceOption) (*NetworkInterface, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Address == nil {
		return nil, errors.New("invalid value for required argument 'Address'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Services == nil {
		return nil, errors.New("invalid value for required argument 'Services'")
	}
	if args.SubnetName == nil {
		return nil, errors.New("invalid value for required argument 'SubnetName'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NetworkInterface
	err := ctx.RegisterResource("flashblade:index/networkInterface:NetworkInterface", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkInterface gets an existing NetworkInterface resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkInterface(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkInterfaceState, opts ...pulumi.ResourceOption) (*NetworkInterface, error) {
	var resource NetworkInterface
	err := ctx.ReadResource("flashblade:index/networkInterface:NetworkInterface", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkInterface resources.
type networkInterfaceState struct {
	// The IPv4 address for this network interface.
	Address *string `pulumi:"address"`
	// List of server names attached to this interface. Required for data/sts; forbidden for egress-only/replication.
	AttachedServers []string `pulumi:"attachedServers"`
	// Whether the network interface is enabled.
	Enabled *bool `pulumi:"enabled"`
	// The gateway address for this network interface.
	Gateway *string `pulumi:"gateway"`
	// Maximum transmission unit (MTU) in bytes.
	Mtu *int `pulumi:"mtu"`
	// The name of the network interface. Changing this forces a new resource.
	Name *string `pulumi:"name"`
	// The subnet mask for this network interface.
	Netmask *string `pulumi:"netmask"`
	// List of realms associated with this network interface.
	Realms []string `pulumi:"realms"`
	// The service type for this network interface. One of: data, sts, egress-only, replication.
	Services *string `pulumi:"services"`
	// The name of the subnet this interface is attached to. Changing this forces a new resource.
	SubnetName *string `pulumi:"subnetName"`
	// The network interface type (e.g. vip). Changing this forces a new resource.
	Type *string `pulumi:"type"`
	// VLAN ID. 0 means untagged.
	Vlan *int `pulumi:"vlan"`
}

type NetworkInterfaceState struct {
	// The IPv4 address for this network interface.
	Address pulumi.StringPtrInput
	// List of server names attached to this interface. Required for data/sts; forbidden for egress-only/replication.
	AttachedServers pulumi.StringArrayInput
	// Whether the network interface is enabled.
	Enabled pulumi.BoolPtrInput
	// The gateway address for this network interface.
	Gateway pulumi.StringPtrInput
	// Maximum transmission unit (MTU) in bytes.
	Mtu pulumi.IntPtrInput
	// The name of the network interface. Changing this forces a new resource.
	Name pulumi.StringPtrInput
	// The subnet mask for this network interface.
	Netmask pulumi.StringPtrInput
	// List of realms associated with this network interface.
	Realms pulumi.StringArrayInput
	// The service type for this network interface. One of: data, sts, egress-only, replication.
	Services pulumi.StringPtrInput
	// The name of the subnet this interface is attached to. Changing this forces a new resource.
	SubnetName pulumi.StringPtrInput
	// The network interface type (e.g. vip). Changing this forces a new resource.
	Type pulumi.StringPtrInput
	// VLAN ID. 0 means untagged.
	Vlan pulumi.IntPtrInput
}

func (NetworkInterfaceState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkInterfaceState)(nil)).Elem()
}

type networkInterfaceArgs struct {
	// The IPv4 address for this network interface.
	Address string `pulumi:"address"`
	// List of server names attached to this interface. Required for data/sts; forbidden for egress-only/replication.
	AttachedServers []string `pulumi:"attachedServers"`
	// The name of the network interface. Changing this forces a new resource.
	Name string `pulumi:"name"`
	// The service type for this network interface. One of: data, sts, egress-only, replication.
	Services string `pulumi:"services"`
	// The name of the subnet this interface is attached to. Changing this forces a new resource.
	SubnetName string `pulumi:"subnetName"`
	// The network interface type (e.g. vip). Changing this forces a new resource.
	Type string `pulumi:"type"`
}

// The set of arguments for constructing a NetworkInterface resource.
type NetworkInterfaceArgs struct {
	// The IPv4 address for this network interface.
	Address pulumi.StringInput
	// List of server names attached to this interface. Required for data/sts; forbidden for egress-only/replication.
	AttachedServers pulumi.StringArrayInput
	// The name of the network interface. Changing this forces a new resource.
	Name pulumi.StringInput
	// The service type for this network interface. One of: data, sts, egress-only, replication.
	Services pulumi.StringInput
	// The name of the subnet this interface is attached to. Changing this forces a new resource.
	SubnetName pulumi.StringInput
	// The network interface type (e.g. vip). Changing this forces a new resource.
	Type pulumi.StringInput
}

func (NetworkInterfaceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkInterfaceArgs)(nil)).Elem()
}

type NetworkInterfaceInput interface {
	pulumi.Input

	ToNetworkInterfaceOutput() NetworkInterfaceOutput
	ToNetworkInterfaceOutputWithContext(ctx context.Context) NetworkInterfaceOutput
}

func (*NetworkInterface) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkInterface)(nil)).Elem()
}

func (i *NetworkInterface) ToNetworkInterfaceOutput() NetworkInterfaceOutput {
	return i.ToNetworkInterfaceOutputWithContext(context.Background())
}

func (i *NetworkInterface) ToNetworkInterfaceOutputWithContext(ctx context.Context) NetworkInterfaceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkInterfaceOutput)
}

type NetworkInterfaceOutput struct{ *pulumi.OutputState }

func (NetworkInterfaceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkInterface)(nil)).Elem()
}

func (o NetworkInterfaceOutput) ToNetworkInterfaceOutput() NetworkInterfaceOutput {
	return o
}

func (o NetworkInterfaceOutput) ToNetworkInterfaceOutputWithContext(ctx context.Context) NetworkInterfaceOutput {
	return o
}

// The IPv4 address for this network interface.
func (o NetworkInterfaceOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkInterface) pulumi.StringOutput { return v.Address }).(pulumi.StringOutput)
}

// List of server names attached to this interface. Required for data/sts; forbidden for egress-only/replication.
func (o NetworkInterfaceOutput) AttachedServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *NetworkInterface) pulumi.StringArrayOutput { return v.AttachedServers }).(pulumi.StringArrayOutput)
}

// Whether the network interface is enabled.
func (o NetworkInterfaceOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *NetworkInterface) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// The gateway address for this network interface.
func (o NetworkInterfaceOutput) Gateway() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkInterface) pulumi.StringOutput { return v.Gateway }).(pulumi.StringOutput)
}

// Maximum transmission unit (MTU) in bytes.
func (o NetworkInterfaceOutput) Mtu() pulumi.IntOutput {
	return o.ApplyT(func(v *NetworkInterface) pulumi.IntOutput { return v.Mtu }).(pulumi.IntOutput)
}

// The name of the network interface. Changing this forces a new resource.
func (o NetworkInterfaceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkInterface) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The subnet mask for this network interface.
func (o NetworkInterfaceOutput) Netmask() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkInterface) pulumi.StringOutput { return v.Netmask }).(pulumi.StringOutput)
}

// List of realms associated with this network interface.
func (o NetworkInterfaceOutput) Realms() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *NetworkInterface) pulumi.StringArrayOutput { return v.Realms }).(pulumi.StringArrayOutput)
}

// The service type for this network interface. One of: data, sts, egress-only, replication.
func (o NetworkInterfaceOutput) Services() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkInterface) pulumi.StringOutput { return v.Services }).(pulumi.StringOutput)
}

// The name of the subnet this interface is attached to. Changing this forces a new resource.
func (o NetworkInterfaceOutput) SubnetName() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkInterface) pulumi.StringOutput { return v.SubnetName }).(pulumi.StringOutput)
}

// The network interface type (e.g. vip). Changing this forces a new resource.
func (o NetworkInterfaceOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkInterface) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// VLAN ID. 0 means untagged.
func (o NetworkInterfaceOutput) Vlan() pulumi.IntOutput {
	return o.ApplyT(func(v *NetworkInterface) pulumi.IntOutput { return v.Vlan }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkInterfaceInput)(nil)).Elem(), &NetworkInterface{})
	pulumi.RegisterOutputType(NetworkInterfaceOutput{})
}
