// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ObjectStoreAccessPolicyRule struct {
	pulumi.CustomResourceState

	// List of S3 actions this rule applies to (e.g. ['s3:GetObject', 's3:PutObject']).
	Actions pulumi.StringArrayOutput `pulumi:"actions"`
	// JSON-encoded IAM conditions object (use jsonencode()). Null or empty if no conditions.
	Conditions pulumi.StringOutput `pulumi:"conditions"`
	// The effect of the rule: 'allow' or 'deny'. Read-only after creation — changing this forces a new resource.
	Effect pulumi.StringOutput `pulumi:"effect"`
	// The name of the rule. Changing this forces a new resource (rules cannot be renamed).
	Name pulumi.StringOutput `pulumi:"name"`
	// The name of the object store access policy this rule belongs to. Changing this forces a new resource.
	PolicyName pulumi.StringOutput `pulumi:"policyName"`
	// List of ARN-like resource patterns this rule applies to.
	Resources pulumi.StringArrayOutput `pulumi:"resources"`
}

// NewObjectStoreAccessPolicyRule registers a new resource with the given unique name, arguments, and options.
func NewObjectStoreAccessPolicyRule(ctx *pulumi.Context,
	name string, args *ObjectStoreAccessPolicyRuleArgs, opts ...pulumi.ResourceOption) (*ObjectStoreAccessPolicyRule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Actions == nil {
		return nil, errors.New("invalid value for required argument 'Actions'")
	}
	if args.Effect == nil {
		return nil, errors.New("invalid value for required argument 'Effect'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.PolicyName == nil {
		return nil, errors.New("invalid value for required argument 'PolicyName'")
	}
	if args.Resources == nil {
		return nil, errors.New("invalid value for required argument 'Resources'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ObjectStoreAccessPolicyRule
	err := ctx.RegisterResource("flashblade:index/objectStoreAccessPolicyRule:ObjectStoreAccessPolicyRule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetObjectStoreAccessPolicyRule gets an existing ObjectStoreAccessPolicyRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetObjectStoreAccessPolicyRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ObjectStoreAccessPolicyRuleState, opts ...pulumi.ResourceOption) (*ObjectStoreAccessPolicyRule, error) {
	var resource ObjectStoreAccessPolicyRule
	err := ctx.ReadResource("flashblade:index/objectStoreAccessPolicyRule:ObjectStoreAccessPolicyRule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ObjectStoreAccessPolicyRule resources.
type objectStoreAccessPolicyRuleState struct {
	// List of S3 actions this rule applies to (e.g. ['s3:GetObject', 's3:PutObject']).
	Actions []string `pulumi:"actions"`
	// JSON-encoded IAM conditions object (use jsonencode()). Null or empty if no conditions.
	Conditions *string `pulumi:"conditions"`
	// The effect of the rule: 'allow' or 'deny'. Read-only after creation — changing this forces a new resource.
	Effect *string `pulumi:"effect"`
	// The name of the rule. Changing this forces a new resource (rules cannot be renamed).
	Name *string `pulumi:"name"`
	// The name of the object store access policy this rule belongs to. Changing this forces a new resource.
	PolicyName *string `pulumi:"policyName"`
	// List of ARN-like resource patterns this rule applies to.
	Resources []string `pulumi:"resources"`
}

type ObjectStoreAccessPolicyRuleState struct {
	// List of S3 actions this rule applies to (e.g. ['s3:GetObject', 's3:PutObject']).
	Actions pulumi.StringArrayInput
	// JSON-encoded IAM conditions object (use jsonencode()). Null or empty if no conditions.
	Conditions pulumi.StringPtrInput
	// The effect of the rule: 'allow' or 'deny'. Read-only after creation — changing this forces a new resource.
	Effect pulumi.StringPtrInput
	// The name of the rule. Changing this forces a new resource (rules cannot be renamed).
	Name pulumi.StringPtrInput
	// The name of the object store access policy this rule belongs to. Changing this forces a new resource.
	PolicyName pulumi.StringPtrInput
	// List of ARN-like resource patterns this rule applies to.
	Resources pulumi.StringArrayInput
}

func (ObjectStoreAccessPolicyRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*objectStoreAccessPolicyRuleState)(nil)).Elem()
}

type objectStoreAccessPolicyRuleArgs struct {
	// List of S3 actions this rule applies to (e.g. ['s3:GetObject', 's3:PutObject']).
	Actions []string `pulumi:"actions"`
	// JSON-encoded IAM conditions object (use jsonencode()). Null or empty if no conditions.
	Conditions *string `pulumi:"conditions"`
	// The effect of the rule: 'allow' or 'deny'. Read-only after creation — changing this forces a new resource.
	Effect string `pulumi:"effect"`
	// The name of the rule. Changing this forces a new resource (rules cannot be renamed).
	Name string `pulumi:"name"`
	// The name of the object store access policy this rule belongs to. Changing this forces a new resource.
	PolicyName string `pulumi:"policyName"`
	// List of ARN-like resource patterns this rule applies to.
	Resources []string `pulumi:"resources"`
}

// The set of arguments for constructing a ObjectStoreAccessPolicyRule resource.
type ObjectStoreAccessPolicyRuleArgs struct {
	// List of S3 actions this rule applies to (e.g. ['s3:GetObject', 's3:PutObject']).
	Actions pulumi.StringArrayInput
	// JSON-encoded IAM conditions object (use jsonencode()). Null or empty if no conditions.
	Conditions pulumi.StringPtrInput
	// The effect of the rule: 'allow' or 'deny'. Read-only after creation — changing this forces a new resource.
	Effect pulumi.StringInput
	// The name of the rule. Changing this forces a new resource (rules cannot be renamed).
	Name pulumi.StringInput
	// The name of the object store access policy this rule belongs to. Changing this forces a new resource.
	PolicyName pulumi.StringInput
	// List of ARN-like resource patterns this rule applies to.
	Resources pulumi.StringArrayInput
}

func (ObjectStoreAccessPolicyRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*objectStoreAccessPolicyRuleArgs)(nil)).Elem()
}

type ObjectStoreAccessPolicyRuleInput interface {
	pulumi.Input

	ToObjectStoreAccessPolicyRuleOutput() ObjectStoreAccessPolicyRuleOutput
	ToObjectStoreAccessPolicyRuleOutputWithContext(ctx context.Context) ObjectStoreAccessPolicyRuleOutput
}

func (*ObjectStoreAccessPolicyRule) ElementType() reflect.Type {
	return reflect.TypeOf((**ObjectStoreAccessPolicyRule)(nil)).Elem()
}

func (i *ObjectStoreAccessPolicyRule) ToObjectStoreAccessPolicyRuleOutput() ObjectStoreAccessPolicyRuleOutput {
	return i.ToObjectStoreAccessPolicyRuleOutputWithContext(context.Background())
}

func (i *ObjectStoreAccessPolicyRule) ToObjectStoreAccessPolicyRuleOutputWithContext(ctx context.Context) ObjectStoreAccessPolicyRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ObjectStoreAccessPolicyRuleOutput)
}

type ObjectStoreAccessPolicyRuleOutput struct{ *pulumi.OutputState }

func (ObjectStoreAccessPolicyRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ObjectStoreAccessPolicyRule)(nil)).Elem()
}

func (o ObjectStoreAccessPolicyRuleOutput) ToObjectStoreAccessPolicyRuleOutput() ObjectStoreAccessPolicyRuleOutput {
	return o
}

func (o ObjectStoreAccessPolicyRuleOutput) ToObjectStoreAccessPolicyRuleOutputWithContext(ctx context.Context) ObjectStoreAccessPolicyRuleOutput {
	return o
}

// List of S3 actions this rule applies to (e.g. ['s3:GetObject', 's3:PutObject']).
func (o ObjectStoreAccessPolicyRuleOutput) Actions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ObjectStoreAccessPolicyRule) pulumi.StringArrayOutput { return v.Actions }).(pulumi.StringArrayOutput)
}

// JSON-encoded IAM conditions object (use jsonencode()). Null or empty if no conditions.
func (o ObjectStoreAccessPolicyRuleOutput) Conditions() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStoreAccessPolicyRule) pulumi.StringOutput { return v.Conditions }).(pulumi.StringOutput)
}

// The effect of the rule: 'allow' or 'deny'. Read-only after creation — changing this forces a new resource.
func (o ObjectStoreAccessPolicyRuleOutput) Effect() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStoreAccessPolicyRule) pulumi.StringOutput { return v.Effect }).(pulumi.StringOutput)
}

// The name of the rule. Changing this forces a new resource (rules cannot be renamed).
func (o ObjectStoreAccessPolicyRuleOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStoreAccessPolicyRule) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The name of the object store access policy this rule belongs to. Changing this forces a new resource.
func (o ObjectStoreAccessPolicyRuleOutput) PolicyName() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStoreAccessPolicyRule) pulumi.StringOutput { return v.PolicyName }).(pulumi.StringOutput)
}

// List of ARN-like resource patterns this rule applies to.
func (o ObjectStoreAccessPolicyRuleOutput) Resources() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ObjectStoreAccessPolicyRule) pulumi.StringArrayOutput { return v.Resources }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ObjectStoreAccessPolicyRuleInput)(nil)).Elem(), &ObjectStoreAccessPolicyRule{})
	pulumi.RegisterOutputType(ObjectStoreAccessPolicyRuleOutput{})
}
