// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/opentofu-provider-flashblade/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ObjectStoreAccessKey struct {
	pulumi.CustomResourceState

	// The access key ID (public part of the credential pair).
	AccessKeyId pulumi.StringOutput `pulumi:"accessKeyId"`
	// Unix timestamp (milliseconds) when the access key was created.
	Created pulumi.IntOutput `pulumi:"created"`
	// If true, the access key is enabled. Changing this forces a new resource.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// The access key name (format: <account>/admin/<key-id>). When providing a secretAccessKey for cross-array replication, this must be set to the same name as the source key. When omitted, the API assigns it automatically.
	Name pulumi.StringOutput `pulumi:"name"`
	// The object store account this access key belongs to. Changing this forces a new resource.
	ObjectStoreAccount pulumi.StringOutput `pulumi:"objectStoreAccount"`
	// The secret access key. When provided, the key is created with this exact secret (for cross-array replication). When omitted, the API generates it. Returned only at creation time and stored in state (encrypted).
	SecretAccessKey pulumi.StringOutput `pulumi:"secretAccessKey"`
	// The S3 user this access key belongs to (format: account/username). When omitted, defaults to account/admin. Changing this forces a new resource.
	User pulumi.StringOutput `pulumi:"user"`
}

// NewObjectStoreAccessKey registers a new resource with the given unique name, arguments, and options.
func NewObjectStoreAccessKey(ctx *pulumi.Context,
	name string, args *ObjectStoreAccessKeyArgs, opts ...pulumi.ResourceOption) (*ObjectStoreAccessKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ObjectStoreAccount == nil {
		return nil, errors.New("invalid value for required argument 'ObjectStoreAccount'")
	}
	if args.SecretAccessKey != nil {
		args.SecretAccessKey = pulumi.ToSecret(args.SecretAccessKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"secretAccessKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ObjectStoreAccessKey
	err := ctx.RegisterResource("flashblade:index/objectStoreAccessKey:ObjectStoreAccessKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetObjectStoreAccessKey gets an existing ObjectStoreAccessKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetObjectStoreAccessKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ObjectStoreAccessKeyState, opts ...pulumi.ResourceOption) (*ObjectStoreAccessKey, error) {
	var resource ObjectStoreAccessKey
	err := ctx.ReadResource("flashblade:index/objectStoreAccessKey:ObjectStoreAccessKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ObjectStoreAccessKey resources.
type objectStoreAccessKeyState struct {
	// The access key ID (public part of the credential pair).
	AccessKeyId *string `pulumi:"accessKeyId"`
	// Unix timestamp (milliseconds) when the access key was created.
	Created *int `pulumi:"created"`
	// If true, the access key is enabled. Changing this forces a new resource.
	Enabled *bool `pulumi:"enabled"`
	// The access key name (format: <account>/admin/<key-id>). When providing a secretAccessKey for cross-array replication, this must be set to the same name as the source key. When omitted, the API assigns it automatically.
	Name *string `pulumi:"name"`
	// The object store account this access key belongs to. Changing this forces a new resource.
	ObjectStoreAccount *string `pulumi:"objectStoreAccount"`
	// The secret access key. When provided, the key is created with this exact secret (for cross-array replication). When omitted, the API generates it. Returned only at creation time and stored in state (encrypted).
	SecretAccessKey *string `pulumi:"secretAccessKey"`
	// The S3 user this access key belongs to (format: account/username). When omitted, defaults to account/admin. Changing this forces a new resource.
	User *string `pulumi:"user"`
}

type ObjectStoreAccessKeyState struct {
	// The access key ID (public part of the credential pair).
	AccessKeyId pulumi.StringPtrInput
	// Unix timestamp (milliseconds) when the access key was created.
	Created pulumi.IntPtrInput
	// If true, the access key is enabled. Changing this forces a new resource.
	Enabled pulumi.BoolPtrInput
	// The access key name (format: <account>/admin/<key-id>). When providing a secretAccessKey for cross-array replication, this must be set to the same name as the source key. When omitted, the API assigns it automatically.
	Name pulumi.StringPtrInput
	// The object store account this access key belongs to. Changing this forces a new resource.
	ObjectStoreAccount pulumi.StringPtrInput
	// The secret access key. When provided, the key is created with this exact secret (for cross-array replication). When omitted, the API generates it. Returned only at creation time and stored in state (encrypted).
	SecretAccessKey pulumi.StringPtrInput
	// The S3 user this access key belongs to (format: account/username). When omitted, defaults to account/admin. Changing this forces a new resource.
	User pulumi.StringPtrInput
}

func (ObjectStoreAccessKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*objectStoreAccessKeyState)(nil)).Elem()
}

type objectStoreAccessKeyArgs struct {
	// If true, the access key is enabled. Changing this forces a new resource.
	Enabled *bool `pulumi:"enabled"`
	// The access key name (format: <account>/admin/<key-id>). When providing a secretAccessKey for cross-array replication, this must be set to the same name as the source key. When omitted, the API assigns it automatically.
	Name *string `pulumi:"name"`
	// The object store account this access key belongs to. Changing this forces a new resource.
	ObjectStoreAccount string `pulumi:"objectStoreAccount"`
	// The secret access key. When provided, the key is created with this exact secret (for cross-array replication). When omitted, the API generates it. Returned only at creation time and stored in state (encrypted).
	SecretAccessKey *string `pulumi:"secretAccessKey"`
	// The S3 user this access key belongs to (format: account/username). When omitted, defaults to account/admin. Changing this forces a new resource.
	User *string `pulumi:"user"`
}

// The set of arguments for constructing a ObjectStoreAccessKey resource.
type ObjectStoreAccessKeyArgs struct {
	// If true, the access key is enabled. Changing this forces a new resource.
	Enabled pulumi.BoolPtrInput
	// The access key name (format: <account>/admin/<key-id>). When providing a secretAccessKey for cross-array replication, this must be set to the same name as the source key. When omitted, the API assigns it automatically.
	Name pulumi.StringPtrInput
	// The object store account this access key belongs to. Changing this forces a new resource.
	ObjectStoreAccount pulumi.StringInput
	// The secret access key. When provided, the key is created with this exact secret (for cross-array replication). When omitted, the API generates it. Returned only at creation time and stored in state (encrypted).
	SecretAccessKey pulumi.StringPtrInput
	// The S3 user this access key belongs to (format: account/username). When omitted, defaults to account/admin. Changing this forces a new resource.
	User pulumi.StringPtrInput
}

func (ObjectStoreAccessKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*objectStoreAccessKeyArgs)(nil)).Elem()
}

type ObjectStoreAccessKeyInput interface {
	pulumi.Input

	ToObjectStoreAccessKeyOutput() ObjectStoreAccessKeyOutput
	ToObjectStoreAccessKeyOutputWithContext(ctx context.Context) ObjectStoreAccessKeyOutput
}

func (*ObjectStoreAccessKey) ElementType() reflect.Type {
	return reflect.TypeOf((**ObjectStoreAccessKey)(nil)).Elem()
}

func (i *ObjectStoreAccessKey) ToObjectStoreAccessKeyOutput() ObjectStoreAccessKeyOutput {
	return i.ToObjectStoreAccessKeyOutputWithContext(context.Background())
}

func (i *ObjectStoreAccessKey) ToObjectStoreAccessKeyOutputWithContext(ctx context.Context) ObjectStoreAccessKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ObjectStoreAccessKeyOutput)
}

type ObjectStoreAccessKeyOutput struct{ *pulumi.OutputState }

func (ObjectStoreAccessKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ObjectStoreAccessKey)(nil)).Elem()
}

func (o ObjectStoreAccessKeyOutput) ToObjectStoreAccessKeyOutput() ObjectStoreAccessKeyOutput {
	return o
}

func (o ObjectStoreAccessKeyOutput) ToObjectStoreAccessKeyOutputWithContext(ctx context.Context) ObjectStoreAccessKeyOutput {
	return o
}

// The access key ID (public part of the credential pair).
func (o ObjectStoreAccessKeyOutput) AccessKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStoreAccessKey) pulumi.StringOutput { return v.AccessKeyId }).(pulumi.StringOutput)
}

// Unix timestamp (milliseconds) when the access key was created.
func (o ObjectStoreAccessKeyOutput) Created() pulumi.IntOutput {
	return o.ApplyT(func(v *ObjectStoreAccessKey) pulumi.IntOutput { return v.Created }).(pulumi.IntOutput)
}

// If true, the access key is enabled. Changing this forces a new resource.
func (o ObjectStoreAccessKeyOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *ObjectStoreAccessKey) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// The access key name (format: <account>/admin/<key-id>). When providing a secretAccessKey for cross-array replication, this must be set to the same name as the source key. When omitted, the API assigns it automatically.
func (o ObjectStoreAccessKeyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStoreAccessKey) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The object store account this access key belongs to. Changing this forces a new resource.
func (o ObjectStoreAccessKeyOutput) ObjectStoreAccount() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStoreAccessKey) pulumi.StringOutput { return v.ObjectStoreAccount }).(pulumi.StringOutput)
}

// The secret access key. When provided, the key is created with this exact secret (for cross-array replication). When omitted, the API generates it. Returned only at creation time and stored in state (encrypted).
func (o ObjectStoreAccessKeyOutput) SecretAccessKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStoreAccessKey) pulumi.StringOutput { return v.SecretAccessKey }).(pulumi.StringOutput)
}

// The S3 user this access key belongs to (format: account/username). When omitted, defaults to account/admin. Changing this forces a new resource.
func (o ObjectStoreAccessKeyOutput) User() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStoreAccessKey) pulumi.StringOutput { return v.User }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ObjectStoreAccessKeyInput)(nil)).Elem(), &ObjectStoreAccessKey{})
	pulumi.RegisterOutputType(ObjectStoreAccessKeyOutput{})
}
