// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type QosPolicyMember struct {
	pulumi.CustomResourceState

	// The name of the file system or realm to assign. Changing this forces a new resource.
	MemberName pulumi.StringOutput `pulumi:"memberName"`
	// The type of the member. Valid values: file-systems, realms. Note: buckets are not supported on API v2.22.
	MemberType pulumi.StringOutput `pulumi:"memberType"`
	// The name of the QoS policy. Changing this forces a new resource.
	PolicyName pulumi.StringOutput `pulumi:"policyName"`
}

// NewQosPolicyMember registers a new resource with the given unique name, arguments, and options.
func NewQosPolicyMember(ctx *pulumi.Context,
	name string, args *QosPolicyMemberArgs, opts ...pulumi.ResourceOption) (*QosPolicyMember, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.MemberName == nil {
		return nil, errors.New("invalid value for required argument 'MemberName'")
	}
	if args.MemberType == nil {
		return nil, errors.New("invalid value for required argument 'MemberType'")
	}
	if args.PolicyName == nil {
		return nil, errors.New("invalid value for required argument 'PolicyName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource QosPolicyMember
	err := ctx.RegisterResource("flashblade:index/qosPolicyMember:QosPolicyMember", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetQosPolicyMember gets an existing QosPolicyMember resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetQosPolicyMember(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *QosPolicyMemberState, opts ...pulumi.ResourceOption) (*QosPolicyMember, error) {
	var resource QosPolicyMember
	err := ctx.ReadResource("flashblade:index/qosPolicyMember:QosPolicyMember", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering QosPolicyMember resources.
type qosPolicyMemberState struct {
	// The name of the file system or realm to assign. Changing this forces a new resource.
	MemberName *string `pulumi:"memberName"`
	// The type of the member. Valid values: file-systems, realms. Note: buckets are not supported on API v2.22.
	MemberType *string `pulumi:"memberType"`
	// The name of the QoS policy. Changing this forces a new resource.
	PolicyName *string `pulumi:"policyName"`
}

type QosPolicyMemberState struct {
	// The name of the file system or realm to assign. Changing this forces a new resource.
	MemberName pulumi.StringPtrInput
	// The type of the member. Valid values: file-systems, realms. Note: buckets are not supported on API v2.22.
	MemberType pulumi.StringPtrInput
	// The name of the QoS policy. Changing this forces a new resource.
	PolicyName pulumi.StringPtrInput
}

func (QosPolicyMemberState) ElementType() reflect.Type {
	return reflect.TypeOf((*qosPolicyMemberState)(nil)).Elem()
}

type qosPolicyMemberArgs struct {
	// The name of the file system or realm to assign. Changing this forces a new resource.
	MemberName string `pulumi:"memberName"`
	// The type of the member. Valid values: file-systems, realms. Note: buckets are not supported on API v2.22.
	MemberType string `pulumi:"memberType"`
	// The name of the QoS policy. Changing this forces a new resource.
	PolicyName string `pulumi:"policyName"`
}

// The set of arguments for constructing a QosPolicyMember resource.
type QosPolicyMemberArgs struct {
	// The name of the file system or realm to assign. Changing this forces a new resource.
	MemberName pulumi.StringInput
	// The type of the member. Valid values: file-systems, realms. Note: buckets are not supported on API v2.22.
	MemberType pulumi.StringInput
	// The name of the QoS policy. Changing this forces a new resource.
	PolicyName pulumi.StringInput
}

func (QosPolicyMemberArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*qosPolicyMemberArgs)(nil)).Elem()
}

type QosPolicyMemberInput interface {
	pulumi.Input

	ToQosPolicyMemberOutput() QosPolicyMemberOutput
	ToQosPolicyMemberOutputWithContext(ctx context.Context) QosPolicyMemberOutput
}

func (*QosPolicyMember) ElementType() reflect.Type {
	return reflect.TypeOf((**QosPolicyMember)(nil)).Elem()
}

func (i *QosPolicyMember) ToQosPolicyMemberOutput() QosPolicyMemberOutput {
	return i.ToQosPolicyMemberOutputWithContext(context.Background())
}

func (i *QosPolicyMember) ToQosPolicyMemberOutputWithContext(ctx context.Context) QosPolicyMemberOutput {
	return pulumi.ToOutputWithContext(ctx, i).(QosPolicyMemberOutput)
}

type QosPolicyMemberOutput struct{ *pulumi.OutputState }

func (QosPolicyMemberOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**QosPolicyMember)(nil)).Elem()
}

func (o QosPolicyMemberOutput) ToQosPolicyMemberOutput() QosPolicyMemberOutput {
	return o
}

func (o QosPolicyMemberOutput) ToQosPolicyMemberOutputWithContext(ctx context.Context) QosPolicyMemberOutput {
	return o
}

// The name of the file system or realm to assign. Changing this forces a new resource.
func (o QosPolicyMemberOutput) MemberName() pulumi.StringOutput {
	return o.ApplyT(func(v *QosPolicyMember) pulumi.StringOutput { return v.MemberName }).(pulumi.StringOutput)
}

// The type of the member. Valid values: file-systems, realms. Note: buckets are not supported on API v2.22.
func (o QosPolicyMemberOutput) MemberType() pulumi.StringOutput {
	return o.ApplyT(func(v *QosPolicyMember) pulumi.StringOutput { return v.MemberType }).(pulumi.StringOutput)
}

// The name of the QoS policy. Changing this forces a new resource.
func (o QosPolicyMemberOutput) PolicyName() pulumi.StringOutput {
	return o.ApplyT(func(v *QosPolicyMember) pulumi.StringOutput { return v.PolicyName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*QosPolicyMemberInput)(nil)).Elem(), &QosPolicyMember{})
	pulumi.RegisterOutputType(QosPolicyMemberOutput{})
}
