// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flashblade

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/flashblade/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type TlsPolicyMember struct {
	pulumi.CustomResourceState

	// The name of the network interface to assign. Changing this forces a new resource.
	MemberName pulumi.StringOutput `pulumi:"memberName"`
	// The name of the TLS policy. Changing this forces a new resource.
	PolicyName pulumi.StringOutput `pulumi:"policyName"`
}

// NewTlsPolicyMember registers a new resource with the given unique name, arguments, and options.
func NewTlsPolicyMember(ctx *pulumi.Context,
	name string, args *TlsPolicyMemberArgs, opts ...pulumi.ResourceOption) (*TlsPolicyMember, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.MemberName == nil {
		return nil, errors.New("invalid value for required argument 'MemberName'")
	}
	if args.PolicyName == nil {
		return nil, errors.New("invalid value for required argument 'PolicyName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TlsPolicyMember
	err := ctx.RegisterResource("flashblade:index/tlsPolicyMember:TlsPolicyMember", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTlsPolicyMember gets an existing TlsPolicyMember resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTlsPolicyMember(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TlsPolicyMemberState, opts ...pulumi.ResourceOption) (*TlsPolicyMember, error) {
	var resource TlsPolicyMember
	err := ctx.ReadResource("flashblade:index/tlsPolicyMember:TlsPolicyMember", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TlsPolicyMember resources.
type tlsPolicyMemberState struct {
	// The name of the network interface to assign. Changing this forces a new resource.
	MemberName *string `pulumi:"memberName"`
	// The name of the TLS policy. Changing this forces a new resource.
	PolicyName *string `pulumi:"policyName"`
}

type TlsPolicyMemberState struct {
	// The name of the network interface to assign. Changing this forces a new resource.
	MemberName pulumi.StringPtrInput
	// The name of the TLS policy. Changing this forces a new resource.
	PolicyName pulumi.StringPtrInput
}

func (TlsPolicyMemberState) ElementType() reflect.Type {
	return reflect.TypeOf((*tlsPolicyMemberState)(nil)).Elem()
}

type tlsPolicyMemberArgs struct {
	// The name of the network interface to assign. Changing this forces a new resource.
	MemberName string `pulumi:"memberName"`
	// The name of the TLS policy. Changing this forces a new resource.
	PolicyName string `pulumi:"policyName"`
}

// The set of arguments for constructing a TlsPolicyMember resource.
type TlsPolicyMemberArgs struct {
	// The name of the network interface to assign. Changing this forces a new resource.
	MemberName pulumi.StringInput
	// The name of the TLS policy. Changing this forces a new resource.
	PolicyName pulumi.StringInput
}

func (TlsPolicyMemberArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*tlsPolicyMemberArgs)(nil)).Elem()
}

type TlsPolicyMemberInput interface {
	pulumi.Input

	ToTlsPolicyMemberOutput() TlsPolicyMemberOutput
	ToTlsPolicyMemberOutputWithContext(ctx context.Context) TlsPolicyMemberOutput
}

func (*TlsPolicyMember) ElementType() reflect.Type {
	return reflect.TypeOf((**TlsPolicyMember)(nil)).Elem()
}

func (i *TlsPolicyMember) ToTlsPolicyMemberOutput() TlsPolicyMemberOutput {
	return i.ToTlsPolicyMemberOutputWithContext(context.Background())
}

func (i *TlsPolicyMember) ToTlsPolicyMemberOutputWithContext(ctx context.Context) TlsPolicyMemberOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TlsPolicyMemberOutput)
}

type TlsPolicyMemberOutput struct{ *pulumi.OutputState }

func (TlsPolicyMemberOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TlsPolicyMember)(nil)).Elem()
}

func (o TlsPolicyMemberOutput) ToTlsPolicyMemberOutput() TlsPolicyMemberOutput {
	return o
}

func (o TlsPolicyMemberOutput) ToTlsPolicyMemberOutputWithContext(ctx context.Context) TlsPolicyMemberOutput {
	return o
}

// The name of the network interface to assign. Changing this forces a new resource.
func (o TlsPolicyMemberOutput) MemberName() pulumi.StringOutput {
	return o.ApplyT(func(v *TlsPolicyMember) pulumi.StringOutput { return v.MemberName }).(pulumi.StringOutput)
}

// The name of the TLS policy. Changing this forces a new resource.
func (o TlsPolicyMemberOutput) PolicyName() pulumi.StringOutput {
	return o.ApplyT(func(v *TlsPolicyMember) pulumi.StringOutput { return v.PolicyName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TlsPolicyMemberInput)(nil)).Elem(), &TlsPolicyMember{})
	pulumi.RegisterOutputType(TlsPolicyMemberOutput{})
}
