# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['BucketAccessPolicyRuleArgs', 'BucketAccessPolicyRule']

@pulumi.input_type
class BucketAccessPolicyRuleArgs:
    def __init__(__self__, *,
                 actions: pulumi.Input[Sequence[pulumi.Input[builtins.str]]],
                 bucket_name: pulumi.Input[builtins.str],
                 principals: pulumi.Input[Sequence[pulumi.Input[builtins.str]]],
                 resources: pulumi.Input[Sequence[pulumi.Input[builtins.str]]],
                 name: Optional[pulumi.Input[builtins.str]] = None):
        """
        The set of arguments for constructing a BucketAccessPolicyRule resource.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] actions: List of S3 actions this rule applies to (e.g. s3:GetObject).
        :param pulumi.Input[builtins.str] bucket_name: The name of the bucket this rule belongs to. Changing this forces a new resource.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] principals: List of principals this rule applies to (mapped to principals.all in the API). Note: the accepted format depends on the FlashBlade firmware version — consult your array documentation for valid principal values.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] resources: List of S3 resource ARNs this rule applies to.
        :param pulumi.Input[builtins.str] name: The rule name. When provided, the rule is created with this name. When omitted, the API assigns one automatically.
        """
        pulumi.set(__self__, "actions", actions)
        pulumi.set(__self__, "bucket_name", bucket_name)
        pulumi.set(__self__, "principals", principals)
        pulumi.set(__self__, "resources", resources)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter
    def actions(self) -> pulumi.Input[Sequence[pulumi.Input[builtins.str]]]:
        """
        List of S3 actions this rule applies to (e.g. s3:GetObject).
        """
        return pulumi.get(self, "actions")

    @actions.setter
    def actions(self, value: pulumi.Input[Sequence[pulumi.Input[builtins.str]]]):
        pulumi.set(self, "actions", value)

    @property
    @pulumi.getter(name="bucketName")
    def bucket_name(self) -> pulumi.Input[builtins.str]:
        """
        The name of the bucket this rule belongs to. Changing this forces a new resource.
        """
        return pulumi.get(self, "bucket_name")

    @bucket_name.setter
    def bucket_name(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "bucket_name", value)

    @property
    @pulumi.getter
    def principals(self) -> pulumi.Input[Sequence[pulumi.Input[builtins.str]]]:
        """
        List of principals this rule applies to (mapped to principals.all in the API). Note: the accepted format depends on the FlashBlade firmware version — consult your array documentation for valid principal values.
        """
        return pulumi.get(self, "principals")

    @principals.setter
    def principals(self, value: pulumi.Input[Sequence[pulumi.Input[builtins.str]]]):
        pulumi.set(self, "principals", value)

    @property
    @pulumi.getter
    def resources(self) -> pulumi.Input[Sequence[pulumi.Input[builtins.str]]]:
        """
        List of S3 resource ARNs this rule applies to.
        """
        return pulumi.get(self, "resources")

    @resources.setter
    def resources(self, value: pulumi.Input[Sequence[pulumi.Input[builtins.str]]]):
        pulumi.set(self, "resources", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The rule name. When provided, the rule is created with this name. When omitted, the API assigns one automatically.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _BucketAccessPolicyRuleState:
    def __init__(__self__, *,
                 actions: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 bucket_name: Optional[pulumi.Input[builtins.str]] = None,
                 effect: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 principals: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 resources: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering BucketAccessPolicyRule resources.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] actions: List of S3 actions this rule applies to (e.g. s3:GetObject).
        :param pulumi.Input[builtins.str] bucket_name: The name of the bucket this rule belongs to. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] effect: The effect of the rule. Always 'allow' — set by the API.
        :param pulumi.Input[builtins.str] name: The rule name. When provided, the rule is created with this name. When omitted, the API assigns one automatically.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] principals: List of principals this rule applies to (mapped to principals.all in the API). Note: the accepted format depends on the FlashBlade firmware version — consult your array documentation for valid principal values.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] resources: List of S3 resource ARNs this rule applies to.
        """
        if actions is not None:
            pulumi.set(__self__, "actions", actions)
        if bucket_name is not None:
            pulumi.set(__self__, "bucket_name", bucket_name)
        if effect is not None:
            pulumi.set(__self__, "effect", effect)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if principals is not None:
            pulumi.set(__self__, "principals", principals)
        if resources is not None:
            pulumi.set(__self__, "resources", resources)

    @property
    @pulumi.getter
    def actions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]:
        """
        List of S3 actions this rule applies to (e.g. s3:GetObject).
        """
        return pulumi.get(self, "actions")

    @actions.setter
    def actions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]):
        pulumi.set(self, "actions", value)

    @property
    @pulumi.getter(name="bucketName")
    def bucket_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the bucket this rule belongs to. Changing this forces a new resource.
        """
        return pulumi.get(self, "bucket_name")

    @bucket_name.setter
    def bucket_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "bucket_name", value)

    @property
    @pulumi.getter
    def effect(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The effect of the rule. Always 'allow' — set by the API.
        """
        return pulumi.get(self, "effect")

    @effect.setter
    def effect(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "effect", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The rule name. When provided, the rule is created with this name. When omitted, the API assigns one automatically.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def principals(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]:
        """
        List of principals this rule applies to (mapped to principals.all in the API). Note: the accepted format depends on the FlashBlade firmware version — consult your array documentation for valid principal values.
        """
        return pulumi.get(self, "principals")

    @principals.setter
    def principals(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]):
        pulumi.set(self, "principals", value)

    @property
    @pulumi.getter
    def resources(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]:
        """
        List of S3 resource ARNs this rule applies to.
        """
        return pulumi.get(self, "resources")

    @resources.setter
    def resources(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]]):
        pulumi.set(self, "resources", value)


class BucketAccessPolicyRule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 actions: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 bucket_name: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 principals: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 resources: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 __props__=None):
        """
        Create a BucketAccessPolicyRule resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] actions: List of S3 actions this rule applies to (e.g. s3:GetObject).
        :param pulumi.Input[builtins.str] bucket_name: The name of the bucket this rule belongs to. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] name: The rule name. When provided, the rule is created with this name. When omitted, the API assigns one automatically.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] principals: List of principals this rule applies to (mapped to principals.all in the API). Note: the accepted format depends on the FlashBlade firmware version — consult your array documentation for valid principal values.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] resources: List of S3 resource ARNs this rule applies to.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: BucketAccessPolicyRuleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a BucketAccessPolicyRule resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param BucketAccessPolicyRuleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(BucketAccessPolicyRuleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 actions: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 bucket_name: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 principals: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 resources: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = BucketAccessPolicyRuleArgs.__new__(BucketAccessPolicyRuleArgs)

            if actions is None and not opts.urn:
                raise TypeError("Missing required property 'actions'")
            __props__.__dict__["actions"] = actions
            if bucket_name is None and not opts.urn:
                raise TypeError("Missing required property 'bucket_name'")
            __props__.__dict__["bucket_name"] = bucket_name
            __props__.__dict__["name"] = name
            if principals is None and not opts.urn:
                raise TypeError("Missing required property 'principals'")
            __props__.__dict__["principals"] = principals
            if resources is None and not opts.urn:
                raise TypeError("Missing required property 'resources'")
            __props__.__dict__["resources"] = resources
            __props__.__dict__["effect"] = None
        super(BucketAccessPolicyRule, __self__).__init__(
            'mica:index/bucketAccessPolicyRule:BucketAccessPolicyRule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            actions: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
            bucket_name: Optional[pulumi.Input[builtins.str]] = None,
            effect: Optional[pulumi.Input[builtins.str]] = None,
            name: Optional[pulumi.Input[builtins.str]] = None,
            principals: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None,
            resources: Optional[pulumi.Input[Sequence[pulumi.Input[builtins.str]]]] = None) -> 'BucketAccessPolicyRule':
        """
        Get an existing BucketAccessPolicyRule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] actions: List of S3 actions this rule applies to (e.g. s3:GetObject).
        :param pulumi.Input[builtins.str] bucket_name: The name of the bucket this rule belongs to. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] effect: The effect of the rule. Always 'allow' — set by the API.
        :param pulumi.Input[builtins.str] name: The rule name. When provided, the rule is created with this name. When omitted, the API assigns one automatically.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] principals: List of principals this rule applies to (mapped to principals.all in the API). Note: the accepted format depends on the FlashBlade firmware version — consult your array documentation for valid principal values.
        :param pulumi.Input[Sequence[pulumi.Input[builtins.str]]] resources: List of S3 resource ARNs this rule applies to.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _BucketAccessPolicyRuleState.__new__(_BucketAccessPolicyRuleState)

        __props__.__dict__["actions"] = actions
        __props__.__dict__["bucket_name"] = bucket_name
        __props__.__dict__["effect"] = effect
        __props__.__dict__["name"] = name
        __props__.__dict__["principals"] = principals
        __props__.__dict__["resources"] = resources
        return BucketAccessPolicyRule(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def actions(self) -> pulumi.Output[Sequence[builtins.str]]:
        """
        List of S3 actions this rule applies to (e.g. s3:GetObject).
        """
        return pulumi.get(self, "actions")

    @property
    @pulumi.getter(name="bucketName")
    def bucket_name(self) -> pulumi.Output[builtins.str]:
        """
        The name of the bucket this rule belongs to. Changing this forces a new resource.
        """
        return pulumi.get(self, "bucket_name")

    @property
    @pulumi.getter
    def effect(self) -> pulumi.Output[builtins.str]:
        """
        The effect of the rule. Always 'allow' — set by the API.
        """
        return pulumi.get(self, "effect")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[builtins.str]:
        """
        The rule name. When provided, the rule is created with this name. When omitted, the API assigns one automatically.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def principals(self) -> pulumi.Output[Sequence[builtins.str]]:
        """
        List of principals this rule applies to (mapped to principals.all in the API). Note: the accepted format depends on the FlashBlade firmware version — consult your array documentation for valid principal values.
        """
        return pulumi.get(self, "principals")

    @property
    @pulumi.getter
    def resources(self) -> pulumi.Output[Sequence[builtins.str]]:
        """
        List of S3 resource ARNs this rule applies to.
        """
        return pulumi.get(self, "resources")

