# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetObjectStoreAccountResult',
    'AwaitableGetObjectStoreAccountResult',
    'get_object_store_account',
    'get_object_store_account_output',
]

@pulumi.output_type
class GetObjectStoreAccountResult:
    """
    A collection of values returned by getObjectStoreAccount.
    """
    def __init__(__self__, created=None, hard_limit_enabled=None, id=None, name=None, object_count=None, quota_limit=None, space=None):
        if created and not isinstance(created, int):
            raise TypeError("Expected argument 'created' to be a int")
        pulumi.set(__self__, "created", created)
        if hard_limit_enabled and not isinstance(hard_limit_enabled, bool):
            raise TypeError("Expected argument 'hard_limit_enabled' to be a bool")
        pulumi.set(__self__, "hard_limit_enabled", hard_limit_enabled)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if object_count and not isinstance(object_count, int):
            raise TypeError("Expected argument 'object_count' to be a int")
        pulumi.set(__self__, "object_count", object_count)
        if quota_limit and not isinstance(quota_limit, int):
            raise TypeError("Expected argument 'quota_limit' to be a int")
        pulumi.set(__self__, "quota_limit", quota_limit)
        if space and not isinstance(space, dict):
            raise TypeError("Expected argument 'space' to be a dict")
        pulumi.set(__self__, "space", space)

    @property
    @pulumi.getter
    def created(self) -> builtins.int:
        return pulumi.get(self, "created")

    @property
    @pulumi.getter(name="hardLimitEnabled")
    def hard_limit_enabled(self) -> builtins.bool:
        return pulumi.get(self, "hard_limit_enabled")

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> builtins.str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="objectCount")
    def object_count(self) -> builtins.int:
        return pulumi.get(self, "object_count")

    @property
    @pulumi.getter(name="quotaLimit")
    def quota_limit(self) -> builtins.int:
        return pulumi.get(self, "quota_limit")

    @property
    @pulumi.getter
    def space(self) -> 'outputs.GetObjectStoreAccountSpaceResult':
        return pulumi.get(self, "space")


class AwaitableGetObjectStoreAccountResult(GetObjectStoreAccountResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetObjectStoreAccountResult(
            created=self.created,
            hard_limit_enabled=self.hard_limit_enabled,
            id=self.id,
            name=self.name,
            object_count=self.object_count,
            quota_limit=self.quota_limit,
            space=self.space)


def get_object_store_account(name: Optional[builtins.str] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetObjectStoreAccountResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mica:index/getObjectStoreAccount:getObjectStoreAccount', __args__, opts=opts, typ=GetObjectStoreAccountResult).value

    return AwaitableGetObjectStoreAccountResult(
        created=pulumi.get(__ret__, 'created'),
        hard_limit_enabled=pulumi.get(__ret__, 'hard_limit_enabled'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        object_count=pulumi.get(__ret__, 'object_count'),
        quota_limit=pulumi.get(__ret__, 'quota_limit'),
        space=pulumi.get(__ret__, 'space'))
def get_object_store_account_output(name: Optional[pulumi.Input[builtins.str]] = None,
                                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetObjectStoreAccountResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mica:index/getObjectStoreAccount:getObjectStoreAccount', __args__, opts=opts, typ=GetObjectStoreAccountResult)
    return __ret__.apply(lambda __response__: GetObjectStoreAccountResult(
        created=pulumi.get(__response__, 'created'),
        hard_limit_enabled=pulumi.get(__response__, 'hard_limit_enabled'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        object_count=pulumi.get(__response__, 'object_count'),
        quota_limit=pulumi.get(__response__, 'quota_limit'),
        space=pulumi.get(__response__, 'space')))
