# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetBucketCorsPolicyResult',
    'AwaitableGetBucketCorsPolicyResult',
    'get_bucket_cors_policy',
    'get_bucket_cors_policy_output',
]

@pulumi.output_type
class GetBucketCorsPolicyResult:
    """
    A collection of values returned by getBucketCorsPolicy.
    """
    def __init__(__self__, bucket_name=None, id=None, is_local=None, policy_type=None):
        if bucket_name and not isinstance(bucket_name, str):
            raise TypeError("Expected argument 'bucket_name' to be a str")
        pulumi.set(__self__, "bucket_name", bucket_name)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if is_local and not isinstance(is_local, bool):
            raise TypeError("Expected argument 'is_local' to be a bool")
        pulumi.set(__self__, "is_local", is_local)
        if policy_type and not isinstance(policy_type, str):
            raise TypeError("Expected argument 'policy_type' to be a str")
        pulumi.set(__self__, "policy_type", policy_type)

    @property
    @pulumi.getter(name="bucketName")
    def bucket_name(self) -> builtins.str:
        return pulumi.get(self, "bucket_name")

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="isLocal")
    def is_local(self) -> builtins.bool:
        return pulumi.get(self, "is_local")

    @property
    @pulumi.getter(name="policyType")
    def policy_type(self) -> builtins.str:
        return pulumi.get(self, "policy_type")


class AwaitableGetBucketCorsPolicyResult(GetBucketCorsPolicyResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetBucketCorsPolicyResult(
            bucket_name=self.bucket_name,
            id=self.id,
            is_local=self.is_local,
            policy_type=self.policy_type)


def get_bucket_cors_policy(bucket_name: Optional[builtins.str] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetBucketCorsPolicyResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['bucketName'] = bucket_name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mica:index/getBucketCorsPolicy:getBucketCorsPolicy', __args__, opts=opts, typ=GetBucketCorsPolicyResult).value

    return AwaitableGetBucketCorsPolicyResult(
        bucket_name=pulumi.get(__ret__, 'bucket_name'),
        id=pulumi.get(__ret__, 'id'),
        is_local=pulumi.get(__ret__, 'is_local'),
        policy_type=pulumi.get(__ret__, 'policy_type'))
def get_bucket_cors_policy_output(bucket_name: Optional[pulumi.Input[builtins.str]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetBucketCorsPolicyResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['bucketName'] = bucket_name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mica:index/getBucketCorsPolicy:getBucketCorsPolicy', __args__, opts=opts, typ=GetBucketCorsPolicyResult)
    return __ret__.apply(lambda __response__: GetBucketCorsPolicyResult(
        bucket_name=pulumi.get(__response__, 'bucket_name'),
        id=pulumi.get(__response__, 'id'),
        is_local=pulumi.get(__response__, 'is_local'),
        policy_type=pulumi.get(__response__, 'policy_type')))
