# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetObjectStoreVirtualHostResult',
    'AwaitableGetObjectStoreVirtualHostResult',
    'get_object_store_virtual_host',
    'get_object_store_virtual_host_output',
]

@pulumi.output_type
class GetObjectStoreVirtualHostResult:
    """
    A collection of values returned by getObjectStoreVirtualHost.
    """
    def __init__(__self__, attached_servers=None, filter=None, hostname=None, id=None, name=None):
        if attached_servers and not isinstance(attached_servers, list):
            raise TypeError("Expected argument 'attached_servers' to be a list")
        pulumi.set(__self__, "attached_servers", attached_servers)
        if filter and not isinstance(filter, str):
            raise TypeError("Expected argument 'filter' to be a str")
        pulumi.set(__self__, "filter", filter)
        if hostname and not isinstance(hostname, str):
            raise TypeError("Expected argument 'hostname' to be a str")
        pulumi.set(__self__, "hostname", hostname)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter(name="attachedServers")
    def attached_servers(self) -> Sequence[builtins.str]:
        return pulumi.get(self, "attached_servers")

    @property
    @pulumi.getter
    def filter(self) -> Optional[builtins.str]:
        return pulumi.get(self, "filter")

    @property
    @pulumi.getter
    def hostname(self) -> builtins.str:
        return pulumi.get(self, "hostname")

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> Optional[builtins.str]:
        return pulumi.get(self, "name")


class AwaitableGetObjectStoreVirtualHostResult(GetObjectStoreVirtualHostResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetObjectStoreVirtualHostResult(
            attached_servers=self.attached_servers,
            filter=self.filter,
            hostname=self.hostname,
            id=self.id,
            name=self.name)


def get_object_store_virtual_host(filter: Optional[builtins.str] = None,
                                  name: Optional[builtins.str] = None,
                                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetObjectStoreVirtualHostResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['filter'] = filter
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mica:index/getObjectStoreVirtualHost:getObjectStoreVirtualHost', __args__, opts=opts, typ=GetObjectStoreVirtualHostResult).value

    return AwaitableGetObjectStoreVirtualHostResult(
        attached_servers=pulumi.get(__ret__, 'attached_servers'),
        filter=pulumi.get(__ret__, 'filter'),
        hostname=pulumi.get(__ret__, 'hostname'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'))
def get_object_store_virtual_host_output(filter: Optional[pulumi.Input[Optional[builtins.str]]] = None,
                                         name: Optional[pulumi.Input[Optional[builtins.str]]] = None,
                                         opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetObjectStoreVirtualHostResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['filter'] = filter
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mica:index/getObjectStoreVirtualHost:getObjectStoreVirtualHost', __args__, opts=opts, typ=GetObjectStoreVirtualHostResult)
    return __ret__.apply(lambda __response__: GetObjectStoreVirtualHostResult(
        attached_servers=pulumi.get(__response__, 'attached_servers'),
        filter=pulumi.get(__response__, 'filter'),
        hostname=pulumi.get(__response__, 'hostname'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name')))
