# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetSyslogServerResult',
    'AwaitableGetSyslogServerResult',
    'get_syslog_server',
    'get_syslog_server_output',
]

@pulumi.output_type
class GetSyslogServerResult:
    """
    A collection of values returned by getSyslogServer.
    """
    def __init__(__self__, id=None, name=None, services=None, sources=None, uri=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if services and not isinstance(services, list):
            raise TypeError("Expected argument 'services' to be a list")
        pulumi.set(__self__, "services", services)
        if sources and not isinstance(sources, list):
            raise TypeError("Expected argument 'sources' to be a list")
        pulumi.set(__self__, "sources", sources)
        if uri and not isinstance(uri, str):
            raise TypeError("Expected argument 'uri' to be a str")
        pulumi.set(__self__, "uri", uri)

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> builtins.str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def services(self) -> Sequence[builtins.str]:
        return pulumi.get(self, "services")

    @property
    @pulumi.getter
    def sources(self) -> Sequence[builtins.str]:
        return pulumi.get(self, "sources")

    @property
    @pulumi.getter
    def uri(self) -> builtins.str:
        return pulumi.get(self, "uri")


class AwaitableGetSyslogServerResult(GetSyslogServerResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSyslogServerResult(
            id=self.id,
            name=self.name,
            services=self.services,
            sources=self.sources,
            uri=self.uri)


def get_syslog_server(name: Optional[builtins.str] = None,
                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSyslogServerResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mica:index/getSyslogServer:getSyslogServer', __args__, opts=opts, typ=GetSyslogServerResult).value

    return AwaitableGetSyslogServerResult(
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        services=pulumi.get(__ret__, 'services'),
        sources=pulumi.get(__ret__, 'sources'),
        uri=pulumi.get(__ret__, 'uri'))
def get_syslog_server_output(name: Optional[pulumi.Input[builtins.str]] = None,
                             opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetSyslogServerResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mica:index/getSyslogServer:getSyslogServer', __args__, opts=opts, typ=GetSyslogServerResult)
    return __ret__.apply(lambda __response__: GetSyslogServerResult(
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        services=pulumi.get(__response__, 'services'),
        sources=pulumi.get(__response__, 'sources'),
        uri=pulumi.get(__response__, 'uri')))
