# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetArrayConnectionResult',
    'AwaitableGetArrayConnectionResult',
    'get_array_connection',
    'get_array_connection_output',
]

@pulumi.output_type
class GetArrayConnectionResult:
    """
    A collection of values returned by getArrayConnection.
    """
    def __init__(__self__, ca_certificate_group=None, encrypted=None, id=None, management_address=None, os=None, remote_id=None, remote_name=None, replication_addresses=None, status=None, type=None, version=None):
        if ca_certificate_group and not isinstance(ca_certificate_group, str):
            raise TypeError("Expected argument 'ca_certificate_group' to be a str")
        pulumi.set(__self__, "ca_certificate_group", ca_certificate_group)
        if encrypted and not isinstance(encrypted, bool):
            raise TypeError("Expected argument 'encrypted' to be a bool")
        pulumi.set(__self__, "encrypted", encrypted)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if management_address and not isinstance(management_address, str):
            raise TypeError("Expected argument 'management_address' to be a str")
        pulumi.set(__self__, "management_address", management_address)
        if os and not isinstance(os, str):
            raise TypeError("Expected argument 'os' to be a str")
        pulumi.set(__self__, "os", os)
        if remote_id and not isinstance(remote_id, str):
            raise TypeError("Expected argument 'remote_id' to be a str")
        pulumi.set(__self__, "remote_id", remote_id)
        if remote_name and not isinstance(remote_name, str):
            raise TypeError("Expected argument 'remote_name' to be a str")
        pulumi.set(__self__, "remote_name", remote_name)
        if replication_addresses and not isinstance(replication_addresses, list):
            raise TypeError("Expected argument 'replication_addresses' to be a list")
        pulumi.set(__self__, "replication_addresses", replication_addresses)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        pulumi.set(__self__, "type", type)
        if version and not isinstance(version, str):
            raise TypeError("Expected argument 'version' to be a str")
        pulumi.set(__self__, "version", version)

    @property
    @pulumi.getter(name="caCertificateGroup")
    def ca_certificate_group(self) -> builtins.str:
        return pulumi.get(self, "ca_certificate_group")

    @property
    @pulumi.getter
    def encrypted(self) -> builtins.bool:
        return pulumi.get(self, "encrypted")

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="managementAddress")
    def management_address(self) -> builtins.str:
        return pulumi.get(self, "management_address")

    @property
    @pulumi.getter
    def os(self) -> builtins.str:
        return pulumi.get(self, "os")

    @property
    @pulumi.getter(name="remoteId")
    def remote_id(self) -> builtins.str:
        return pulumi.get(self, "remote_id")

    @property
    @pulumi.getter(name="remoteName")
    def remote_name(self) -> builtins.str:
        return pulumi.get(self, "remote_name")

    @property
    @pulumi.getter(name="replicationAddresses")
    def replication_addresses(self) -> Sequence[builtins.str]:
        return pulumi.get(self, "replication_addresses")

    @property
    @pulumi.getter
    def status(self) -> builtins.str:
        return pulumi.get(self, "status")

    @property
    @pulumi.getter
    def type(self) -> builtins.str:
        return pulumi.get(self, "type")

    @property
    @pulumi.getter
    def version(self) -> builtins.str:
        return pulumi.get(self, "version")


class AwaitableGetArrayConnectionResult(GetArrayConnectionResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetArrayConnectionResult(
            ca_certificate_group=self.ca_certificate_group,
            encrypted=self.encrypted,
            id=self.id,
            management_address=self.management_address,
            os=self.os,
            remote_id=self.remote_id,
            remote_name=self.remote_name,
            replication_addresses=self.replication_addresses,
            status=self.status,
            type=self.type,
            version=self.version)


def get_array_connection(remote_name: Optional[builtins.str] = None,
                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetArrayConnectionResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['remoteName'] = remote_name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('mica:index/getArrayConnection:getArrayConnection', __args__, opts=opts, typ=GetArrayConnectionResult).value

    return AwaitableGetArrayConnectionResult(
        ca_certificate_group=pulumi.get(__ret__, 'ca_certificate_group'),
        encrypted=pulumi.get(__ret__, 'encrypted'),
        id=pulumi.get(__ret__, 'id'),
        management_address=pulumi.get(__ret__, 'management_address'),
        os=pulumi.get(__ret__, 'os'),
        remote_id=pulumi.get(__ret__, 'remote_id'),
        remote_name=pulumi.get(__ret__, 'remote_name'),
        replication_addresses=pulumi.get(__ret__, 'replication_addresses'),
        status=pulumi.get(__ret__, 'status'),
        type=pulumi.get(__ret__, 'type'),
        version=pulumi.get(__ret__, 'version'))
def get_array_connection_output(remote_name: Optional[pulumi.Input[builtins.str]] = None,
                                opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetArrayConnectionResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['remoteName'] = remote_name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('mica:index/getArrayConnection:getArrayConnection', __args__, opts=opts, typ=GetArrayConnectionResult)
    return __ret__.apply(lambda __response__: GetArrayConnectionResult(
        ca_certificate_group=pulumi.get(__response__, 'ca_certificate_group'),
        encrypted=pulumi.get(__response__, 'encrypted'),
        id=pulumi.get(__response__, 'id'),
        management_address=pulumi.get(__response__, 'management_address'),
        os=pulumi.get(__response__, 'os'),
        remote_id=pulumi.get(__response__, 'remote_id'),
        remote_name=pulumi.get(__response__, 'remote_name'),
        replication_addresses=pulumi.get(__response__, 'replication_addresses'),
        status=pulumi.get(__response__, 'status'),
        type=pulumi.get(__response__, 'type'),
        version=pulumi.get(__response__, 'version')))
