# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ManagementAccessPolicyDirectoryServiceRoleMembershipArgs', 'ManagementAccessPolicyDirectoryServiceRoleMembership']

@pulumi.input_type
class ManagementAccessPolicyDirectoryServiceRoleMembershipArgs:
    def __init__(__self__, *,
                 policy: pulumi.Input[builtins.str],
                 role: pulumi.Input[builtins.str]):
        """
        The set of arguments for constructing a ManagementAccessPolicyDirectoryServiceRoleMembership resource.
        :param pulumi.Input[builtins.str] policy: Name of the management access policy to associate. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] role: Name of the directory service role. Changing this forces a new resource.
        """
        pulumi.set(__self__, "policy", policy)
        pulumi.set(__self__, "role", role)

    @property
    @pulumi.getter
    def policy(self) -> pulumi.Input[builtins.str]:
        """
        Name of the management access policy to associate. Changing this forces a new resource.
        """
        return pulumi.get(self, "policy")

    @policy.setter
    def policy(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "policy", value)

    @property
    @pulumi.getter
    def role(self) -> pulumi.Input[builtins.str]:
        """
        Name of the directory service role. Changing this forces a new resource.
        """
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "role", value)


@pulumi.input_type
class _ManagementAccessPolicyDirectoryServiceRoleMembershipState:
    def __init__(__self__, *,
                 policy: Optional[pulumi.Input[builtins.str]] = None,
                 role: Optional[pulumi.Input[builtins.str]] = None):
        """
        Input properties used for looking up and filtering ManagementAccessPolicyDirectoryServiceRoleMembership resources.
        :param pulumi.Input[builtins.str] policy: Name of the management access policy to associate. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] role: Name of the directory service role. Changing this forces a new resource.
        """
        if policy is not None:
            pulumi.set(__self__, "policy", policy)
        if role is not None:
            pulumi.set(__self__, "role", role)

    @property
    @pulumi.getter
    def policy(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Name of the management access policy to associate. Changing this forces a new resource.
        """
        return pulumi.get(self, "policy")

    @policy.setter
    def policy(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "policy", value)

    @property
    @pulumi.getter
    def role(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Name of the directory service role. Changing this forces a new resource.
        """
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "role", value)


class ManagementAccessPolicyDirectoryServiceRoleMembership(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 policy: Optional[pulumi.Input[builtins.str]] = None,
                 role: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        """
        Create a ManagementAccessPolicyDirectoryServiceRoleMembership resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] policy: Name of the management access policy to associate. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] role: Name of the directory service role. Changing this forces a new resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ManagementAccessPolicyDirectoryServiceRoleMembershipArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ManagementAccessPolicyDirectoryServiceRoleMembership resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ManagementAccessPolicyDirectoryServiceRoleMembershipArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ManagementAccessPolicyDirectoryServiceRoleMembershipArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 policy: Optional[pulumi.Input[builtins.str]] = None,
                 role: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ManagementAccessPolicyDirectoryServiceRoleMembershipArgs.__new__(ManagementAccessPolicyDirectoryServiceRoleMembershipArgs)

            if policy is None and not opts.urn:
                raise TypeError("Missing required property 'policy'")
            __props__.__dict__["policy"] = policy
            if role is None and not opts.urn:
                raise TypeError("Missing required property 'role'")
            __props__.__dict__["role"] = role
        super(ManagementAccessPolicyDirectoryServiceRoleMembership, __self__).__init__(
            'mica:index/managementAccessPolicyDirectoryServiceRoleMembership:ManagementAccessPolicyDirectoryServiceRoleMembership',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            policy: Optional[pulumi.Input[builtins.str]] = None,
            role: Optional[pulumi.Input[builtins.str]] = None) -> 'ManagementAccessPolicyDirectoryServiceRoleMembership':
        """
        Get an existing ManagementAccessPolicyDirectoryServiceRoleMembership resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] policy: Name of the management access policy to associate. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] role: Name of the directory service role. Changing this forces a new resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ManagementAccessPolicyDirectoryServiceRoleMembershipState.__new__(_ManagementAccessPolicyDirectoryServiceRoleMembershipState)

        __props__.__dict__["policy"] = policy
        __props__.__dict__["role"] = role
        return ManagementAccessPolicyDirectoryServiceRoleMembership(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def policy(self) -> pulumi.Output[builtins.str]:
        """
        Name of the management access policy to associate. Changing this forces a new resource.
        """
        return pulumi.get(self, "policy")

    @property
    @pulumi.getter
    def role(self) -> pulumi.Output[builtins.str]:
        """
        Name of the directory service role. Changing this forces a new resource.
        """
        return pulumi.get(self, "role")

