# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SnapshotPolicyArgs', 'SnapshotPolicy']

@pulumi.input_type
class SnapshotPolicyArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[builtins.str],
                 enabled: Optional[pulumi.Input[builtins.bool]] = None):
        """
        The set of arguments for constructing a SnapshotPolicy resource.
        :param pulumi.Input[builtins.str] name: The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
        :param pulumi.Input[builtins.bool] enabled: If true, the policy is enabled and its rules are enforced.
        """
        pulumi.set(__self__, "name", name)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[builtins.str]:
        """
        The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        If true, the policy is enabled and its rules are enforced.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "enabled", value)


@pulumi.input_type
class _SnapshotPolicyState:
    def __init__(__self__, *,
                 enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 is_local: Optional[pulumi.Input[builtins.bool]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 policy_type: Optional[pulumi.Input[builtins.str]] = None,
                 retention_lock: Optional[pulumi.Input[builtins.str]] = None):
        """
        Input properties used for looking up and filtering SnapshotPolicy resources.
        :param pulumi.Input[builtins.bool] enabled: If true, the policy is enabled and its rules are enforced.
        :param pulumi.Input[builtins.bool] is_local: If true, the policy is local to this array (not replicated).
        :param pulumi.Input[builtins.str] name: The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
        :param pulumi.Input[builtins.str] policy_type: The type of the policy (e.g. 'snapshot').
        :param pulumi.Input[builtins.str] retention_lock: The retention lock mode of the policy (e.g. 'none', 'ratcheted').
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if is_local is not None:
            pulumi.set(__self__, "is_local", is_local)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if policy_type is not None:
            pulumi.set(__self__, "policy_type", policy_type)
        if retention_lock is not None:
            pulumi.set(__self__, "retention_lock", retention_lock)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        If true, the policy is enabled and its rules are enforced.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter(name="isLocal")
    def is_local(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        If true, the policy is local to this array (not replicated).
        """
        return pulumi.get(self, "is_local")

    @is_local.setter
    def is_local(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "is_local", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="policyType")
    def policy_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The type of the policy (e.g. 'snapshot').
        """
        return pulumi.get(self, "policy_type")

    @policy_type.setter
    def policy_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "policy_type", value)

    @property
    @pulumi.getter(name="retentionLock")
    def retention_lock(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The retention lock mode of the policy (e.g. 'none', 'ratcheted').
        """
        return pulumi.get(self, "retention_lock")

    @retention_lock.setter
    def retention_lock(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "retention_lock", value)


class SnapshotPolicy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        """
        Create a SnapshotPolicy resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.bool] enabled: If true, the policy is enabled and its rules are enforced.
        :param pulumi.Input[builtins.str] name: The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SnapshotPolicyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a SnapshotPolicy resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param SnapshotPolicyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SnapshotPolicyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SnapshotPolicyArgs.__new__(SnapshotPolicyArgs)

            __props__.__dict__["enabled"] = enabled
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["is_local"] = None
            __props__.__dict__["policy_type"] = None
            __props__.__dict__["retention_lock"] = None
        super(SnapshotPolicy, __self__).__init__(
            'mica:index/snapshotPolicy:SnapshotPolicy',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            enabled: Optional[pulumi.Input[builtins.bool]] = None,
            is_local: Optional[pulumi.Input[builtins.bool]] = None,
            name: Optional[pulumi.Input[builtins.str]] = None,
            policy_type: Optional[pulumi.Input[builtins.str]] = None,
            retention_lock: Optional[pulumi.Input[builtins.str]] = None) -> 'SnapshotPolicy':
        """
        Get an existing SnapshotPolicy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.bool] enabled: If true, the policy is enabled and its rules are enforced.
        :param pulumi.Input[builtins.bool] is_local: If true, the policy is local to this array (not replicated).
        :param pulumi.Input[builtins.str] name: The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
        :param pulumi.Input[builtins.str] policy_type: The type of the policy (e.g. 'snapshot').
        :param pulumi.Input[builtins.str] retention_lock: The retention lock mode of the policy (e.g. 'none', 'ratcheted').
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SnapshotPolicyState.__new__(_SnapshotPolicyState)

        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["is_local"] = is_local
        __props__.__dict__["name"] = name
        __props__.__dict__["policy_type"] = policy_type
        __props__.__dict__["retention_lock"] = retention_lock
        return SnapshotPolicy(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[builtins.bool]:
        """
        If true, the policy is enabled and its rules are enforced.
        """
        return pulumi.get(self, "enabled")

    @property
    @pulumi.getter(name="isLocal")
    def is_local(self) -> pulumi.Output[builtins.bool]:
        """
        If true, the policy is local to this array (not replicated).
        """
        return pulumi.get(self, "is_local")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[builtins.str]:
        """
        The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="policyType")
    def policy_type(self) -> pulumi.Output[builtins.str]:
        """
        The type of the policy (e.g. 'snapshot').
        """
        return pulumi.get(self, "policy_type")

    @property
    @pulumi.getter(name="retentionLock")
    def retention_lock(self) -> pulumi.Output[builtins.str]:
        """
        The retention lock mode of the policy (e.g. 'none', 'ratcheted').
        """
        return pulumi.get(self, "retention_lock")

