#!/usr/bin/env python3
"""
upgrade_version.py — Mechanical API version-string replacement for the FlashBlade provider.

Replaces version strings across the provider codebase. Comprehensive scope is required
because tests (`*_test.go`) and model files reference the API version in URL paths and
quoted literals — a narrow scope leaves Gate 1 failing with 404s.

Target patterns:
  1. internal/client/client.go       — const APIVersion = "OLD"  (single match)
  2. internal/testmock/server.go     — last element of the versions slice  (preserves older versions)
  3. internal/**/*.go                — /api/OLD/ URL path prefixes (anywhere: handlers, tests, comments)
  4. internal/**/*.go                — "OLD" quoted version literals (test fixtures, version checks)

Out of scope (intentional):
  - docs/        — regenerated by `make docs` in Phase 5
  - examples/    — HCL files use the provider abstraction, no hardcoded API version
  - README.md, FLASHBLADE_API.md, CHANGELOG, .planning/ — manual update during Phase 5 if needed
  - Provider patch versions like v2.22.3, pulumi-2.22.3 — those follow a separate release cycle

Usage:
    python3 upgrade_version.py --from 2.22 --to 2.23 [--dry-run | --apply] [--project-root /path]
"""

import re
import sys
import argparse
from pathlib import Path
from collections import namedtuple

Change = namedtuple("Change", ["lineno", "old_line", "new_line"])
FileChange = namedtuple("FileChange", ["path", "new_content", "changes"])


def replace_client_version(content: str, old: str, new: str) -> tuple[str, list[Change]]:
    """Replace const APIVersion = "OLD" → const APIVersion = "NEW" in client.go."""
    pattern = re.compile(r'(const APIVersion = ")' + re.escape(old) + r'"')
    changes = []
    lines = content.splitlines(keepends=True)
    new_lines = []
    for i, line in enumerate(lines, start=1):
        new_line = pattern.sub(r'\g<1>' + new + '"', line)
        if new_line != line:
            changes.append(Change(lineno=i, old_line=line.rstrip("\n"), new_line=new_line.rstrip("\n")))
        new_lines.append(new_line)
    return "".join(new_lines), changes


def replace_server_versions(content: str, old: str, new: str) -> tuple[str, list[Change]]:
    """Replace "OLD" only on the line containing "versions": in server.go."""
    changes = []
    lines = content.splitlines(keepends=True)
    new_lines = []
    for i, line in enumerate(lines, start=1):
        if '"versions":' in line:
            # Only replace the last occurrence of "OLD" on this line to avoid
            # touching older version strings like "2.12" or "2.15".
            old_quoted = '"' + old + '"'
            new_quoted = '"' + new + '"'
            if old_quoted in line:
                # Replace only the last occurrence (the current/latest version)
                idx = line.rfind(old_quoted)
                new_line = line[:idx] + new_quoted + line[idx + len(old_quoted):]
                changes.append(Change(lineno=i, old_line=line.rstrip("\n"), new_line=new_line.rstrip("\n")))
                new_lines.append(new_line)
                continue
        new_lines.append(line)
    return "".join(new_lines), changes


def replace_api_url_paths(content: str, old: str, new: str) -> tuple[str, list[Change]]:
    """Replace /api/OLD/ → /api/NEW/ wherever it appears (code, comments, test fixtures)."""
    old_prefix = f"/api/{old}/"
    new_prefix = f"/api/{new}/"
    changes = []
    lines = content.splitlines(keepends=True)
    new_lines = []
    for i, line in enumerate(lines, start=1):
        if old_prefix in line:
            new_line = line.replace(old_prefix, new_prefix)
            changes.append(Change(lineno=i, old_line=line.rstrip("\n"), new_line=new_line.rstrip("\n")))
            new_lines.append(new_line)
        else:
            new_lines.append(line)
    return "".join(new_lines), changes


def replace_quoted_version(content: str, old: str, new: str) -> tuple[str, list[Change]]:
    """Replace "OLD" → "NEW" — quoted version literals in Go code (test fixtures, assertions).

    Safe because the entire `2.22` token in the project is API-version specific. Provider
    patch versions are formatted as `v2.22.3` / `pulumi-2.22.3` (suffix `.N`) which this
    pattern does NOT match (no quotes around `2.22.3` in source). Verified by grep before
    designing this rule.
    """
    old_quoted = f'"{old}"'
    new_quoted = f'"{new}"'
    changes = []
    lines = content.splitlines(keepends=True)
    new_lines = []
    for i, line in enumerate(lines, start=1):
        if old_quoted in line:
            new_line = line.replace(old_quoted, new_quoted)
            changes.append(Change(lineno=i, old_line=line.rstrip("\n"), new_line=new_line.rstrip("\n")))
            new_lines.append(new_line)
        else:
            new_lines.append(line)
    return "".join(new_lines), changes


def _merge_changes(existing: "FileChange | None", path: Path, new_content: str, changes: list[Change]) -> FileChange:
    """Merge new changes into an existing FileChange for the same path, or create a new one."""
    if existing is None:
        return FileChange(path=path, new_content=new_content, changes=list(changes))
    # Combine changes — new_content from the last pass is authoritative because each
    # pass reads the previous pass's output via the accumulator dict.
    combined = list(existing.changes) + list(changes)
    return FileChange(path=path, new_content=new_content, changes=combined)


def find_replacements(project_root: Path, old: str, new: str) -> list[FileChange]:
    """Discover all version-string replacements across the four target patterns."""
    # Accumulate by path so multiple passes on the same file merge cleanly.
    by_path: dict[Path, FileChange] = {}

    # Pattern 1 — internal/client/client.go: const APIVersion
    client_go = project_root / "internal" / "client" / "client.go"
    if not client_go.exists():
        print(f"WARNING: {client_go} not found — skipping client.go replacement", file=sys.stderr)
    else:
        content = client_go.read_text(encoding="utf-8")
        new_content, changes = replace_client_version(content, old, new)
        if changes:
            by_path[client_go] = _merge_changes(by_path.get(client_go), client_go, new_content, changes)

    # Pattern 2 — internal/testmock/server.go: versions slice (preserves older versions)
    server_go = project_root / "internal" / "testmock" / "server.go"
    if not server_go.exists():
        print(f"WARNING: {server_go} not found — skipping server.go replacement", file=sys.stderr)
    else:
        content = server_go.read_text(encoding="utf-8")
        new_content, changes = replace_server_versions(content, old, new)
        if changes:
            by_path[server_go] = _merge_changes(by_path.get(server_go), server_go, new_content, changes)

    # Pattern 3 — internal/**/*.go: /api/OLD/ URL paths (code, comments, tests)
    internal_dir = project_root / "internal"
    if not internal_dir.exists():
        print(f"WARNING: {internal_dir} not found — skipping recursive .go replacements", file=sys.stderr)
        return list(by_path.values())

    for go_file in sorted(internal_dir.rglob("*.go")):
        # If we already touched this file in pass 1 or 2, read the *staged* new content
        # so subsequent passes see prior replacements.
        if go_file in by_path:
            content = by_path[go_file].new_content
        else:
            content = go_file.read_text(encoding="utf-8")
        new_content, changes = replace_api_url_paths(content, old, new)
        if changes:
            by_path[go_file] = _merge_changes(by_path.get(go_file), go_file, new_content, changes)

    # Pattern 4 — internal/**/*.go: "OLD" quoted version literals
    for go_file in sorted(internal_dir.rglob("*.go")):
        if go_file in by_path:
            content = by_path[go_file].new_content
        else:
            content = go_file.read_text(encoding="utf-8")
        new_content, changes = replace_quoted_version(content, old, new)
        if changes:
            by_path[go_file] = _merge_changes(by_path.get(go_file), go_file, new_content, changes)

    return list(by_path.values())


def apply_replacements(file_changes: list[FileChange]) -> None:
    """Write updated content back to each file."""
    for fc in file_changes:
        fc.path.write_text(fc.new_content, encoding="utf-8")


def _format_snippet(line: str, max_len: int = 80) -> str:
    stripped = line.strip()
    if len(stripped) > max_len:
        return stripped[:max_len] + "…"
    return stripped


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Replace FlashBlade API version strings across the provider codebase."
    )
    parser.add_argument("--from", dest="from_version", required=True, metavar="VERSION",
                        help="Current API version string (e.g. 2.22)")
    parser.add_argument("--to", dest="to_version", required=True, metavar="VERSION",
                        help="Target API version string (e.g. 2.23)")
    parser.add_argument("--project-root", default=None, metavar="DIR",
                        help="Root of the provider repository (default: cwd)")

    mode_group = parser.add_mutually_exclusive_group()
    mode_group.add_argument("--dry-run", dest="dry_run", action="store_true", default=True,
                            help="Print replacements without modifying files (default)")
    mode_group.add_argument("--apply", dest="apply", action="store_true", default=False,
                            help="Apply replacements to files")

    args = parser.parse_args()

    # When --apply is given, dry_run should be False.
    dry_run = not args.apply

    project_root = Path(args.project_root) if args.project_root else Path.cwd()
    old_version = args.from_version
    new_version = args.to_version

    file_changes = find_replacements(project_root, old_version, new_version)

    if not file_changes:
        print(f"No replacements found for version {old_version}", file=sys.stderr)
        sys.exit(1)

    if dry_run:
        print(f"DRY RUN — no files modified")
        print(f"Would replace {old_version!r} → {new_version!r} in {len(file_changes)} file(s):\n")
    else:
        print(f"APPLYING — replacing {old_version!r} → {new_version!r} in {len(file_changes)} file(s):\n")

    for fc in file_changes:
        for ch in fc.changes:
            old_snippet = _format_snippet(ch.old_line)
            new_snippet = _format_snippet(ch.new_line)
            print(f"{fc.path}:{ch.lineno}: {old_snippet} → {new_snippet}")

    if not dry_run:
        apply_replacements(file_changes)
        total_files = len(file_changes)
        print(f"\nDone. {total_files} file(s) modified.")


if __name__ == "__main__":
    main()
