package client_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/numberly/opentofu-provider-flashblade/internal/client"
)

func TestUnit_ObjectStoreAccessKey_Get(t *testing.T) {
	expected := client.ObjectStoreAccessKey{
		Name:        "test-account/test-user/key-id-abc",
		AccessKeyID: "AKIAIOSFODNN7EXAMPLE",
		Enabled:     true,
		User:        client.NamedReference{Name: "test-account/test-user"},
	}

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.URL.Path == "/api/login":
			w.Header().Set("x-auth-token", "tok")
			w.WriteHeader(http.StatusOK)
		case r.Method == http.MethodGet && r.URL.Path == "/api/2.22/object-store-access-keys":
			name := r.URL.Query().Get("names")
			if name != "test-account/test-user/key-id-abc" {
				writeJSON(w, http.StatusOK, listResponse([]client.ObjectStoreAccessKey{}))
				return
			}
			writeJSON(w, http.StatusOK, listResponse([]client.ObjectStoreAccessKey{expected}))
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()

	c := newTestClient(t, srv)
	got, err := c.GetObjectStoreAccessKey(context.Background(), "test-account/test-user/key-id-abc")
	if err != nil {
		t.Fatalf("GetObjectStoreAccessKey: %v", err)
	}
	if got.AccessKeyID != expected.AccessKeyID {
		t.Errorf("expected AccessKeyID %q, got %q", expected.AccessKeyID, got.AccessKeyID)
	}
	if !got.Enabled {
		t.Errorf("expected Enabled true")
	}
}

func TestUnit_ObjectStoreAccessKey_Get_NotFound(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.URL.Path == "/api/login":
			w.Header().Set("x-auth-token", "tok")
			w.WriteHeader(http.StatusOK)
		case r.Method == http.MethodGet && r.URL.Path == "/api/2.22/object-store-access-keys":
			writeJSON(w, http.StatusOK, listResponse([]client.ObjectStoreAccessKey{}))
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()

	c := newTestClient(t, srv)
	_, err := c.GetObjectStoreAccessKey(context.Background(), "nonexistent")
	if err == nil {
		t.Fatal("expected error for not found, got nil")
	}
	if !client.IsNotFound(err) {
		t.Errorf("expected IsNotFound true, got false; err: %v", err)
	}
}

func TestUnit_ObjectStoreAccessKey_Post_AutoGenerated(t *testing.T) {
	// POST without names= — API auto-generates key name and secret.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.URL.Path == "/api/login":
			w.Header().Set("x-auth-token", "tok")
			w.WriteHeader(http.StatusOK)
		case r.Method == http.MethodPost && r.URL.Path == "/api/2.22/object-store-access-keys":
			// names param should be absent when auto-generating
			name := r.URL.Query().Get("names")
			if name != "" {
				http.Error(w, "unexpected names param for auto-generated key", http.StatusBadRequest)
				return
			}
			var body client.ObjectStoreAccessKeyPost
			if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
				http.Error(w, "bad body", http.StatusBadRequest)
				return
			}
			key := client.ObjectStoreAccessKey{
				Name:            "test-account/test-user/generated-key-id",
				AccessKeyID:     "AKIAIOSFODNN7GENERATED",
				SecretAccessKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
				Enabled:         true,
				User:            body.User,
			}
			writeJSON(w, http.StatusOK, listResponse([]client.ObjectStoreAccessKey{key}))
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()

	c := newTestClient(t, srv)
	got, err := c.PostObjectStoreAccessKey(context.Background(), "", client.ObjectStoreAccessKeyPost{
		User: client.NamedReference{Name: "test-account/test-user"},
	})
	if err != nil {
		t.Fatalf("PostObjectStoreAccessKey: %v", err)
	}
	if got.AccessKeyID != "AKIAIOSFODNN7GENERATED" {
		t.Errorf("expected AccessKeyID AKIAIOSFODNN7GENERATED, got %q", got.AccessKeyID)
	}
	// Secret must be returned on POST
	if got.SecretAccessKey != "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" {
		t.Errorf("expected SecretAccessKey to be returned, got empty")
	}
	if got.User.Name != "test-account/test-user" {
		t.Errorf("expected User.Name test-account/test-user, got %q", got.User.Name)
	}
}

func TestUnit_ObjectStoreAccessKey_Post_WithName(t *testing.T) {
	// POST with explicit names= — user-provided key name (used when importing a key).
	keyFullName := "test-account/test-user/my-key-id"

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.URL.Path == "/api/login":
			w.Header().Set("x-auth-token", "tok")
			w.WriteHeader(http.StatusOK)
		case r.Method == http.MethodPost && r.URL.Path == "/api/2.22/object-store-access-keys":
			name := r.URL.Query().Get("names")
			if name != keyFullName {
				http.Error(w, "expected names param", http.StatusBadRequest)
				return
			}
			key := client.ObjectStoreAccessKey{
				Name:            name,
				AccessKeyID:     "AKIAIOSFODNN7EXAMPLE",
				SecretAccessKey: "PROVIDED-SECRET",
				Enabled:         true,
			}
			writeJSON(w, http.StatusOK, listResponse([]client.ObjectStoreAccessKey{key}))
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()

	c := newTestClient(t, srv)
	got, err := c.PostObjectStoreAccessKey(context.Background(), keyFullName, client.ObjectStoreAccessKeyPost{
		User:            client.NamedReference{Name: "test-account/test-user"},
		SecretAccessKey: "PROVIDED-SECRET",
	})
	if err != nil {
		t.Fatalf("PostObjectStoreAccessKey with name: %v", err)
	}
	if got.Name != keyFullName {
		t.Errorf("expected Name %q, got %q", keyFullName, got.Name)
	}
}

func TestUnit_ObjectStoreAccessKey_Delete(t *testing.T) {
	var deleteCalled bool

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.URL.Path == "/api/login":
			w.Header().Set("x-auth-token", "tok")
			w.WriteHeader(http.StatusOK)
		case r.Method == http.MethodDelete && r.URL.Path == "/api/2.22/object-store-access-keys":
			name := r.URL.Query().Get("names")
			if name != "test-account/test-user/delete-key-id" {
				http.Error(w, "unexpected names param", http.StatusBadRequest)
				return
			}
			deleteCalled = true
			w.WriteHeader(http.StatusOK)
		default:
			http.NotFound(w, r)
		}
	}))
	defer srv.Close()

	c := newTestClient(t, srv)
	if err := c.DeleteObjectStoreAccessKey(context.Background(), "test-account/test-user/delete-key-id"); err != nil {
		t.Fatalf("DeleteObjectStoreAccessKey: %v", err)
	}
	if !deleteCalled {
		t.Error("expected DELETE to be called")
	}
}
