# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

auth: Optional[str]
"""
Authentication configuration for the FlashBlade array.
"""

caCert: Optional[str]
"""
Inline PEM-encoded CA certificate string used for TLS verification.
"""

caCertFile: Optional[str]
"""
Path to a PEM-encoded CA certificate file used for TLS verification.
"""

endpoint: Optional[str]
"""
FlashBlade management endpoint URL (e.g. https://flashblade.example.com). Falls back to FLASHBLADE_HOST environment variable.
"""

insecureSkipVerify: Optional[bool]
"""
Disable TLS certificate verification. For testing and development only.
"""

maxRetries: Optional[int]
"""
Maximum number of retry attempts for transient errors (429, 5xx). Default: 3.
"""

