# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'ArrayConnectionThrottleArgs',
    'ArrayConnectionThrottleArgsDict',
    'ArraySmtpAlertWatcherArgs',
    'ArraySmtpAlertWatcherArgsDict',
    'BucketEradicationConfigArgs',
    'BucketEradicationConfigArgsDict',
    'BucketObjectLockConfigArgs',
    'BucketObjectLockConfigArgsDict',
    'BucketPublicAccessConfigArgs',
    'BucketPublicAccessConfigArgsDict',
    'BucketSpaceArgs',
    'BucketSpaceArgsDict',
    'DirectoryServiceRoleRoleArgs',
    'DirectoryServiceRoleRoleArgsDict',
    'FileSystemDefaultQuotasArgs',
    'FileSystemDefaultQuotasArgsDict',
    'FileSystemHttpArgs',
    'FileSystemHttpArgsDict',
    'FileSystemMultiProtocolArgs',
    'FileSystemMultiProtocolArgsDict',
    'FileSystemNfsArgs',
    'FileSystemNfsArgsDict',
    'FileSystemSmbArgs',
    'FileSystemSmbArgsDict',
    'FileSystemSourceArgs',
    'FileSystemSourceArgsDict',
    'FileSystemSpaceArgs',
    'FileSystemSpaceArgsDict',
    'ObjectStoreAccountSpaceArgs',
    'ObjectStoreAccountSpaceArgsDict',
    'ProviderAuthArgs',
    'ProviderAuthArgsDict',
    'ProviderAuthOauth2Args',
    'ProviderAuthOauth2ArgsDict',
]

MYPY = False

if not MYPY:
    class ArrayConnectionThrottleArgsDict(TypedDict):
        default_limit: NotRequired[pulumi.Input[builtins.int]]
        """
        Default bandwidth limit in bytes per second.
        """
        window_end: NotRequired[pulumi.Input[builtins.str]]
        """
        End time of the throttle window (HH:MM format).
        """
        window_limit: NotRequired[pulumi.Input[builtins.int]]
        """
        Window bandwidth limit in bytes per second.
        """
        window_start: NotRequired[pulumi.Input[builtins.str]]
        """
        Start time of the throttle window (HH:MM format).
        """
elif False:
    ArrayConnectionThrottleArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class ArrayConnectionThrottleArgs:
    def __init__(__self__, *,
                 default_limit: Optional[pulumi.Input[builtins.int]] = None,
                 window_end: Optional[pulumi.Input[builtins.str]] = None,
                 window_limit: Optional[pulumi.Input[builtins.int]] = None,
                 window_start: Optional[pulumi.Input[builtins.str]] = None):
        """
        :param pulumi.Input[builtins.int] default_limit: Default bandwidth limit in bytes per second.
        :param pulumi.Input[builtins.str] window_end: End time of the throttle window (HH:MM format).
        :param pulumi.Input[builtins.int] window_limit: Window bandwidth limit in bytes per second.
        :param pulumi.Input[builtins.str] window_start: Start time of the throttle window (HH:MM format).
        """
        if default_limit is not None:
            pulumi.set(__self__, "default_limit", default_limit)
        if window_end is not None:
            pulumi.set(__self__, "window_end", window_end)
        if window_limit is not None:
            pulumi.set(__self__, "window_limit", window_limit)
        if window_start is not None:
            pulumi.set(__self__, "window_start", window_start)

    @property
    @pulumi.getter(name="defaultLimit")
    def default_limit(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Default bandwidth limit in bytes per second.
        """
        return pulumi.get(self, "default_limit")

    @default_limit.setter
    def default_limit(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "default_limit", value)

    @property
    @pulumi.getter(name="windowEnd")
    def window_end(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        End time of the throttle window (HH:MM format).
        """
        return pulumi.get(self, "window_end")

    @window_end.setter
    def window_end(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "window_end", value)

    @property
    @pulumi.getter(name="windowLimit")
    def window_limit(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Window bandwidth limit in bytes per second.
        """
        return pulumi.get(self, "window_limit")

    @window_limit.setter
    def window_limit(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "window_limit", value)

    @property
    @pulumi.getter(name="windowStart")
    def window_start(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Start time of the throttle window (HH:MM format).
        """
        return pulumi.get(self, "window_start")

    @window_start.setter
    def window_start(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "window_start", value)


if not MYPY:
    class ArraySmtpAlertWatcherArgsDict(TypedDict):
        email: pulumi.Input[builtins.str]
        """
        Email address of the alert recipient. This is the unique identifier for the watcher.
        """
        enabled: NotRequired[pulumi.Input[builtins.bool]]
        """
        If true, this watcher receives alert notifications.
        """
        minimum_notification_severity: NotRequired[pulumi.Input[builtins.str]]
        """
        Minimum alert severity that triggers a notification: 'info', 'warning', 'error', or 'critical'.
        """
elif False:
    ArraySmtpAlertWatcherArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class ArraySmtpAlertWatcherArgs:
    def __init__(__self__, *,
                 email: pulumi.Input[builtins.str],
                 enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 minimum_notification_severity: Optional[pulumi.Input[builtins.str]] = None):
        """
        :param pulumi.Input[builtins.str] email: Email address of the alert recipient. This is the unique identifier for the watcher.
        :param pulumi.Input[builtins.bool] enabled: If true, this watcher receives alert notifications.
        :param pulumi.Input[builtins.str] minimum_notification_severity: Minimum alert severity that triggers a notification: 'info', 'warning', 'error', or 'critical'.
        """
        pulumi.set(__self__, "email", email)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if minimum_notification_severity is not None:
            pulumi.set(__self__, "minimum_notification_severity", minimum_notification_severity)

    @property
    @pulumi.getter
    def email(self) -> pulumi.Input[builtins.str]:
        """
        Email address of the alert recipient. This is the unique identifier for the watcher.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "email", value)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        If true, this watcher receives alert notifications.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter(name="minimumNotificationSeverity")
    def minimum_notification_severity(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Minimum alert severity that triggers a notification: 'info', 'warning', 'error', or 'critical'.
        """
        return pulumi.get(self, "minimum_notification_severity")

    @minimum_notification_severity.setter
    def minimum_notification_severity(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "minimum_notification_severity", value)


if not MYPY:
    class BucketEradicationConfigArgsDict(TypedDict):
        eradication_delay: NotRequired[pulumi.Input[builtins.int]]
        """
        Eradication delay in milliseconds.
        """
        eradication_mode: NotRequired[pulumi.Input[builtins.str]]
        """
        Eradication mode (e.g. 'retention-based', 'permission-based').
        """
        manual_eradication: NotRequired[pulumi.Input[builtins.str]]
        """
        Manual eradication setting ('enabled' or 'disabled').
        """
elif False:
    BucketEradicationConfigArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class BucketEradicationConfigArgs:
    def __init__(__self__, *,
                 eradication_delay: Optional[pulumi.Input[builtins.int]] = None,
                 eradication_mode: Optional[pulumi.Input[builtins.str]] = None,
                 manual_eradication: Optional[pulumi.Input[builtins.str]] = None):
        """
        :param pulumi.Input[builtins.int] eradication_delay: Eradication delay in milliseconds.
        :param pulumi.Input[builtins.str] eradication_mode: Eradication mode (e.g. 'retention-based', 'permission-based').
        :param pulumi.Input[builtins.str] manual_eradication: Manual eradication setting ('enabled' or 'disabled').
        """
        if eradication_delay is not None:
            pulumi.set(__self__, "eradication_delay", eradication_delay)
        if eradication_mode is not None:
            pulumi.set(__self__, "eradication_mode", eradication_mode)
        if manual_eradication is not None:
            pulumi.set(__self__, "manual_eradication", manual_eradication)

    @property
    @pulumi.getter(name="eradicationDelay")
    def eradication_delay(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Eradication delay in milliseconds.
        """
        return pulumi.get(self, "eradication_delay")

    @eradication_delay.setter
    def eradication_delay(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "eradication_delay", value)

    @property
    @pulumi.getter(name="eradicationMode")
    def eradication_mode(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Eradication mode (e.g. 'retention-based', 'permission-based').
        """
        return pulumi.get(self, "eradication_mode")

    @eradication_mode.setter
    def eradication_mode(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "eradication_mode", value)

    @property
    @pulumi.getter(name="manualEradication")
    def manual_eradication(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Manual eradication setting ('enabled' or 'disabled').
        """
        return pulumi.get(self, "manual_eradication")

    @manual_eradication.setter
    def manual_eradication(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "manual_eradication", value)


if not MYPY:
    class BucketObjectLockConfigArgsDict(TypedDict):
        default_retention: NotRequired[pulumi.Input[builtins.int]]
        """
        Default retention period in seconds.
        """
        default_retention_mode: NotRequired[pulumi.Input[builtins.str]]
        """
        Default retention mode ('compliance' or 'governance').
        """
        freeze_locked_objects: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether to freeze locked objects.
        """
        object_lock_enabled: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether object lock is enabled.
        """
elif False:
    BucketObjectLockConfigArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class BucketObjectLockConfigArgs:
    def __init__(__self__, *,
                 default_retention: Optional[pulumi.Input[builtins.int]] = None,
                 default_retention_mode: Optional[pulumi.Input[builtins.str]] = None,
                 freeze_locked_objects: Optional[pulumi.Input[builtins.bool]] = None,
                 object_lock_enabled: Optional[pulumi.Input[builtins.bool]] = None):
        """
        :param pulumi.Input[builtins.int] default_retention: Default retention period in seconds.
        :param pulumi.Input[builtins.str] default_retention_mode: Default retention mode ('compliance' or 'governance').
        :param pulumi.Input[builtins.bool] freeze_locked_objects: Whether to freeze locked objects.
        :param pulumi.Input[builtins.bool] object_lock_enabled: Whether object lock is enabled.
        """
        if default_retention is not None:
            pulumi.set(__self__, "default_retention", default_retention)
        if default_retention_mode is not None:
            pulumi.set(__self__, "default_retention_mode", default_retention_mode)
        if freeze_locked_objects is not None:
            pulumi.set(__self__, "freeze_locked_objects", freeze_locked_objects)
        if object_lock_enabled is not None:
            pulumi.set(__self__, "object_lock_enabled", object_lock_enabled)

    @property
    @pulumi.getter(name="defaultRetention")
    def default_retention(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Default retention period in seconds.
        """
        return pulumi.get(self, "default_retention")

    @default_retention.setter
    def default_retention(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "default_retention", value)

    @property
    @pulumi.getter(name="defaultRetentionMode")
    def default_retention_mode(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Default retention mode ('compliance' or 'governance').
        """
        return pulumi.get(self, "default_retention_mode")

    @default_retention_mode.setter
    def default_retention_mode(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "default_retention_mode", value)

    @property
    @pulumi.getter(name="freezeLockedObjects")
    def freeze_locked_objects(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether to freeze locked objects.
        """
        return pulumi.get(self, "freeze_locked_objects")

    @freeze_locked_objects.setter
    def freeze_locked_objects(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "freeze_locked_objects", value)

    @property
    @pulumi.getter(name="objectLockEnabled")
    def object_lock_enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether object lock is enabled.
        """
        return pulumi.get(self, "object_lock_enabled")

    @object_lock_enabled.setter
    def object_lock_enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "object_lock_enabled", value)


if not MYPY:
    class BucketPublicAccessConfigArgsDict(TypedDict):
        block_new_public_policies: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether to block new public policies.
        """
        block_public_access: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether to block public access.
        """
elif False:
    BucketPublicAccessConfigArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class BucketPublicAccessConfigArgs:
    def __init__(__self__, *,
                 block_new_public_policies: Optional[pulumi.Input[builtins.bool]] = None,
                 block_public_access: Optional[pulumi.Input[builtins.bool]] = None):
        """
        :param pulumi.Input[builtins.bool] block_new_public_policies: Whether to block new public policies.
        :param pulumi.Input[builtins.bool] block_public_access: Whether to block public access.
        """
        if block_new_public_policies is not None:
            pulumi.set(__self__, "block_new_public_policies", block_new_public_policies)
        if block_public_access is not None:
            pulumi.set(__self__, "block_public_access", block_public_access)

    @property
    @pulumi.getter(name="blockNewPublicPolicies")
    def block_new_public_policies(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether to block new public policies.
        """
        return pulumi.get(self, "block_new_public_policies")

    @block_new_public_policies.setter
    def block_new_public_policies(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "block_new_public_policies", value)

    @property
    @pulumi.getter(name="blockPublicAccess")
    def block_public_access(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether to block public access.
        """
        return pulumi.get(self, "block_public_access")

    @block_public_access.setter
    def block_public_access(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "block_public_access", value)


if not MYPY:
    class BucketSpaceArgsDict(TypedDict):
        data_reduction: NotRequired[pulumi.Input[builtins.float]]
        """
        Data reduction ratio.
        """
        snapshots: NotRequired[pulumi.Input[builtins.int]]
        """
        Physical space used by snapshots in bytes.
        """
        snapshots_effective: NotRequired[pulumi.Input[builtins.int]]
        """
        Effective snapshot space used in bytes.
        """
        total_physical: NotRequired[pulumi.Input[builtins.int]]
        """
        Total physical space used in bytes.
        """
        unique: NotRequired[pulumi.Input[builtins.int]]
        """
        Unique physical space used in bytes.
        """
        virtual: NotRequired[pulumi.Input[builtins.int]]
        """
        Virtual (logical) space used in bytes.
        """
elif False:
    BucketSpaceArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class BucketSpaceArgs:
    def __init__(__self__, *,
                 data_reduction: Optional[pulumi.Input[builtins.float]] = None,
                 snapshots: Optional[pulumi.Input[builtins.int]] = None,
                 snapshots_effective: Optional[pulumi.Input[builtins.int]] = None,
                 total_physical: Optional[pulumi.Input[builtins.int]] = None,
                 unique: Optional[pulumi.Input[builtins.int]] = None,
                 virtual: Optional[pulumi.Input[builtins.int]] = None):
        """
        :param pulumi.Input[builtins.float] data_reduction: Data reduction ratio.
        :param pulumi.Input[builtins.int] snapshots: Physical space used by snapshots in bytes.
        :param pulumi.Input[builtins.int] snapshots_effective: Effective snapshot space used in bytes.
        :param pulumi.Input[builtins.int] total_physical: Total physical space used in bytes.
        :param pulumi.Input[builtins.int] unique: Unique physical space used in bytes.
        :param pulumi.Input[builtins.int] virtual: Virtual (logical) space used in bytes.
        """
        if data_reduction is not None:
            pulumi.set(__self__, "data_reduction", data_reduction)
        if snapshots is not None:
            pulumi.set(__self__, "snapshots", snapshots)
        if snapshots_effective is not None:
            pulumi.set(__self__, "snapshots_effective", snapshots_effective)
        if total_physical is not None:
            pulumi.set(__self__, "total_physical", total_physical)
        if unique is not None:
            pulumi.set(__self__, "unique", unique)
        if virtual is not None:
            pulumi.set(__self__, "virtual", virtual)

    @property
    @pulumi.getter(name="dataReduction")
    def data_reduction(self) -> Optional[pulumi.Input[builtins.float]]:
        """
        Data reduction ratio.
        """
        return pulumi.get(self, "data_reduction")

    @data_reduction.setter
    def data_reduction(self, value: Optional[pulumi.Input[builtins.float]]):
        pulumi.set(self, "data_reduction", value)

    @property
    @pulumi.getter
    def snapshots(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Physical space used by snapshots in bytes.
        """
        return pulumi.get(self, "snapshots")

    @snapshots.setter
    def snapshots(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "snapshots", value)

    @property
    @pulumi.getter(name="snapshotsEffective")
    def snapshots_effective(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Effective snapshot space used in bytes.
        """
        return pulumi.get(self, "snapshots_effective")

    @snapshots_effective.setter
    def snapshots_effective(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "snapshots_effective", value)

    @property
    @pulumi.getter(name="totalPhysical")
    def total_physical(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Total physical space used in bytes.
        """
        return pulumi.get(self, "total_physical")

    @total_physical.setter
    def total_physical(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "total_physical", value)

    @property
    @pulumi.getter
    def unique(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Unique physical space used in bytes.
        """
        return pulumi.get(self, "unique")

    @unique.setter
    def unique(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "unique", value)

    @property
    @pulumi.getter
    def virtual(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Virtual (logical) space used in bytes.
        """
        return pulumi.get(self, "virtual")

    @virtual.setter
    def virtual(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "virtual", value)


if not MYPY:
    class DirectoryServiceRoleRoleArgsDict(TypedDict):
        name: NotRequired[pulumi.Input[builtins.str]]
elif False:
    DirectoryServiceRoleRoleArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class DirectoryServiceRoleRoleArgs:
    def __init__(__self__, *,
                 name: Optional[pulumi.Input[builtins.str]] = None):
        if name is not None:
            pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[builtins.str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "name", value)


if not MYPY:
    class FileSystemDefaultQuotasArgsDict(TypedDict):
        group_quota: NotRequired[pulumi.Input[builtins.int]]
        """
        Default quota per group in bytes.
        """
        user_quota: NotRequired[pulumi.Input[builtins.int]]
        """
        Default quota per user in bytes.
        """
elif False:
    FileSystemDefaultQuotasArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class FileSystemDefaultQuotasArgs:
    def __init__(__self__, *,
                 group_quota: Optional[pulumi.Input[builtins.int]] = None,
                 user_quota: Optional[pulumi.Input[builtins.int]] = None):
        """
        :param pulumi.Input[builtins.int] group_quota: Default quota per group in bytes.
        :param pulumi.Input[builtins.int] user_quota: Default quota per user in bytes.
        """
        if group_quota is not None:
            pulumi.set(__self__, "group_quota", group_quota)
        if user_quota is not None:
            pulumi.set(__self__, "user_quota", user_quota)

    @property
    @pulumi.getter(name="groupQuota")
    def group_quota(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Default quota per group in bytes.
        """
        return pulumi.get(self, "group_quota")

    @group_quota.setter
    def group_quota(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "group_quota", value)

    @property
    @pulumi.getter(name="userQuota")
    def user_quota(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Default quota per user in bytes.
        """
        return pulumi.get(self, "user_quota")

    @user_quota.setter
    def user_quota(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "user_quota", value)


if not MYPY:
    class FileSystemHttpArgsDict(TypedDict):
        enabled: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether HTTP is enabled on this file system.
        """
elif False:
    FileSystemHttpArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class FileSystemHttpArgs:
    def __init__(__self__, *,
                 enabled: Optional[pulumi.Input[builtins.bool]] = None):
        """
        :param pulumi.Input[builtins.bool] enabled: Whether HTTP is enabled on this file system.
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether HTTP is enabled on this file system.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "enabled", value)


if not MYPY:
    class FileSystemMultiProtocolArgsDict(TypedDict):
        access_control_style: NotRequired[pulumi.Input[builtins.str]]
        """
        Access control style for multi-protocol access ('nfs' or 'smb').
        """
        safeguard_acls: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether to safeguard ACLs during multi-protocol access.
        """
elif False:
    FileSystemMultiProtocolArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class FileSystemMultiProtocolArgs:
    def __init__(__self__, *,
                 access_control_style: Optional[pulumi.Input[builtins.str]] = None,
                 safeguard_acls: Optional[pulumi.Input[builtins.bool]] = None):
        """
        :param pulumi.Input[builtins.str] access_control_style: Access control style for multi-protocol access ('nfs' or 'smb').
        :param pulumi.Input[builtins.bool] safeguard_acls: Whether to safeguard ACLs during multi-protocol access.
        """
        if access_control_style is not None:
            pulumi.set(__self__, "access_control_style", access_control_style)
        if safeguard_acls is not None:
            pulumi.set(__self__, "safeguard_acls", safeguard_acls)

    @property
    @pulumi.getter(name="accessControlStyle")
    def access_control_style(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Access control style for multi-protocol access ('nfs' or 'smb').
        """
        return pulumi.get(self, "access_control_style")

    @access_control_style.setter
    def access_control_style(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "access_control_style", value)

    @property
    @pulumi.getter(name="safeguardAcls")
    def safeguard_acls(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether to safeguard ACLs during multi-protocol access.
        """
        return pulumi.get(self, "safeguard_acls")

    @safeguard_acls.setter
    def safeguard_acls(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "safeguard_acls", value)


if not MYPY:
    class FileSystemNfsArgsDict(TypedDict):
        enabled: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether NFS is enabled on this file system.
        """
        rules: NotRequired[pulumi.Input[builtins.str]]
        """
        NFS export rules string (e.g. '*(rw,no_root_squash)').
        """
        transport: NotRequired[pulumi.Input[builtins.str]]
        """
        NFS transport protocol ('tcp' or 'udp').
        """
        v3_enabled: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether NFSv3 is enabled.
        """
        v41_enabled: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether NFSv4.1 is enabled.
        """
elif False:
    FileSystemNfsArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class FileSystemNfsArgs:
    def __init__(__self__, *,
                 enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 rules: Optional[pulumi.Input[builtins.str]] = None,
                 transport: Optional[pulumi.Input[builtins.str]] = None,
                 v3_enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 v41_enabled: Optional[pulumi.Input[builtins.bool]] = None):
        """
        :param pulumi.Input[builtins.bool] enabled: Whether NFS is enabled on this file system.
        :param pulumi.Input[builtins.str] rules: NFS export rules string (e.g. '*(rw,no_root_squash)').
        :param pulumi.Input[builtins.str] transport: NFS transport protocol ('tcp' or 'udp').
        :param pulumi.Input[builtins.bool] v3_enabled: Whether NFSv3 is enabled.
        :param pulumi.Input[builtins.bool] v41_enabled: Whether NFSv4.1 is enabled.
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if rules is not None:
            pulumi.set(__self__, "rules", rules)
        if transport is not None:
            pulumi.set(__self__, "transport", transport)
        if v3_enabled is not None:
            pulumi.set(__self__, "v3_enabled", v3_enabled)
        if v41_enabled is not None:
            pulumi.set(__self__, "v41_enabled", v41_enabled)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether NFS is enabled on this file system.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter
    def rules(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        NFS export rules string (e.g. '*(rw,no_root_squash)').
        """
        return pulumi.get(self, "rules")

    @rules.setter
    def rules(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "rules", value)

    @property
    @pulumi.getter
    def transport(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        NFS transport protocol ('tcp' or 'udp').
        """
        return pulumi.get(self, "transport")

    @transport.setter
    def transport(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "transport", value)

    @property
    @pulumi.getter(name="v3Enabled")
    def v3_enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether NFSv3 is enabled.
        """
        return pulumi.get(self, "v3_enabled")

    @v3_enabled.setter
    def v3_enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "v3_enabled", value)

    @property
    @pulumi.getter(name="v41Enabled")
    def v41_enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether NFSv4.1 is enabled.
        """
        return pulumi.get(self, "v41_enabled")

    @v41_enabled.setter
    def v41_enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "v41_enabled", value)


if not MYPY:
    class FileSystemSmbArgsDict(TypedDict):
        access_based_enumeration_enabled: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether access-based enumeration is enabled for SMB.
        """
        continuous_availability_enabled: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether continuous availability is enabled for SMB.
        """
        enabled: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether SMB is enabled on this file system.
        """
        smb_encryption_enabled: NotRequired[pulumi.Input[builtins.bool]]
        """
        Whether SMB encryption is enabled.
        """
elif False:
    FileSystemSmbArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class FileSystemSmbArgs:
    def __init__(__self__, *,
                 access_based_enumeration_enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 continuous_availability_enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 smb_encryption_enabled: Optional[pulumi.Input[builtins.bool]] = None):
        """
        :param pulumi.Input[builtins.bool] access_based_enumeration_enabled: Whether access-based enumeration is enabled for SMB.
        :param pulumi.Input[builtins.bool] continuous_availability_enabled: Whether continuous availability is enabled for SMB.
        :param pulumi.Input[builtins.bool] enabled: Whether SMB is enabled on this file system.
        :param pulumi.Input[builtins.bool] smb_encryption_enabled: Whether SMB encryption is enabled.
        """
        if access_based_enumeration_enabled is not None:
            pulumi.set(__self__, "access_based_enumeration_enabled", access_based_enumeration_enabled)
        if continuous_availability_enabled is not None:
            pulumi.set(__self__, "continuous_availability_enabled", continuous_availability_enabled)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if smb_encryption_enabled is not None:
            pulumi.set(__self__, "smb_encryption_enabled", smb_encryption_enabled)

    @property
    @pulumi.getter(name="accessBasedEnumerationEnabled")
    def access_based_enumeration_enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether access-based enumeration is enabled for SMB.
        """
        return pulumi.get(self, "access_based_enumeration_enabled")

    @access_based_enumeration_enabled.setter
    def access_based_enumeration_enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "access_based_enumeration_enabled", value)

    @property
    @pulumi.getter(name="continuousAvailabilityEnabled")
    def continuous_availability_enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether continuous availability is enabled for SMB.
        """
        return pulumi.get(self, "continuous_availability_enabled")

    @continuous_availability_enabled.setter
    def continuous_availability_enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "continuous_availability_enabled", value)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether SMB is enabled on this file system.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter(name="smbEncryptionEnabled")
    def smb_encryption_enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether SMB encryption is enabled.
        """
        return pulumi.get(self, "smb_encryption_enabled")

    @smb_encryption_enabled.setter
    def smb_encryption_enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "smb_encryption_enabled", value)


if not MYPY:
    class FileSystemSourceArgsDict(TypedDict):
        id: NotRequired[pulumi.Input[builtins.str]]
        """
        Source file system ID.
        """
        name: NotRequired[pulumi.Input[builtins.str]]
        """
        Source file system name.
        """
elif False:
    FileSystemSourceArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class FileSystemSourceArgs:
    def __init__(__self__, *,
                 id: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None):
        """
        :param pulumi.Input[builtins.str] id: Source file system ID.
        :param pulumi.Input[builtins.str] name: Source file system name.
        """
        if id is not None:
            pulumi.set(__self__, "id", id)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter
    def id(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Source file system ID.
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "id", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Source file system name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "name", value)


if not MYPY:
    class FileSystemSpaceArgsDict(TypedDict):
        data_reduction: NotRequired[pulumi.Input[builtins.float]]
        """
        Data reduction ratio.
        """
        snapshots: NotRequired[pulumi.Input[builtins.int]]
        """
        Physical space used by snapshots in bytes.
        """
        snapshots_effective: NotRequired[pulumi.Input[builtins.int]]
        """
        Effective snapshot space used in bytes.
        """
        total_physical: NotRequired[pulumi.Input[builtins.int]]
        """
        Total physical space used in bytes.
        """
        unique: NotRequired[pulumi.Input[builtins.int]]
        """
        Unique physical space used in bytes.
        """
        virtual: NotRequired[pulumi.Input[builtins.int]]
        """
        Virtual (logical) space used in bytes.
        """
elif False:
    FileSystemSpaceArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class FileSystemSpaceArgs:
    def __init__(__self__, *,
                 data_reduction: Optional[pulumi.Input[builtins.float]] = None,
                 snapshots: Optional[pulumi.Input[builtins.int]] = None,
                 snapshots_effective: Optional[pulumi.Input[builtins.int]] = None,
                 total_physical: Optional[pulumi.Input[builtins.int]] = None,
                 unique: Optional[pulumi.Input[builtins.int]] = None,
                 virtual: Optional[pulumi.Input[builtins.int]] = None):
        """
        :param pulumi.Input[builtins.float] data_reduction: Data reduction ratio.
        :param pulumi.Input[builtins.int] snapshots: Physical space used by snapshots in bytes.
        :param pulumi.Input[builtins.int] snapshots_effective: Effective snapshot space used in bytes.
        :param pulumi.Input[builtins.int] total_physical: Total physical space used in bytes.
        :param pulumi.Input[builtins.int] unique: Unique physical space used in bytes.
        :param pulumi.Input[builtins.int] virtual: Virtual (logical) space used in bytes.
        """
        if data_reduction is not None:
            pulumi.set(__self__, "data_reduction", data_reduction)
        if snapshots is not None:
            pulumi.set(__self__, "snapshots", snapshots)
        if snapshots_effective is not None:
            pulumi.set(__self__, "snapshots_effective", snapshots_effective)
        if total_physical is not None:
            pulumi.set(__self__, "total_physical", total_physical)
        if unique is not None:
            pulumi.set(__self__, "unique", unique)
        if virtual is not None:
            pulumi.set(__self__, "virtual", virtual)

    @property
    @pulumi.getter(name="dataReduction")
    def data_reduction(self) -> Optional[pulumi.Input[builtins.float]]:
        """
        Data reduction ratio.
        """
        return pulumi.get(self, "data_reduction")

    @data_reduction.setter
    def data_reduction(self, value: Optional[pulumi.Input[builtins.float]]):
        pulumi.set(self, "data_reduction", value)

    @property
    @pulumi.getter
    def snapshots(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Physical space used by snapshots in bytes.
        """
        return pulumi.get(self, "snapshots")

    @snapshots.setter
    def snapshots(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "snapshots", value)

    @property
    @pulumi.getter(name="snapshotsEffective")
    def snapshots_effective(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Effective snapshot space used in bytes.
        """
        return pulumi.get(self, "snapshots_effective")

    @snapshots_effective.setter
    def snapshots_effective(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "snapshots_effective", value)

    @property
    @pulumi.getter(name="totalPhysical")
    def total_physical(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Total physical space used in bytes.
        """
        return pulumi.get(self, "total_physical")

    @total_physical.setter
    def total_physical(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "total_physical", value)

    @property
    @pulumi.getter
    def unique(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Unique physical space used in bytes.
        """
        return pulumi.get(self, "unique")

    @unique.setter
    def unique(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "unique", value)

    @property
    @pulumi.getter
    def virtual(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Virtual (logical) space used in bytes.
        """
        return pulumi.get(self, "virtual")

    @virtual.setter
    def virtual(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "virtual", value)


if not MYPY:
    class ObjectStoreAccountSpaceArgsDict(TypedDict):
        data_reduction: NotRequired[pulumi.Input[builtins.float]]
        """
        Data reduction ratio.
        """
        snapshots: NotRequired[pulumi.Input[builtins.int]]
        """
        Physical space used by snapshots in bytes.
        """
        snapshots_effective: NotRequired[pulumi.Input[builtins.int]]
        """
        Effective snapshot space used in bytes.
        """
        total_physical: NotRequired[pulumi.Input[builtins.int]]
        """
        Total physical space used in bytes.
        """
        unique: NotRequired[pulumi.Input[builtins.int]]
        """
        Unique physical space used in bytes.
        """
        virtual: NotRequired[pulumi.Input[builtins.int]]
        """
        Virtual (logical) space used in bytes.
        """
elif False:
    ObjectStoreAccountSpaceArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class ObjectStoreAccountSpaceArgs:
    def __init__(__self__, *,
                 data_reduction: Optional[pulumi.Input[builtins.float]] = None,
                 snapshots: Optional[pulumi.Input[builtins.int]] = None,
                 snapshots_effective: Optional[pulumi.Input[builtins.int]] = None,
                 total_physical: Optional[pulumi.Input[builtins.int]] = None,
                 unique: Optional[pulumi.Input[builtins.int]] = None,
                 virtual: Optional[pulumi.Input[builtins.int]] = None):
        """
        :param pulumi.Input[builtins.float] data_reduction: Data reduction ratio.
        :param pulumi.Input[builtins.int] snapshots: Physical space used by snapshots in bytes.
        :param pulumi.Input[builtins.int] snapshots_effective: Effective snapshot space used in bytes.
        :param pulumi.Input[builtins.int] total_physical: Total physical space used in bytes.
        :param pulumi.Input[builtins.int] unique: Unique physical space used in bytes.
        :param pulumi.Input[builtins.int] virtual: Virtual (logical) space used in bytes.
        """
        if data_reduction is not None:
            pulumi.set(__self__, "data_reduction", data_reduction)
        if snapshots is not None:
            pulumi.set(__self__, "snapshots", snapshots)
        if snapshots_effective is not None:
            pulumi.set(__self__, "snapshots_effective", snapshots_effective)
        if total_physical is not None:
            pulumi.set(__self__, "total_physical", total_physical)
        if unique is not None:
            pulumi.set(__self__, "unique", unique)
        if virtual is not None:
            pulumi.set(__self__, "virtual", virtual)

    @property
    @pulumi.getter(name="dataReduction")
    def data_reduction(self) -> Optional[pulumi.Input[builtins.float]]:
        """
        Data reduction ratio.
        """
        return pulumi.get(self, "data_reduction")

    @data_reduction.setter
    def data_reduction(self, value: Optional[pulumi.Input[builtins.float]]):
        pulumi.set(self, "data_reduction", value)

    @property
    @pulumi.getter
    def snapshots(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Physical space used by snapshots in bytes.
        """
        return pulumi.get(self, "snapshots")

    @snapshots.setter
    def snapshots(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "snapshots", value)

    @property
    @pulumi.getter(name="snapshotsEffective")
    def snapshots_effective(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Effective snapshot space used in bytes.
        """
        return pulumi.get(self, "snapshots_effective")

    @snapshots_effective.setter
    def snapshots_effective(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "snapshots_effective", value)

    @property
    @pulumi.getter(name="totalPhysical")
    def total_physical(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Total physical space used in bytes.
        """
        return pulumi.get(self, "total_physical")

    @total_physical.setter
    def total_physical(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "total_physical", value)

    @property
    @pulumi.getter
    def unique(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Unique physical space used in bytes.
        """
        return pulumi.get(self, "unique")

    @unique.setter
    def unique(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "unique", value)

    @property
    @pulumi.getter
    def virtual(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Virtual (logical) space used in bytes.
        """
        return pulumi.get(self, "virtual")

    @virtual.setter
    def virtual(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "virtual", value)


if not MYPY:
    class ProviderAuthArgsDict(TypedDict):
        api_token: NotRequired[pulumi.Input[builtins.str]]
        """
        API token for session-based authentication. Falls back to FLASHBLADE_API_TOKEN environment variable.
        """
        oauth2: NotRequired[pulumi.Input['ProviderAuthOauth2ArgsDict']]
        """
        OAuth2 token-exchange authentication configuration.
        """
elif False:
    ProviderAuthArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class ProviderAuthArgs:
    def __init__(__self__, *,
                 api_token: Optional[pulumi.Input[builtins.str]] = None,
                 oauth2: Optional[pulumi.Input['ProviderAuthOauth2Args']] = None):
        """
        :param pulumi.Input[builtins.str] api_token: API token for session-based authentication. Falls back to FLASHBLADE_API_TOKEN environment variable.
        :param pulumi.Input['ProviderAuthOauth2Args'] oauth2: OAuth2 token-exchange authentication configuration.
        """
        if api_token is not None:
            pulumi.set(__self__, "api_token", api_token)
        if oauth2 is not None:
            pulumi.set(__self__, "oauth2", oauth2)

    @property
    @pulumi.getter(name="apiToken")
    def api_token(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        API token for session-based authentication. Falls back to FLASHBLADE_API_TOKEN environment variable.
        """
        return pulumi.get(self, "api_token")

    @api_token.setter
    def api_token(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "api_token", value)

    @property
    @pulumi.getter
    def oauth2(self) -> Optional[pulumi.Input['ProviderAuthOauth2Args']]:
        """
        OAuth2 token-exchange authentication configuration.
        """
        return pulumi.get(self, "oauth2")

    @oauth2.setter
    def oauth2(self, value: Optional[pulumi.Input['ProviderAuthOauth2Args']]):
        pulumi.set(self, "oauth2", value)


if not MYPY:
    class ProviderAuthOauth2ArgsDict(TypedDict):
        client_id: NotRequired[pulumi.Input[builtins.str]]
        """
        OAuth2 client ID. Falls back to FLASHBLADE_OAUTH2_CLIENT_ID environment variable.
        """
        issuer: NotRequired[pulumi.Input[builtins.str]]
        """
        OAuth2 issuer. Falls back to FLASHBLADE_OAUTH2_ISSUER environment variable.
        """
        key_id: NotRequired[pulumi.Input[builtins.str]]
        """
        OAuth2 key ID. Falls back to FLASHBLADE_OAUTH2_KEY_ID environment variable.
        """
elif False:
    ProviderAuthOauth2ArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class ProviderAuthOauth2Args:
    def __init__(__self__, *,
                 client_id: Optional[pulumi.Input[builtins.str]] = None,
                 issuer: Optional[pulumi.Input[builtins.str]] = None,
                 key_id: Optional[pulumi.Input[builtins.str]] = None):
        """
        :param pulumi.Input[builtins.str] client_id: OAuth2 client ID. Falls back to FLASHBLADE_OAUTH2_CLIENT_ID environment variable.
        :param pulumi.Input[builtins.str] issuer: OAuth2 issuer. Falls back to FLASHBLADE_OAUTH2_ISSUER environment variable.
        :param pulumi.Input[builtins.str] key_id: OAuth2 key ID. Falls back to FLASHBLADE_OAUTH2_KEY_ID environment variable.
        """
        if client_id is not None:
            pulumi.set(__self__, "client_id", client_id)
        if issuer is not None:
            pulumi.set(__self__, "issuer", issuer)
        if key_id is not None:
            pulumi.set(__self__, "key_id", key_id)

    @property
    @pulumi.getter(name="clientId")
    def client_id(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        OAuth2 client ID. Falls back to FLASHBLADE_OAUTH2_CLIENT_ID environment variable.
        """
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "client_id", value)

    @property
    @pulumi.getter
    def issuer(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        OAuth2 issuer. Falls back to FLASHBLADE_OAUTH2_ISSUER environment variable.
        """
        return pulumi.get(self, "issuer")

    @issuer.setter
    def issuer(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "issuer", value)

    @property
    @pulumi.getter(name="keyId")
    def key_id(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        OAuth2 key ID. Falls back to FLASHBLADE_OAUTH2_KEY_ID environment variable.
        """
        return pulumi.get(self, "key_id")

    @key_id.setter
    def key_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "key_id", value)


