# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['FileSystemExportArgs', 'FileSystemExport']

@pulumi.input_type
class FileSystemExportArgs:
    def __init__(__self__, *,
                 file_system_name: pulumi.Input[builtins.str],
                 policy_name: pulumi.Input[builtins.str],
                 server_name: pulumi.Input[builtins.str],
                 export_name: Optional[pulumi.Input[builtins.str]] = None,
                 share_policy_name: Optional[pulumi.Input[builtins.str]] = None):
        """
        The set of arguments for constructing a FileSystemExport resource.
        :param pulumi.Input[builtins.str] file_system_name: The name of the file system to export. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] policy_name: The name of the NFS export policy to apply to the export.
        :param pulumi.Input[builtins.str] server_name: The name of the server to export to. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] export_name: The export name part. Defaults to the file system name if not set.
        :param pulumi.Input[builtins.str] share_policy_name: The name of the SMB share policy to apply to the export.
        """
        pulumi.set(__self__, "file_system_name", file_system_name)
        pulumi.set(__self__, "policy_name", policy_name)
        pulumi.set(__self__, "server_name", server_name)
        if export_name is not None:
            pulumi.set(__self__, "export_name", export_name)
        if share_policy_name is not None:
            pulumi.set(__self__, "share_policy_name", share_policy_name)

    @property
    @pulumi.getter(name="fileSystemName")
    def file_system_name(self) -> pulumi.Input[builtins.str]:
        """
        The name of the file system to export. Changing this forces a new resource.
        """
        return pulumi.get(self, "file_system_name")

    @file_system_name.setter
    def file_system_name(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "file_system_name", value)

    @property
    @pulumi.getter(name="policyName")
    def policy_name(self) -> pulumi.Input[builtins.str]:
        """
        The name of the NFS export policy to apply to the export.
        """
        return pulumi.get(self, "policy_name")

    @policy_name.setter
    def policy_name(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "policy_name", value)

    @property
    @pulumi.getter(name="serverName")
    def server_name(self) -> pulumi.Input[builtins.str]:
        """
        The name of the server to export to. Changing this forces a new resource.
        """
        return pulumi.get(self, "server_name")

    @server_name.setter
    def server_name(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "server_name", value)

    @property
    @pulumi.getter(name="exportName")
    def export_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The export name part. Defaults to the file system name if not set.
        """
        return pulumi.get(self, "export_name")

    @export_name.setter
    def export_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "export_name", value)

    @property
    @pulumi.getter(name="sharePolicyName")
    def share_policy_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the SMB share policy to apply to the export.
        """
        return pulumi.get(self, "share_policy_name")

    @share_policy_name.setter
    def share_policy_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "share_policy_name", value)


@pulumi.input_type
class _FileSystemExportState:
    def __init__(__self__, *,
                 enabled: Optional[pulumi.Input[builtins.bool]] = None,
                 export_name: Optional[pulumi.Input[builtins.str]] = None,
                 file_system_name: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 policy_name: Optional[pulumi.Input[builtins.str]] = None,
                 policy_type: Optional[pulumi.Input[builtins.str]] = None,
                 server_name: Optional[pulumi.Input[builtins.str]] = None,
                 share_policy_name: Optional[pulumi.Input[builtins.str]] = None,
                 status: Optional[pulumi.Input[builtins.str]] = None):
        """
        Input properties used for looking up and filtering FileSystemExport resources.
        :param pulumi.Input[builtins.bool] enabled: Whether the export is enabled.
        :param pulumi.Input[builtins.str] export_name: The export name part. Defaults to the file system name if not set.
        :param pulumi.Input[builtins.str] file_system_name: The name of the file system to export. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] name: The combined name of the export (e.g. 'filesystem/export_name').
        :param pulumi.Input[builtins.str] policy_name: The name of the NFS export policy to apply to the export.
        :param pulumi.Input[builtins.str] policy_type: The policy type ('nfs' or 'smb').
        :param pulumi.Input[builtins.str] server_name: The name of the server to export to. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] share_policy_name: The name of the SMB share policy to apply to the export.
        :param pulumi.Input[builtins.str] status: The status of the export.
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if export_name is not None:
            pulumi.set(__self__, "export_name", export_name)
        if file_system_name is not None:
            pulumi.set(__self__, "file_system_name", file_system_name)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if policy_name is not None:
            pulumi.set(__self__, "policy_name", policy_name)
        if policy_type is not None:
            pulumi.set(__self__, "policy_type", policy_type)
        if server_name is not None:
            pulumi.set(__self__, "server_name", server_name)
        if share_policy_name is not None:
            pulumi.set(__self__, "share_policy_name", share_policy_name)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[builtins.bool]]:
        """
        Whether the export is enabled.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter(name="exportName")
    def export_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The export name part. Defaults to the file system name if not set.
        """
        return pulumi.get(self, "export_name")

    @export_name.setter
    def export_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "export_name", value)

    @property
    @pulumi.getter(name="fileSystemName")
    def file_system_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the file system to export. Changing this forces a new resource.
        """
        return pulumi.get(self, "file_system_name")

    @file_system_name.setter
    def file_system_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "file_system_name", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The combined name of the export (e.g. 'filesystem/export_name').
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="policyName")
    def policy_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the NFS export policy to apply to the export.
        """
        return pulumi.get(self, "policy_name")

    @policy_name.setter
    def policy_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "policy_name", value)

    @property
    @pulumi.getter(name="policyType")
    def policy_type(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The policy type ('nfs' or 'smb').
        """
        return pulumi.get(self, "policy_type")

    @policy_type.setter
    def policy_type(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "policy_type", value)

    @property
    @pulumi.getter(name="serverName")
    def server_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the server to export to. Changing this forces a new resource.
        """
        return pulumi.get(self, "server_name")

    @server_name.setter
    def server_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "server_name", value)

    @property
    @pulumi.getter(name="sharePolicyName")
    def share_policy_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the SMB share policy to apply to the export.
        """
        return pulumi.get(self, "share_policy_name")

    @share_policy_name.setter
    def share_policy_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "share_policy_name", value)

    @property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The status of the export.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "status", value)


class FileSystemExport(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 export_name: Optional[pulumi.Input[builtins.str]] = None,
                 file_system_name: Optional[pulumi.Input[builtins.str]] = None,
                 policy_name: Optional[pulumi.Input[builtins.str]] = None,
                 server_name: Optional[pulumi.Input[builtins.str]] = None,
                 share_policy_name: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        """
        Create a FileSystemExport resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] export_name: The export name part. Defaults to the file system name if not set.
        :param pulumi.Input[builtins.str] file_system_name: The name of the file system to export. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] policy_name: The name of the NFS export policy to apply to the export.
        :param pulumi.Input[builtins.str] server_name: The name of the server to export to. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] share_policy_name: The name of the SMB share policy to apply to the export.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: FileSystemExportArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a FileSystemExport resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param FileSystemExportArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(FileSystemExportArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 export_name: Optional[pulumi.Input[builtins.str]] = None,
                 file_system_name: Optional[pulumi.Input[builtins.str]] = None,
                 policy_name: Optional[pulumi.Input[builtins.str]] = None,
                 server_name: Optional[pulumi.Input[builtins.str]] = None,
                 share_policy_name: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = FileSystemExportArgs.__new__(FileSystemExportArgs)

            __props__.__dict__["export_name"] = export_name
            if file_system_name is None and not opts.urn:
                raise TypeError("Missing required property 'file_system_name'")
            __props__.__dict__["file_system_name"] = file_system_name
            if policy_name is None and not opts.urn:
                raise TypeError("Missing required property 'policy_name'")
            __props__.__dict__["policy_name"] = policy_name
            if server_name is None and not opts.urn:
                raise TypeError("Missing required property 'server_name'")
            __props__.__dict__["server_name"] = server_name
            __props__.__dict__["share_policy_name"] = share_policy_name
            __props__.__dict__["enabled"] = None
            __props__.__dict__["name"] = None
            __props__.__dict__["policy_type"] = None
            __props__.__dict__["status"] = None
        super(FileSystemExport, __self__).__init__(
            'flashblade:index/fileSystemExport:FileSystemExport',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            enabled: Optional[pulumi.Input[builtins.bool]] = None,
            export_name: Optional[pulumi.Input[builtins.str]] = None,
            file_system_name: Optional[pulumi.Input[builtins.str]] = None,
            name: Optional[pulumi.Input[builtins.str]] = None,
            policy_name: Optional[pulumi.Input[builtins.str]] = None,
            policy_type: Optional[pulumi.Input[builtins.str]] = None,
            server_name: Optional[pulumi.Input[builtins.str]] = None,
            share_policy_name: Optional[pulumi.Input[builtins.str]] = None,
            status: Optional[pulumi.Input[builtins.str]] = None) -> 'FileSystemExport':
        """
        Get an existing FileSystemExport resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.bool] enabled: Whether the export is enabled.
        :param pulumi.Input[builtins.str] export_name: The export name part. Defaults to the file system name if not set.
        :param pulumi.Input[builtins.str] file_system_name: The name of the file system to export. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] name: The combined name of the export (e.g. 'filesystem/export_name').
        :param pulumi.Input[builtins.str] policy_name: The name of the NFS export policy to apply to the export.
        :param pulumi.Input[builtins.str] policy_type: The policy type ('nfs' or 'smb').
        :param pulumi.Input[builtins.str] server_name: The name of the server to export to. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] share_policy_name: The name of the SMB share policy to apply to the export.
        :param pulumi.Input[builtins.str] status: The status of the export.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _FileSystemExportState.__new__(_FileSystemExportState)

        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["export_name"] = export_name
        __props__.__dict__["file_system_name"] = file_system_name
        __props__.__dict__["name"] = name
        __props__.__dict__["policy_name"] = policy_name
        __props__.__dict__["policy_type"] = policy_type
        __props__.__dict__["server_name"] = server_name
        __props__.__dict__["share_policy_name"] = share_policy_name
        __props__.__dict__["status"] = status
        return FileSystemExport(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[builtins.bool]:
        """
        Whether the export is enabled.
        """
        return pulumi.get(self, "enabled")

    @property
    @pulumi.getter(name="exportName")
    def export_name(self) -> pulumi.Output[builtins.str]:
        """
        The export name part. Defaults to the file system name if not set.
        """
        return pulumi.get(self, "export_name")

    @property
    @pulumi.getter(name="fileSystemName")
    def file_system_name(self) -> pulumi.Output[builtins.str]:
        """
        The name of the file system to export. Changing this forces a new resource.
        """
        return pulumi.get(self, "file_system_name")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[builtins.str]:
        """
        The combined name of the export (e.g. 'filesystem/export_name').
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="policyName")
    def policy_name(self) -> pulumi.Output[builtins.str]:
        """
        The name of the NFS export policy to apply to the export.
        """
        return pulumi.get(self, "policy_name")

    @property
    @pulumi.getter(name="policyType")
    def policy_type(self) -> pulumi.Output[builtins.str]:
        """
        The policy type ('nfs' or 'smb').
        """
        return pulumi.get(self, "policy_type")

    @property
    @pulumi.getter(name="serverName")
    def server_name(self) -> pulumi.Output[builtins.str]:
        """
        The name of the server to export to. Changing this forces a new resource.
        """
        return pulumi.get(self, "server_name")

    @property
    @pulumi.getter(name="sharePolicyName")
    def share_policy_name(self) -> pulumi.Output[builtins.str]:
        """
        The name of the SMB share policy to apply to the export.
        """
        return pulumi.get(self, "share_policy_name")

    @property
    @pulumi.getter
    def status(self) -> pulumi.Output[builtins.str]:
        """
        The status of the export.
        """
        return pulumi.get(self, "status")

