# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetBucketAuditFilterResult',
    'AwaitableGetBucketAuditFilterResult',
    'get_bucket_audit_filter',
    'get_bucket_audit_filter_output',
]

@pulumi.output_type
class GetBucketAuditFilterResult:
    """
    A collection of values returned by getBucketAuditFilter.
    """
    def __init__(__self__, actions=None, bucket_name=None, id=None, s3_prefixes=None):
        if actions and not isinstance(actions, list):
            raise TypeError("Expected argument 'actions' to be a list")
        pulumi.set(__self__, "actions", actions)
        if bucket_name and not isinstance(bucket_name, str):
            raise TypeError("Expected argument 'bucket_name' to be a str")
        pulumi.set(__self__, "bucket_name", bucket_name)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if s3_prefixes and not isinstance(s3_prefixes, list):
            raise TypeError("Expected argument 's3_prefixes' to be a list")
        pulumi.set(__self__, "s3_prefixes", s3_prefixes)

    @property
    @pulumi.getter
    def actions(self) -> Sequence[builtins.str]:
        return pulumi.get(self, "actions")

    @property
    @pulumi.getter(name="bucketName")
    def bucket_name(self) -> builtins.str:
        return pulumi.get(self, "bucket_name")

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="s3Prefixes")
    def s3_prefixes(self) -> Sequence[builtins.str]:
        return pulumi.get(self, "s3_prefixes")


class AwaitableGetBucketAuditFilterResult(GetBucketAuditFilterResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetBucketAuditFilterResult(
            actions=self.actions,
            bucket_name=self.bucket_name,
            id=self.id,
            s3_prefixes=self.s3_prefixes)


def get_bucket_audit_filter(bucket_name: Optional[builtins.str] = None,
                            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetBucketAuditFilterResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['bucketName'] = bucket_name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('flashblade:index/getBucketAuditFilter:getBucketAuditFilter', __args__, opts=opts, typ=GetBucketAuditFilterResult).value

    return AwaitableGetBucketAuditFilterResult(
        actions=pulumi.get(__ret__, 'actions'),
        bucket_name=pulumi.get(__ret__, 'bucket_name'),
        id=pulumi.get(__ret__, 'id'),
        s3_prefixes=pulumi.get(__ret__, 's3_prefixes'))
def get_bucket_audit_filter_output(bucket_name: Optional[pulumi.Input[builtins.str]] = None,
                                   opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetBucketAuditFilterResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['bucketName'] = bucket_name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('flashblade:index/getBucketAuditFilter:getBucketAuditFilter', __args__, opts=opts, typ=GetBucketAuditFilterResult)
    return __ret__.apply(lambda __response__: GetBucketAuditFilterResult(
        actions=pulumi.get(__response__, 'actions'),
        bucket_name=pulumi.get(__response__, 'bucket_name'),
        id=pulumi.get(__response__, 'id'),
        s3_prefixes=pulumi.get(__response__, 's3_prefixes')))
