# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetCertificateResult',
    'AwaitableGetCertificateResult',
    'get_certificate',
    'get_certificate_output',
]

@pulumi.output_type
class GetCertificateResult:
    """
    A collection of values returned by getCertificate.
    """
    def __init__(__self__, certificate=None, certificate_type=None, common_name=None, country=None, email=None, id=None, intermediate_certificate=None, issued_by=None, issued_to=None, key_algorithm=None, key_size=None, locality=None, name=None, organization=None, organizational_unit=None, state=None, status=None, subject_alternative_names=None, valid_from=None, valid_to=None):
        if certificate and not isinstance(certificate, str):
            raise TypeError("Expected argument 'certificate' to be a str")
        pulumi.set(__self__, "certificate", certificate)
        if certificate_type and not isinstance(certificate_type, str):
            raise TypeError("Expected argument 'certificate_type' to be a str")
        pulumi.set(__self__, "certificate_type", certificate_type)
        if common_name and not isinstance(common_name, str):
            raise TypeError("Expected argument 'common_name' to be a str")
        pulumi.set(__self__, "common_name", common_name)
        if country and not isinstance(country, str):
            raise TypeError("Expected argument 'country' to be a str")
        pulumi.set(__self__, "country", country)
        if email and not isinstance(email, str):
            raise TypeError("Expected argument 'email' to be a str")
        pulumi.set(__self__, "email", email)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if intermediate_certificate and not isinstance(intermediate_certificate, str):
            raise TypeError("Expected argument 'intermediate_certificate' to be a str")
        pulumi.set(__self__, "intermediate_certificate", intermediate_certificate)
        if issued_by and not isinstance(issued_by, str):
            raise TypeError("Expected argument 'issued_by' to be a str")
        pulumi.set(__self__, "issued_by", issued_by)
        if issued_to and not isinstance(issued_to, str):
            raise TypeError("Expected argument 'issued_to' to be a str")
        pulumi.set(__self__, "issued_to", issued_to)
        if key_algorithm and not isinstance(key_algorithm, str):
            raise TypeError("Expected argument 'key_algorithm' to be a str")
        pulumi.set(__self__, "key_algorithm", key_algorithm)
        if key_size and not isinstance(key_size, int):
            raise TypeError("Expected argument 'key_size' to be a int")
        pulumi.set(__self__, "key_size", key_size)
        if locality and not isinstance(locality, str):
            raise TypeError("Expected argument 'locality' to be a str")
        pulumi.set(__self__, "locality", locality)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if organization and not isinstance(organization, str):
            raise TypeError("Expected argument 'organization' to be a str")
        pulumi.set(__self__, "organization", organization)
        if organizational_unit and not isinstance(organizational_unit, str):
            raise TypeError("Expected argument 'organizational_unit' to be a str")
        pulumi.set(__self__, "organizational_unit", organizational_unit)
        if state and not isinstance(state, str):
            raise TypeError("Expected argument 'state' to be a str")
        pulumi.set(__self__, "state", state)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if subject_alternative_names and not isinstance(subject_alternative_names, list):
            raise TypeError("Expected argument 'subject_alternative_names' to be a list")
        pulumi.set(__self__, "subject_alternative_names", subject_alternative_names)
        if valid_from and not isinstance(valid_from, int):
            raise TypeError("Expected argument 'valid_from' to be a int")
        pulumi.set(__self__, "valid_from", valid_from)
        if valid_to and not isinstance(valid_to, int):
            raise TypeError("Expected argument 'valid_to' to be a int")
        pulumi.set(__self__, "valid_to", valid_to)

    @property
    @pulumi.getter
    def certificate(self) -> builtins.str:
        return pulumi.get(self, "certificate")

    @property
    @pulumi.getter(name="certificateType")
    def certificate_type(self) -> builtins.str:
        return pulumi.get(self, "certificate_type")

    @property
    @pulumi.getter(name="commonName")
    def common_name(self) -> builtins.str:
        return pulumi.get(self, "common_name")

    @property
    @pulumi.getter
    def country(self) -> builtins.str:
        return pulumi.get(self, "country")

    @property
    @pulumi.getter
    def email(self) -> builtins.str:
        return pulumi.get(self, "email")

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="intermediateCertificate")
    def intermediate_certificate(self) -> builtins.str:
        return pulumi.get(self, "intermediate_certificate")

    @property
    @pulumi.getter(name="issuedBy")
    def issued_by(self) -> builtins.str:
        return pulumi.get(self, "issued_by")

    @property
    @pulumi.getter(name="issuedTo")
    def issued_to(self) -> builtins.str:
        return pulumi.get(self, "issued_to")

    @property
    @pulumi.getter(name="keyAlgorithm")
    def key_algorithm(self) -> builtins.str:
        return pulumi.get(self, "key_algorithm")

    @property
    @pulumi.getter(name="keySize")
    def key_size(self) -> builtins.int:
        return pulumi.get(self, "key_size")

    @property
    @pulumi.getter
    def locality(self) -> builtins.str:
        return pulumi.get(self, "locality")

    @property
    @pulumi.getter
    def name(self) -> builtins.str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def organization(self) -> builtins.str:
        return pulumi.get(self, "organization")

    @property
    @pulumi.getter(name="organizationalUnit")
    def organizational_unit(self) -> builtins.str:
        return pulumi.get(self, "organizational_unit")

    @property
    @pulumi.getter
    def state(self) -> builtins.str:
        return pulumi.get(self, "state")

    @property
    @pulumi.getter
    def status(self) -> builtins.str:
        return pulumi.get(self, "status")

    @property
    @pulumi.getter(name="subjectAlternativeNames")
    def subject_alternative_names(self) -> Sequence[builtins.str]:
        return pulumi.get(self, "subject_alternative_names")

    @property
    @pulumi.getter(name="validFrom")
    def valid_from(self) -> builtins.int:
        return pulumi.get(self, "valid_from")

    @property
    @pulumi.getter(name="validTo")
    def valid_to(self) -> builtins.int:
        return pulumi.get(self, "valid_to")


class AwaitableGetCertificateResult(GetCertificateResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCertificateResult(
            certificate=self.certificate,
            certificate_type=self.certificate_type,
            common_name=self.common_name,
            country=self.country,
            email=self.email,
            id=self.id,
            intermediate_certificate=self.intermediate_certificate,
            issued_by=self.issued_by,
            issued_to=self.issued_to,
            key_algorithm=self.key_algorithm,
            key_size=self.key_size,
            locality=self.locality,
            name=self.name,
            organization=self.organization,
            organizational_unit=self.organizational_unit,
            state=self.state,
            status=self.status,
            subject_alternative_names=self.subject_alternative_names,
            valid_from=self.valid_from,
            valid_to=self.valid_to)


def get_certificate(name: Optional[builtins.str] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCertificateResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('flashblade:index/getCertificate:getCertificate', __args__, opts=opts, typ=GetCertificateResult).value

    return AwaitableGetCertificateResult(
        certificate=pulumi.get(__ret__, 'certificate'),
        certificate_type=pulumi.get(__ret__, 'certificate_type'),
        common_name=pulumi.get(__ret__, 'common_name'),
        country=pulumi.get(__ret__, 'country'),
        email=pulumi.get(__ret__, 'email'),
        id=pulumi.get(__ret__, 'id'),
        intermediate_certificate=pulumi.get(__ret__, 'intermediate_certificate'),
        issued_by=pulumi.get(__ret__, 'issued_by'),
        issued_to=pulumi.get(__ret__, 'issued_to'),
        key_algorithm=pulumi.get(__ret__, 'key_algorithm'),
        key_size=pulumi.get(__ret__, 'key_size'),
        locality=pulumi.get(__ret__, 'locality'),
        name=pulumi.get(__ret__, 'name'),
        organization=pulumi.get(__ret__, 'organization'),
        organizational_unit=pulumi.get(__ret__, 'organizational_unit'),
        state=pulumi.get(__ret__, 'state'),
        status=pulumi.get(__ret__, 'status'),
        subject_alternative_names=pulumi.get(__ret__, 'subject_alternative_names'),
        valid_from=pulumi.get(__ret__, 'valid_from'),
        valid_to=pulumi.get(__ret__, 'valid_to'))
def get_certificate_output(name: Optional[pulumi.Input[builtins.str]] = None,
                           opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCertificateResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('flashblade:index/getCertificate:getCertificate', __args__, opts=opts, typ=GetCertificateResult)
    return __ret__.apply(lambda __response__: GetCertificateResult(
        certificate=pulumi.get(__response__, 'certificate'),
        certificate_type=pulumi.get(__response__, 'certificate_type'),
        common_name=pulumi.get(__response__, 'common_name'),
        country=pulumi.get(__response__, 'country'),
        email=pulumi.get(__response__, 'email'),
        id=pulumi.get(__response__, 'id'),
        intermediate_certificate=pulumi.get(__response__, 'intermediate_certificate'),
        issued_by=pulumi.get(__response__, 'issued_by'),
        issued_to=pulumi.get(__response__, 'issued_to'),
        key_algorithm=pulumi.get(__response__, 'key_algorithm'),
        key_size=pulumi.get(__response__, 'key_size'),
        locality=pulumi.get(__response__, 'locality'),
        name=pulumi.get(__response__, 'name'),
        organization=pulumi.get(__response__, 'organization'),
        organizational_unit=pulumi.get(__response__, 'organizational_unit'),
        state=pulumi.get(__response__, 'state'),
        status=pulumi.get(__response__, 'status'),
        subject_alternative_names=pulumi.get(__response__, 'subject_alternative_names'),
        valid_from=pulumi.get(__response__, 'valid_from'),
        valid_to=pulumi.get(__response__, 'valid_to')))
