# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetObjectStoreUserResult',
    'AwaitableGetObjectStoreUserResult',
    'get_object_store_user',
    'get_object_store_user_output',
]

@pulumi.output_type
class GetObjectStoreUserResult:
    """
    A collection of values returned by getObjectStoreUser.
    """
    def __init__(__self__, full_access=None, id=None, name=None):
        if full_access and not isinstance(full_access, bool):
            raise TypeError("Expected argument 'full_access' to be a bool")
        pulumi.set(__self__, "full_access", full_access)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter(name="fullAccess")
    def full_access(self) -> builtins.bool:
        return pulumi.get(self, "full_access")

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> builtins.str:
        return pulumi.get(self, "name")


class AwaitableGetObjectStoreUserResult(GetObjectStoreUserResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetObjectStoreUserResult(
            full_access=self.full_access,
            id=self.id,
            name=self.name)


def get_object_store_user(name: Optional[builtins.str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetObjectStoreUserResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('flashblade:index/getObjectStoreUser:getObjectStoreUser', __args__, opts=opts, typ=GetObjectStoreUserResult).value

    return AwaitableGetObjectStoreUserResult(
        full_access=pulumi.get(__ret__, 'full_access'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'))
def get_object_store_user_output(name: Optional[pulumi.Input[builtins.str]] = None,
                                 opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetObjectStoreUserResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('flashblade:index/getObjectStoreUser:getObjectStoreUser', __args__, opts=opts, typ=GetObjectStoreUserResult)
    return __ret__.apply(lambda __response__: GetObjectStoreUserResult(
        full_access=pulumi.get(__response__, 'full_access'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name')))
