# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetNetworkInterfaceResult',
    'AwaitableGetNetworkInterfaceResult',
    'get_network_interface',
    'get_network_interface_output',
]

@pulumi.output_type
class GetNetworkInterfaceResult:
    """
    A collection of values returned by getNetworkInterface.
    """
    def __init__(__self__, address=None, attached_servers=None, enabled=None, gateway=None, id=None, mtu=None, name=None, netmask=None, realms=None, services=None, subnet_name=None, type=None, vlan=None):
        if address and not isinstance(address, str):
            raise TypeError("Expected argument 'address' to be a str")
        pulumi.set(__self__, "address", address)
        if attached_servers and not isinstance(attached_servers, list):
            raise TypeError("Expected argument 'attached_servers' to be a list")
        pulumi.set(__self__, "attached_servers", attached_servers)
        if enabled and not isinstance(enabled, bool):
            raise TypeError("Expected argument 'enabled' to be a bool")
        pulumi.set(__self__, "enabled", enabled)
        if gateway and not isinstance(gateway, str):
            raise TypeError("Expected argument 'gateway' to be a str")
        pulumi.set(__self__, "gateway", gateway)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if mtu and not isinstance(mtu, int):
            raise TypeError("Expected argument 'mtu' to be a int")
        pulumi.set(__self__, "mtu", mtu)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if netmask and not isinstance(netmask, str):
            raise TypeError("Expected argument 'netmask' to be a str")
        pulumi.set(__self__, "netmask", netmask)
        if realms and not isinstance(realms, list):
            raise TypeError("Expected argument 'realms' to be a list")
        pulumi.set(__self__, "realms", realms)
        if services and not isinstance(services, str):
            raise TypeError("Expected argument 'services' to be a str")
        pulumi.set(__self__, "services", services)
        if subnet_name and not isinstance(subnet_name, str):
            raise TypeError("Expected argument 'subnet_name' to be a str")
        pulumi.set(__self__, "subnet_name", subnet_name)
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        pulumi.set(__self__, "type", type)
        if vlan and not isinstance(vlan, int):
            raise TypeError("Expected argument 'vlan' to be a int")
        pulumi.set(__self__, "vlan", vlan)

    @property
    @pulumi.getter
    def address(self) -> builtins.str:
        return pulumi.get(self, "address")

    @property
    @pulumi.getter(name="attachedServers")
    def attached_servers(self) -> Sequence[builtins.str]:
        return pulumi.get(self, "attached_servers")

    @property
    @pulumi.getter
    def enabled(self) -> builtins.bool:
        return pulumi.get(self, "enabled")

    @property
    @pulumi.getter
    def gateway(self) -> builtins.str:
        return pulumi.get(self, "gateway")

    @property
    @pulumi.getter
    def id(self) -> builtins.str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def mtu(self) -> builtins.int:
        return pulumi.get(self, "mtu")

    @property
    @pulumi.getter
    def name(self) -> builtins.str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def netmask(self) -> builtins.str:
        return pulumi.get(self, "netmask")

    @property
    @pulumi.getter
    def realms(self) -> Sequence[builtins.str]:
        return pulumi.get(self, "realms")

    @property
    @pulumi.getter
    def services(self) -> builtins.str:
        return pulumi.get(self, "services")

    @property
    @pulumi.getter(name="subnetName")
    def subnet_name(self) -> builtins.str:
        return pulumi.get(self, "subnet_name")

    @property
    @pulumi.getter
    def type(self) -> builtins.str:
        return pulumi.get(self, "type")

    @property
    @pulumi.getter
    def vlan(self) -> builtins.int:
        return pulumi.get(self, "vlan")


class AwaitableGetNetworkInterfaceResult(GetNetworkInterfaceResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetNetworkInterfaceResult(
            address=self.address,
            attached_servers=self.attached_servers,
            enabled=self.enabled,
            gateway=self.gateway,
            id=self.id,
            mtu=self.mtu,
            name=self.name,
            netmask=self.netmask,
            realms=self.realms,
            services=self.services,
            subnet_name=self.subnet_name,
            type=self.type,
            vlan=self.vlan)


def get_network_interface(name: Optional[builtins.str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetNetworkInterfaceResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('flashblade:index/getNetworkInterface:getNetworkInterface', __args__, opts=opts, typ=GetNetworkInterfaceResult).value

    return AwaitableGetNetworkInterfaceResult(
        address=pulumi.get(__ret__, 'address'),
        attached_servers=pulumi.get(__ret__, 'attached_servers'),
        enabled=pulumi.get(__ret__, 'enabled'),
        gateway=pulumi.get(__ret__, 'gateway'),
        id=pulumi.get(__ret__, 'id'),
        mtu=pulumi.get(__ret__, 'mtu'),
        name=pulumi.get(__ret__, 'name'),
        netmask=pulumi.get(__ret__, 'netmask'),
        realms=pulumi.get(__ret__, 'realms'),
        services=pulumi.get(__ret__, 'services'),
        subnet_name=pulumi.get(__ret__, 'subnet_name'),
        type=pulumi.get(__ret__, 'type'),
        vlan=pulumi.get(__ret__, 'vlan'))
def get_network_interface_output(name: Optional[pulumi.Input[builtins.str]] = None,
                                 opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetNetworkInterfaceResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('flashblade:index/getNetworkInterface:getNetworkInterface', __args__, opts=opts, typ=GetNetworkInterfaceResult)
    return __ret__.apply(lambda __response__: GetNetworkInterfaceResult(
        address=pulumi.get(__response__, 'address'),
        attached_servers=pulumi.get(__response__, 'attached_servers'),
        enabled=pulumi.get(__response__, 'enabled'),
        gateway=pulumi.get(__response__, 'gateway'),
        id=pulumi.get(__response__, 'id'),
        mtu=pulumi.get(__response__, 'mtu'),
        name=pulumi.get(__response__, 'name'),
        netmask=pulumi.get(__response__, 'netmask'),
        realms=pulumi.get(__response__, 'realms'),
        services=pulumi.get(__response__, 'services'),
        subnet_name=pulumi.get(__response__, 'subnet_name'),
        type=pulumi.get(__response__, 'type'),
        vlan=pulumi.get(__response__, 'vlan')))
