# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ObjectStoreRemoteCredentialsArgs', 'ObjectStoreRemoteCredentials']

@pulumi.input_type
class ObjectStoreRemoteCredentialsArgs:
    def __init__(__self__, *,
                 access_key_id: pulumi.Input[builtins.str],
                 name: pulumi.Input[builtins.str],
                 secret_access_key: pulumi.Input[builtins.str],
                 remote_name: Optional[pulumi.Input[builtins.str]] = None,
                 target_name: Optional[pulumi.Input[builtins.str]] = None):
        """
        The set of arguments for constructing a ObjectStoreRemoteCredentials resource.
        :param pulumi.Input[builtins.str] access_key_id: The access key ID for the remote S3 credentials.
        :param pulumi.Input[builtins.str] name: The name of the remote credentials. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] secret_access_key: The secret access key for the remote S3 credentials.
        :param pulumi.Input[builtins.str] remote_name: The name of the remote array connection. Populated automatically from the API response. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] target_name: The name of the target (S3-compatible endpoint). Mutually exclusive with remote_name. Changing this forces a new resource.
        """
        pulumi.set(__self__, "access_key_id", access_key_id)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "secret_access_key", secret_access_key)
        if remote_name is not None:
            pulumi.set(__self__, "remote_name", remote_name)
        if target_name is not None:
            pulumi.set(__self__, "target_name", target_name)

    @property
    @pulumi.getter(name="accessKeyId")
    def access_key_id(self) -> pulumi.Input[builtins.str]:
        """
        The access key ID for the remote S3 credentials.
        """
        return pulumi.get(self, "access_key_id")

    @access_key_id.setter
    def access_key_id(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "access_key_id", value)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[builtins.str]:
        """
        The name of the remote credentials. Changing this forces a new resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="secretAccessKey")
    def secret_access_key(self) -> pulumi.Input[builtins.str]:
        """
        The secret access key for the remote S3 credentials.
        """
        return pulumi.get(self, "secret_access_key")

    @secret_access_key.setter
    def secret_access_key(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "secret_access_key", value)

    @property
    @pulumi.getter(name="remoteName")
    def remote_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the remote array connection. Populated automatically from the API response. Changing this forces a new resource.
        """
        return pulumi.get(self, "remote_name")

    @remote_name.setter
    def remote_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "remote_name", value)

    @property
    @pulumi.getter(name="targetName")
    def target_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the target (S3-compatible endpoint). Mutually exclusive with remote_name. Changing this forces a new resource.
        """
        return pulumi.get(self, "target_name")

    @target_name.setter
    def target_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "target_name", value)


@pulumi.input_type
class _ObjectStoreRemoteCredentialsState:
    def __init__(__self__, *,
                 access_key_id: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 remote_name: Optional[pulumi.Input[builtins.str]] = None,
                 secret_access_key: Optional[pulumi.Input[builtins.str]] = None,
                 target_name: Optional[pulumi.Input[builtins.str]] = None):
        """
        Input properties used for looking up and filtering ObjectStoreRemoteCredentials resources.
        :param pulumi.Input[builtins.str] access_key_id: The access key ID for the remote S3 credentials.
        :param pulumi.Input[builtins.str] name: The name of the remote credentials. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] remote_name: The name of the remote array connection. Populated automatically from the API response. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] secret_access_key: The secret access key for the remote S3 credentials.
        :param pulumi.Input[builtins.str] target_name: The name of the target (S3-compatible endpoint). Mutually exclusive with remote_name. Changing this forces a new resource.
        """
        if access_key_id is not None:
            pulumi.set(__self__, "access_key_id", access_key_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if remote_name is not None:
            pulumi.set(__self__, "remote_name", remote_name)
        if secret_access_key is not None:
            pulumi.set(__self__, "secret_access_key", secret_access_key)
        if target_name is not None:
            pulumi.set(__self__, "target_name", target_name)

    @property
    @pulumi.getter(name="accessKeyId")
    def access_key_id(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The access key ID for the remote S3 credentials.
        """
        return pulumi.get(self, "access_key_id")

    @access_key_id.setter
    def access_key_id(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "access_key_id", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the remote credentials. Changing this forces a new resource.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="remoteName")
    def remote_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the remote array connection. Populated automatically from the API response. Changing this forces a new resource.
        """
        return pulumi.get(self, "remote_name")

    @remote_name.setter
    def remote_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "remote_name", value)

    @property
    @pulumi.getter(name="secretAccessKey")
    def secret_access_key(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The secret access key for the remote S3 credentials.
        """
        return pulumi.get(self, "secret_access_key")

    @secret_access_key.setter
    def secret_access_key(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "secret_access_key", value)

    @property
    @pulumi.getter(name="targetName")
    def target_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        The name of the target (S3-compatible endpoint). Mutually exclusive with remote_name. Changing this forces a new resource.
        """
        return pulumi.get(self, "target_name")

    @target_name.setter
    def target_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "target_name", value)


class ObjectStoreRemoteCredentials(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_key_id: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 remote_name: Optional[pulumi.Input[builtins.str]] = None,
                 secret_access_key: Optional[pulumi.Input[builtins.str]] = None,
                 target_name: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        """
        Create a ObjectStoreRemoteCredentials resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] access_key_id: The access key ID for the remote S3 credentials.
        :param pulumi.Input[builtins.str] name: The name of the remote credentials. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] remote_name: The name of the remote array connection. Populated automatically from the API response. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] secret_access_key: The secret access key for the remote S3 credentials.
        :param pulumi.Input[builtins.str] target_name: The name of the target (S3-compatible endpoint). Mutually exclusive with remote_name. Changing this forces a new resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ObjectStoreRemoteCredentialsArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ObjectStoreRemoteCredentials resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ObjectStoreRemoteCredentialsArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ObjectStoreRemoteCredentialsArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_key_id: Optional[pulumi.Input[builtins.str]] = None,
                 name: Optional[pulumi.Input[builtins.str]] = None,
                 remote_name: Optional[pulumi.Input[builtins.str]] = None,
                 secret_access_key: Optional[pulumi.Input[builtins.str]] = None,
                 target_name: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ObjectStoreRemoteCredentialsArgs.__new__(ObjectStoreRemoteCredentialsArgs)

            if access_key_id is None and not opts.urn:
                raise TypeError("Missing required property 'access_key_id'")
            __props__.__dict__["access_key_id"] = None if access_key_id is None else pulumi.Output.secret(access_key_id)
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["remote_name"] = remote_name
            if secret_access_key is None and not opts.urn:
                raise TypeError("Missing required property 'secret_access_key'")
            __props__.__dict__["secret_access_key"] = None if secret_access_key is None else pulumi.Output.secret(secret_access_key)
            __props__.__dict__["target_name"] = target_name
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["accessKeyId", "secretAccessKey"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ObjectStoreRemoteCredentials, __self__).__init__(
            'flashblade:index/objectStoreRemoteCredentials:ObjectStoreRemoteCredentials',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            access_key_id: Optional[pulumi.Input[builtins.str]] = None,
            name: Optional[pulumi.Input[builtins.str]] = None,
            remote_name: Optional[pulumi.Input[builtins.str]] = None,
            secret_access_key: Optional[pulumi.Input[builtins.str]] = None,
            target_name: Optional[pulumi.Input[builtins.str]] = None) -> 'ObjectStoreRemoteCredentials':
        """
        Get an existing ObjectStoreRemoteCredentials resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] access_key_id: The access key ID for the remote S3 credentials.
        :param pulumi.Input[builtins.str] name: The name of the remote credentials. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] remote_name: The name of the remote array connection. Populated automatically from the API response. Changing this forces a new resource.
        :param pulumi.Input[builtins.str] secret_access_key: The secret access key for the remote S3 credentials.
        :param pulumi.Input[builtins.str] target_name: The name of the target (S3-compatible endpoint). Mutually exclusive with remote_name. Changing this forces a new resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ObjectStoreRemoteCredentialsState.__new__(_ObjectStoreRemoteCredentialsState)

        __props__.__dict__["access_key_id"] = access_key_id
        __props__.__dict__["name"] = name
        __props__.__dict__["remote_name"] = remote_name
        __props__.__dict__["secret_access_key"] = secret_access_key
        __props__.__dict__["target_name"] = target_name
        return ObjectStoreRemoteCredentials(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="accessKeyId")
    def access_key_id(self) -> pulumi.Output[builtins.str]:
        """
        The access key ID for the remote S3 credentials.
        """
        return pulumi.get(self, "access_key_id")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[builtins.str]:
        """
        The name of the remote credentials. Changing this forces a new resource.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="remoteName")
    def remote_name(self) -> pulumi.Output[builtins.str]:
        """
        The name of the remote array connection. Populated automatically from the API response. Changing this forces a new resource.
        """
        return pulumi.get(self, "remote_name")

    @property
    @pulumi.getter(name="secretAccessKey")
    def secret_access_key(self) -> pulumi.Output[builtins.str]:
        """
        The secret access key for the remote S3 credentials.
        """
        return pulumi.get(self, "secret_access_key")

    @property
    @pulumi.getter(name="targetName")
    def target_name(self) -> pulumi.Output[Optional[builtins.str]]:
        """
        The name of the target (S3-compatible endpoint). Mutually exclusive with remote_name. Changing this forces a new resource.
        """
        return pulumi.get(self, "target_name")

