# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['QuotaUserArgs', 'QuotaUser']

@pulumi.input_type
class QuotaUserArgs:
    def __init__(__self__, *,
                 file_system_name: pulumi.Input[builtins.str],
                 quota: pulumi.Input[builtins.int],
                 uid: pulumi.Input[builtins.str]):
        """
        The set of arguments for constructing a QuotaUser resource.
        :param pulumi.Input[builtins.str] file_system_name: Name of the file system this quota applies to. Changing this forces a new resource.
        :param pulumi.Input[builtins.int] quota: Quota limit in bytes.
        :param pulumi.Input[builtins.str] uid: User ID (UID) the quota applies to. Changing this forces a new resource.
        """
        pulumi.set(__self__, "file_system_name", file_system_name)
        pulumi.set(__self__, "quota", quota)
        pulumi.set(__self__, "uid", uid)

    @property
    @pulumi.getter(name="fileSystemName")
    def file_system_name(self) -> pulumi.Input[builtins.str]:
        """
        Name of the file system this quota applies to. Changing this forces a new resource.
        """
        return pulumi.get(self, "file_system_name")

    @file_system_name.setter
    def file_system_name(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "file_system_name", value)

    @property
    @pulumi.getter
    def quota(self) -> pulumi.Input[builtins.int]:
        """
        Quota limit in bytes.
        """
        return pulumi.get(self, "quota")

    @quota.setter
    def quota(self, value: pulumi.Input[builtins.int]):
        pulumi.set(self, "quota", value)

    @property
    @pulumi.getter
    def uid(self) -> pulumi.Input[builtins.str]:
        """
        User ID (UID) the quota applies to. Changing this forces a new resource.
        """
        return pulumi.get(self, "uid")

    @uid.setter
    def uid(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "uid", value)


@pulumi.input_type
class _QuotaUserState:
    def __init__(__self__, *,
                 file_system_name: Optional[pulumi.Input[builtins.str]] = None,
                 quota: Optional[pulumi.Input[builtins.int]] = None,
                 uid: Optional[pulumi.Input[builtins.str]] = None,
                 usage: Optional[pulumi.Input[builtins.int]] = None):
        """
        Input properties used for looking up and filtering QuotaUser resources.
        :param pulumi.Input[builtins.str] file_system_name: Name of the file system this quota applies to. Changing this forces a new resource.
        :param pulumi.Input[builtins.int] quota: Quota limit in bytes.
        :param pulumi.Input[builtins.str] uid: User ID (UID) the quota applies to. Changing this forces a new resource.
        :param pulumi.Input[builtins.int] usage: Current usage in bytes (read-only, API-managed).
        """
        if file_system_name is not None:
            pulumi.set(__self__, "file_system_name", file_system_name)
        if quota is not None:
            pulumi.set(__self__, "quota", quota)
        if uid is not None:
            pulumi.set(__self__, "uid", uid)
        if usage is not None:
            pulumi.set(__self__, "usage", usage)

    @property
    @pulumi.getter(name="fileSystemName")
    def file_system_name(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        Name of the file system this quota applies to. Changing this forces a new resource.
        """
        return pulumi.get(self, "file_system_name")

    @file_system_name.setter
    def file_system_name(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "file_system_name", value)

    @property
    @pulumi.getter
    def quota(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Quota limit in bytes.
        """
        return pulumi.get(self, "quota")

    @quota.setter
    def quota(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "quota", value)

    @property
    @pulumi.getter
    def uid(self) -> Optional[pulumi.Input[builtins.str]]:
        """
        User ID (UID) the quota applies to. Changing this forces a new resource.
        """
        return pulumi.get(self, "uid")

    @uid.setter
    def uid(self, value: Optional[pulumi.Input[builtins.str]]):
        pulumi.set(self, "uid", value)

    @property
    @pulumi.getter
    def usage(self) -> Optional[pulumi.Input[builtins.int]]:
        """
        Current usage in bytes (read-only, API-managed).
        """
        return pulumi.get(self, "usage")

    @usage.setter
    def usage(self, value: Optional[pulumi.Input[builtins.int]]):
        pulumi.set(self, "usage", value)


class QuotaUser(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 file_system_name: Optional[pulumi.Input[builtins.str]] = None,
                 quota: Optional[pulumi.Input[builtins.int]] = None,
                 uid: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        """
        Create a QuotaUser resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] file_system_name: Name of the file system this quota applies to. Changing this forces a new resource.
        :param pulumi.Input[builtins.int] quota: Quota limit in bytes.
        :param pulumi.Input[builtins.str] uid: User ID (UID) the quota applies to. Changing this forces a new resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: QuotaUserArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a QuotaUser resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param QuotaUserArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(QuotaUserArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 file_system_name: Optional[pulumi.Input[builtins.str]] = None,
                 quota: Optional[pulumi.Input[builtins.int]] = None,
                 uid: Optional[pulumi.Input[builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = QuotaUserArgs.__new__(QuotaUserArgs)

            if file_system_name is None and not opts.urn:
                raise TypeError("Missing required property 'file_system_name'")
            __props__.__dict__["file_system_name"] = file_system_name
            if quota is None and not opts.urn:
                raise TypeError("Missing required property 'quota'")
            __props__.__dict__["quota"] = quota
            if uid is None and not opts.urn:
                raise TypeError("Missing required property 'uid'")
            __props__.__dict__["uid"] = uid
            __props__.__dict__["usage"] = None
        super(QuotaUser, __self__).__init__(
            'flashblade:index/quotaUser:QuotaUser',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            file_system_name: Optional[pulumi.Input[builtins.str]] = None,
            quota: Optional[pulumi.Input[builtins.int]] = None,
            uid: Optional[pulumi.Input[builtins.str]] = None,
            usage: Optional[pulumi.Input[builtins.int]] = None) -> 'QuotaUser':
        """
        Get an existing QuotaUser resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[builtins.str] file_system_name: Name of the file system this quota applies to. Changing this forces a new resource.
        :param pulumi.Input[builtins.int] quota: Quota limit in bytes.
        :param pulumi.Input[builtins.str] uid: User ID (UID) the quota applies to. Changing this forces a new resource.
        :param pulumi.Input[builtins.int] usage: Current usage in bytes (read-only, API-managed).
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _QuotaUserState.__new__(_QuotaUserState)

        __props__.__dict__["file_system_name"] = file_system_name
        __props__.__dict__["quota"] = quota
        __props__.__dict__["uid"] = uid
        __props__.__dict__["usage"] = usage
        return QuotaUser(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="fileSystemName")
    def file_system_name(self) -> pulumi.Output[builtins.str]:
        """
        Name of the file system this quota applies to. Changing this forces a new resource.
        """
        return pulumi.get(self, "file_system_name")

    @property
    @pulumi.getter
    def quota(self) -> pulumi.Output[builtins.int]:
        """
        Quota limit in bytes.
        """
        return pulumi.get(self, "quota")

    @property
    @pulumi.getter
    def uid(self) -> pulumi.Output[builtins.str]:
        """
        User ID (UID) the quota applies to. Changing this forces a new resource.
        """
        return pulumi.get(self, "uid")

    @property
    @pulumi.getter
    def usage(self) -> pulumi.Output[builtins.int]:
        """
        Current usage in bytes (read-only, API-managed).
        """
        return pulumi.get(self, "usage")

