// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ArrayConnection struct {
	pulumi.CustomResourceState

	// Connection key of the remote array. Required when creating a new connection. Write-only: not returned by GET. Changing this forces a new resource.
	ConnectionKey pulumi.StringPtrOutput `pulumi:"connectionKey"`
	// Whether data is encrypted in transit.
	Encrypted pulumi.BoolOutput `pulumi:"encrypted"`
	// Management IP or hostname of the remote array. Required when creating a new connection, computed for imported/passive-side connections.
	ManagementAddress pulumi.StringOutput `pulumi:"managementAddress"`
	// Operating system of the remote array.
	Os pulumi.StringOutput `pulumi:"os"`
	// The name of the remote array. Used as the import identifier. Changing this forces a new resource.
	RemoteName pulumi.StringOutput `pulumi:"remoteName"`
	// Replication IP addresses or FQDNs.
	ReplicationAddresses pulumi.StringArrayOutput `pulumi:"replicationAddresses"`
	// Connection status (connected, connecting, etc.).
	Status pulumi.StringOutput `pulumi:"status"`
	// Bandwidth throttle configuration for the array connection.
	Throttle ArrayConnectionThrottleOutput `pulumi:"throttle"`
	// Connection type (async-replication, etc.).
	Type pulumi.StringOutput `pulumi:"type"`
	// Version of the remote array.
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewArrayConnection registers a new resource with the given unique name, arguments, and options.
func NewArrayConnection(ctx *pulumi.Context,
	name string, args *ArrayConnectionArgs, opts ...pulumi.ResourceOption) (*ArrayConnection, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.RemoteName == nil {
		return nil, errors.New("invalid value for required argument 'RemoteName'")
	}
	if args.ConnectionKey != nil {
		args.ConnectionKey = pulumi.ToSecret(args.ConnectionKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"connectionKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ArrayConnection
	err := ctx.RegisterResource("mica:index/arrayConnection:ArrayConnection", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetArrayConnection gets an existing ArrayConnection resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetArrayConnection(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ArrayConnectionState, opts ...pulumi.ResourceOption) (*ArrayConnection, error) {
	var resource ArrayConnection
	err := ctx.ReadResource("mica:index/arrayConnection:ArrayConnection", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ArrayConnection resources.
type arrayConnectionState struct {
	// Connection key of the remote array. Required when creating a new connection. Write-only: not returned by GET. Changing this forces a new resource.
	ConnectionKey *string `pulumi:"connectionKey"`
	// Whether data is encrypted in transit.
	Encrypted *bool `pulumi:"encrypted"`
	// Management IP or hostname of the remote array. Required when creating a new connection, computed for imported/passive-side connections.
	ManagementAddress *string `pulumi:"managementAddress"`
	// Operating system of the remote array.
	Os *string `pulumi:"os"`
	// The name of the remote array. Used as the import identifier. Changing this forces a new resource.
	RemoteName *string `pulumi:"remoteName"`
	// Replication IP addresses or FQDNs.
	ReplicationAddresses []string `pulumi:"replicationAddresses"`
	// Connection status (connected, connecting, etc.).
	Status *string `pulumi:"status"`
	// Bandwidth throttle configuration for the array connection.
	Throttle *ArrayConnectionThrottle `pulumi:"throttle"`
	// Connection type (async-replication, etc.).
	Type *string `pulumi:"type"`
	// Version of the remote array.
	Version *string `pulumi:"version"`
}

type ArrayConnectionState struct {
	// Connection key of the remote array. Required when creating a new connection. Write-only: not returned by GET. Changing this forces a new resource.
	ConnectionKey pulumi.StringPtrInput
	// Whether data is encrypted in transit.
	Encrypted pulumi.BoolPtrInput
	// Management IP or hostname of the remote array. Required when creating a new connection, computed for imported/passive-side connections.
	ManagementAddress pulumi.StringPtrInput
	// Operating system of the remote array.
	Os pulumi.StringPtrInput
	// The name of the remote array. Used as the import identifier. Changing this forces a new resource.
	RemoteName pulumi.StringPtrInput
	// Replication IP addresses or FQDNs.
	ReplicationAddresses pulumi.StringArrayInput
	// Connection status (connected, connecting, etc.).
	Status pulumi.StringPtrInput
	// Bandwidth throttle configuration for the array connection.
	Throttle ArrayConnectionThrottlePtrInput
	// Connection type (async-replication, etc.).
	Type pulumi.StringPtrInput
	// Version of the remote array.
	Version pulumi.StringPtrInput
}

func (ArrayConnectionState) ElementType() reflect.Type {
	return reflect.TypeOf((*arrayConnectionState)(nil)).Elem()
}

type arrayConnectionArgs struct {
	// Connection key of the remote array. Required when creating a new connection. Write-only: not returned by GET. Changing this forces a new resource.
	ConnectionKey *string `pulumi:"connectionKey"`
	// Whether data is encrypted in transit.
	Encrypted *bool `pulumi:"encrypted"`
	// Management IP or hostname of the remote array. Required when creating a new connection, computed for imported/passive-side connections.
	ManagementAddress *string `pulumi:"managementAddress"`
	// The name of the remote array. Used as the import identifier. Changing this forces a new resource.
	RemoteName string `pulumi:"remoteName"`
	// Replication IP addresses or FQDNs.
	ReplicationAddresses []string `pulumi:"replicationAddresses"`
	// Bandwidth throttle configuration for the array connection.
	Throttle *ArrayConnectionThrottle `pulumi:"throttle"`
}

// The set of arguments for constructing a ArrayConnection resource.
type ArrayConnectionArgs struct {
	// Connection key of the remote array. Required when creating a new connection. Write-only: not returned by GET. Changing this forces a new resource.
	ConnectionKey pulumi.StringPtrInput
	// Whether data is encrypted in transit.
	Encrypted pulumi.BoolPtrInput
	// Management IP or hostname of the remote array. Required when creating a new connection, computed for imported/passive-side connections.
	ManagementAddress pulumi.StringPtrInput
	// The name of the remote array. Used as the import identifier. Changing this forces a new resource.
	RemoteName pulumi.StringInput
	// Replication IP addresses or FQDNs.
	ReplicationAddresses pulumi.StringArrayInput
	// Bandwidth throttle configuration for the array connection.
	Throttle ArrayConnectionThrottlePtrInput
}

func (ArrayConnectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*arrayConnectionArgs)(nil)).Elem()
}

type ArrayConnectionInput interface {
	pulumi.Input

	ToArrayConnectionOutput() ArrayConnectionOutput
	ToArrayConnectionOutputWithContext(ctx context.Context) ArrayConnectionOutput
}

func (*ArrayConnection) ElementType() reflect.Type {
	return reflect.TypeOf((**ArrayConnection)(nil)).Elem()
}

func (i *ArrayConnection) ToArrayConnectionOutput() ArrayConnectionOutput {
	return i.ToArrayConnectionOutputWithContext(context.Background())
}

func (i *ArrayConnection) ToArrayConnectionOutputWithContext(ctx context.Context) ArrayConnectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ArrayConnectionOutput)
}

type ArrayConnectionOutput struct{ *pulumi.OutputState }

func (ArrayConnectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ArrayConnection)(nil)).Elem()
}

func (o ArrayConnectionOutput) ToArrayConnectionOutput() ArrayConnectionOutput {
	return o
}

func (o ArrayConnectionOutput) ToArrayConnectionOutputWithContext(ctx context.Context) ArrayConnectionOutput {
	return o
}

// Connection key of the remote array. Required when creating a new connection. Write-only: not returned by GET. Changing this forces a new resource.
func (o ArrayConnectionOutput) ConnectionKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ArrayConnection) pulumi.StringPtrOutput { return v.ConnectionKey }).(pulumi.StringPtrOutput)
}

// Whether data is encrypted in transit.
func (o ArrayConnectionOutput) Encrypted() pulumi.BoolOutput {
	return o.ApplyT(func(v *ArrayConnection) pulumi.BoolOutput { return v.Encrypted }).(pulumi.BoolOutput)
}

// Management IP or hostname of the remote array. Required when creating a new connection, computed for imported/passive-side connections.
func (o ArrayConnectionOutput) ManagementAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *ArrayConnection) pulumi.StringOutput { return v.ManagementAddress }).(pulumi.StringOutput)
}

// Operating system of the remote array.
func (o ArrayConnectionOutput) Os() pulumi.StringOutput {
	return o.ApplyT(func(v *ArrayConnection) pulumi.StringOutput { return v.Os }).(pulumi.StringOutput)
}

// The name of the remote array. Used as the import identifier. Changing this forces a new resource.
func (o ArrayConnectionOutput) RemoteName() pulumi.StringOutput {
	return o.ApplyT(func(v *ArrayConnection) pulumi.StringOutput { return v.RemoteName }).(pulumi.StringOutput)
}

// Replication IP addresses or FQDNs.
func (o ArrayConnectionOutput) ReplicationAddresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ArrayConnection) pulumi.StringArrayOutput { return v.ReplicationAddresses }).(pulumi.StringArrayOutput)
}

// Connection status (connected, connecting, etc.).
func (o ArrayConnectionOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *ArrayConnection) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Bandwidth throttle configuration for the array connection.
func (o ArrayConnectionOutput) Throttle() ArrayConnectionThrottleOutput {
	return o.ApplyT(func(v *ArrayConnection) ArrayConnectionThrottleOutput { return v.Throttle }).(ArrayConnectionThrottleOutput)
}

// Connection type (async-replication, etc.).
func (o ArrayConnectionOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *ArrayConnection) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// Version of the remote array.
func (o ArrayConnectionOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *ArrayConnection) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ArrayConnectionInput)(nil)).Elem(), &ArrayConnection{})
	pulumi.RegisterOutputType(ArrayConnectionOutput{})
}
