// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ArraySmtp struct {
	pulumi.CustomResourceState

	// Set of alert watcher email recipients.
	AlertWatchers ArraySmtpAlertWatcherArrayOutput `pulumi:"alertWatchers"`
	// SMTP encryption mode: 'none', 'tls', or 'starttls'.
	EncryptionMode pulumi.StringOutput `pulumi:"encryptionMode"`
	// Hostname or IP address of the SMTP relay server.
	RelayHost pulumi.StringOutput `pulumi:"relayHost"`
	// Domain appended to the sender email address.
	SenderDomain pulumi.StringOutput `pulumi:"senderDomain"`
}

// NewArraySmtp registers a new resource with the given unique name, arguments, and options.
func NewArraySmtp(ctx *pulumi.Context,
	name string, args *ArraySmtpArgs, opts ...pulumi.ResourceOption) (*ArraySmtp, error) {
	if args == nil {
		args = &ArraySmtpArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ArraySmtp
	err := ctx.RegisterResource("mica:index/arraySmtp:ArraySmtp", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetArraySmtp gets an existing ArraySmtp resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetArraySmtp(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ArraySmtpState, opts ...pulumi.ResourceOption) (*ArraySmtp, error) {
	var resource ArraySmtp
	err := ctx.ReadResource("mica:index/arraySmtp:ArraySmtp", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ArraySmtp resources.
type arraySmtpState struct {
	// Set of alert watcher email recipients.
	AlertWatchers []ArraySmtpAlertWatcher `pulumi:"alertWatchers"`
	// SMTP encryption mode: 'none', 'tls', or 'starttls'.
	EncryptionMode *string `pulumi:"encryptionMode"`
	// Hostname or IP address of the SMTP relay server.
	RelayHost *string `pulumi:"relayHost"`
	// Domain appended to the sender email address.
	SenderDomain *string `pulumi:"senderDomain"`
}

type ArraySmtpState struct {
	// Set of alert watcher email recipients.
	AlertWatchers ArraySmtpAlertWatcherArrayInput
	// SMTP encryption mode: 'none', 'tls', or 'starttls'.
	EncryptionMode pulumi.StringPtrInput
	// Hostname or IP address of the SMTP relay server.
	RelayHost pulumi.StringPtrInput
	// Domain appended to the sender email address.
	SenderDomain pulumi.StringPtrInput
}

func (ArraySmtpState) ElementType() reflect.Type {
	return reflect.TypeOf((*arraySmtpState)(nil)).Elem()
}

type arraySmtpArgs struct {
	// Set of alert watcher email recipients.
	AlertWatchers []ArraySmtpAlertWatcher `pulumi:"alertWatchers"`
	// SMTP encryption mode: 'none', 'tls', or 'starttls'.
	EncryptionMode *string `pulumi:"encryptionMode"`
	// Hostname or IP address of the SMTP relay server.
	RelayHost *string `pulumi:"relayHost"`
	// Domain appended to the sender email address.
	SenderDomain *string `pulumi:"senderDomain"`
}

// The set of arguments for constructing a ArraySmtp resource.
type ArraySmtpArgs struct {
	// Set of alert watcher email recipients.
	AlertWatchers ArraySmtpAlertWatcherArrayInput
	// SMTP encryption mode: 'none', 'tls', or 'starttls'.
	EncryptionMode pulumi.StringPtrInput
	// Hostname or IP address of the SMTP relay server.
	RelayHost pulumi.StringPtrInput
	// Domain appended to the sender email address.
	SenderDomain pulumi.StringPtrInput
}

func (ArraySmtpArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*arraySmtpArgs)(nil)).Elem()
}

type ArraySmtpInput interface {
	pulumi.Input

	ToArraySmtpOutput() ArraySmtpOutput
	ToArraySmtpOutputWithContext(ctx context.Context) ArraySmtpOutput
}

func (*ArraySmtp) ElementType() reflect.Type {
	return reflect.TypeOf((**ArraySmtp)(nil)).Elem()
}

func (i *ArraySmtp) ToArraySmtpOutput() ArraySmtpOutput {
	return i.ToArraySmtpOutputWithContext(context.Background())
}

func (i *ArraySmtp) ToArraySmtpOutputWithContext(ctx context.Context) ArraySmtpOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ArraySmtpOutput)
}

type ArraySmtpOutput struct{ *pulumi.OutputState }

func (ArraySmtpOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ArraySmtp)(nil)).Elem()
}

func (o ArraySmtpOutput) ToArraySmtpOutput() ArraySmtpOutput {
	return o
}

func (o ArraySmtpOutput) ToArraySmtpOutputWithContext(ctx context.Context) ArraySmtpOutput {
	return o
}

// Set of alert watcher email recipients.
func (o ArraySmtpOutput) AlertWatchers() ArraySmtpAlertWatcherArrayOutput {
	return o.ApplyT(func(v *ArraySmtp) ArraySmtpAlertWatcherArrayOutput { return v.AlertWatchers }).(ArraySmtpAlertWatcherArrayOutput)
}

// SMTP encryption mode: 'none', 'tls', or 'starttls'.
func (o ArraySmtpOutput) EncryptionMode() pulumi.StringOutput {
	return o.ApplyT(func(v *ArraySmtp) pulumi.StringOutput { return v.EncryptionMode }).(pulumi.StringOutput)
}

// Hostname or IP address of the SMTP relay server.
func (o ArraySmtpOutput) RelayHost() pulumi.StringOutput {
	return o.ApplyT(func(v *ArraySmtp) pulumi.StringOutput { return v.RelayHost }).(pulumi.StringOutput)
}

// Domain appended to the sender email address.
func (o ArraySmtpOutput) SenderDomain() pulumi.StringOutput {
	return o.ApplyT(func(v *ArraySmtp) pulumi.StringOutput { return v.SenderDomain }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ArraySmtpInput)(nil)).Elem(), &ArraySmtp{})
	pulumi.RegisterOutputType(ArraySmtpOutput{})
}
