// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ArrayNtp struct {
	pulumi.CustomResourceState

	// List of NTP server hostnames or IP addresses.
	NtpServers pulumi.StringArrayOutput `pulumi:"ntpServers"`
}

// NewArrayNtp registers a new resource with the given unique name, arguments, and options.
func NewArrayNtp(ctx *pulumi.Context,
	name string, args *ArrayNtpArgs, opts ...pulumi.ResourceOption) (*ArrayNtp, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.NtpServers == nil {
		return nil, errors.New("invalid value for required argument 'NtpServers'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ArrayNtp
	err := ctx.RegisterResource("mica:index/arrayNtp:ArrayNtp", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetArrayNtp gets an existing ArrayNtp resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetArrayNtp(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ArrayNtpState, opts ...pulumi.ResourceOption) (*ArrayNtp, error) {
	var resource ArrayNtp
	err := ctx.ReadResource("mica:index/arrayNtp:ArrayNtp", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ArrayNtp resources.
type arrayNtpState struct {
	// List of NTP server hostnames or IP addresses.
	NtpServers []string `pulumi:"ntpServers"`
}

type ArrayNtpState struct {
	// List of NTP server hostnames or IP addresses.
	NtpServers pulumi.StringArrayInput
}

func (ArrayNtpState) ElementType() reflect.Type {
	return reflect.TypeOf((*arrayNtpState)(nil)).Elem()
}

type arrayNtpArgs struct {
	// List of NTP server hostnames or IP addresses.
	NtpServers []string `pulumi:"ntpServers"`
}

// The set of arguments for constructing a ArrayNtp resource.
type ArrayNtpArgs struct {
	// List of NTP server hostnames or IP addresses.
	NtpServers pulumi.StringArrayInput
}

func (ArrayNtpArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*arrayNtpArgs)(nil)).Elem()
}

type ArrayNtpInput interface {
	pulumi.Input

	ToArrayNtpOutput() ArrayNtpOutput
	ToArrayNtpOutputWithContext(ctx context.Context) ArrayNtpOutput
}

func (*ArrayNtp) ElementType() reflect.Type {
	return reflect.TypeOf((**ArrayNtp)(nil)).Elem()
}

func (i *ArrayNtp) ToArrayNtpOutput() ArrayNtpOutput {
	return i.ToArrayNtpOutputWithContext(context.Background())
}

func (i *ArrayNtp) ToArrayNtpOutputWithContext(ctx context.Context) ArrayNtpOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ArrayNtpOutput)
}

type ArrayNtpOutput struct{ *pulumi.OutputState }

func (ArrayNtpOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ArrayNtp)(nil)).Elem()
}

func (o ArrayNtpOutput) ToArrayNtpOutput() ArrayNtpOutput {
	return o
}

func (o ArrayNtpOutput) ToArrayNtpOutputWithContext(ctx context.Context) ArrayNtpOutput {
	return o
}

// List of NTP server hostnames or IP addresses.
func (o ArrayNtpOutput) NtpServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ArrayNtp) pulumi.StringArrayOutput { return v.NtpServers }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ArrayNtpInput)(nil)).Elem(), &ArrayNtp{})
	pulumi.RegisterOutputType(ArrayNtpOutput{})
}
