// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNfsExportPolicy(ctx *pulumi.Context, args *LookupNfsExportPolicyArgs, opts ...pulumi.InvokeOption) (*LookupNfsExportPolicyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNfsExportPolicyResult
	err := ctx.Invoke("mica:index/getNfsExportPolicy:getNfsExportPolicy", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNfsExportPolicy.
type LookupNfsExportPolicyArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getNfsExportPolicy.
type LookupNfsExportPolicyResult struct {
	Enabled    bool   `pulumi:"enabled"`
	Id         string `pulumi:"id"`
	IsLocal    bool   `pulumi:"isLocal"`
	Name       string `pulumi:"name"`
	PolicyType string `pulumi:"policyType"`
	Version    string `pulumi:"version"`
}

func LookupNfsExportPolicyOutput(ctx *pulumi.Context, args LookupNfsExportPolicyOutputArgs, opts ...pulumi.InvokeOption) LookupNfsExportPolicyResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNfsExportPolicyResultOutput, error) {
			args := v.(LookupNfsExportPolicyArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mica:index/getNfsExportPolicy:getNfsExportPolicy", args, LookupNfsExportPolicyResultOutput{}, options).(LookupNfsExportPolicyResultOutput), nil
		}).(LookupNfsExportPolicyResultOutput)
}

// A collection of arguments for invoking getNfsExportPolicy.
type LookupNfsExportPolicyOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupNfsExportPolicyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNfsExportPolicyArgs)(nil)).Elem()
}

// A collection of values returned by getNfsExportPolicy.
type LookupNfsExportPolicyResultOutput struct{ *pulumi.OutputState }

func (LookupNfsExportPolicyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNfsExportPolicyResult)(nil)).Elem()
}

func (o LookupNfsExportPolicyResultOutput) ToLookupNfsExportPolicyResultOutput() LookupNfsExportPolicyResultOutput {
	return o
}

func (o LookupNfsExportPolicyResultOutput) ToLookupNfsExportPolicyResultOutputWithContext(ctx context.Context) LookupNfsExportPolicyResultOutput {
	return o
}

func (o LookupNfsExportPolicyResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNfsExportPolicyResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupNfsExportPolicyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNfsExportPolicyResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNfsExportPolicyResultOutput) IsLocal() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNfsExportPolicyResult) bool { return v.IsLocal }).(pulumi.BoolOutput)
}

func (o LookupNfsExportPolicyResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNfsExportPolicyResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNfsExportPolicyResultOutput) PolicyType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNfsExportPolicyResult) string { return v.PolicyType }).(pulumi.StringOutput)
}

func (o LookupNfsExportPolicyResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNfsExportPolicyResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNfsExportPolicyResultOutput{})
}
