// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupObjectStoreUser(ctx *pulumi.Context, args *LookupObjectStoreUserArgs, opts ...pulumi.InvokeOption) (*LookupObjectStoreUserResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupObjectStoreUserResult
	err := ctx.Invoke("mica:index/getObjectStoreUser:getObjectStoreUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getObjectStoreUser.
type LookupObjectStoreUserArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getObjectStoreUser.
type LookupObjectStoreUserResult struct {
	FullAccess bool   `pulumi:"fullAccess"`
	Id         string `pulumi:"id"`
	Name       string `pulumi:"name"`
}

func LookupObjectStoreUserOutput(ctx *pulumi.Context, args LookupObjectStoreUserOutputArgs, opts ...pulumi.InvokeOption) LookupObjectStoreUserResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupObjectStoreUserResultOutput, error) {
			args := v.(LookupObjectStoreUserArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mica:index/getObjectStoreUser:getObjectStoreUser", args, LookupObjectStoreUserResultOutput{}, options).(LookupObjectStoreUserResultOutput), nil
		}).(LookupObjectStoreUserResultOutput)
}

// A collection of arguments for invoking getObjectStoreUser.
type LookupObjectStoreUserOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupObjectStoreUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupObjectStoreUserArgs)(nil)).Elem()
}

// A collection of values returned by getObjectStoreUser.
type LookupObjectStoreUserResultOutput struct{ *pulumi.OutputState }

func (LookupObjectStoreUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupObjectStoreUserResult)(nil)).Elem()
}

func (o LookupObjectStoreUserResultOutput) ToLookupObjectStoreUserResultOutput() LookupObjectStoreUserResultOutput {
	return o
}

func (o LookupObjectStoreUserResultOutput) ToLookupObjectStoreUserResultOutputWithContext(ctx context.Context) LookupObjectStoreUserResultOutput {
	return o
}

func (o LookupObjectStoreUserResultOutput) FullAccess() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupObjectStoreUserResult) bool { return v.FullAccess }).(pulumi.BoolOutput)
}

func (o LookupObjectStoreUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStoreUserResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupObjectStoreUserResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStoreUserResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupObjectStoreUserResultOutput{})
}
