// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupObjectStoreAccountExport(ctx *pulumi.Context, args *LookupObjectStoreAccountExportArgs, opts ...pulumi.InvokeOption) (*LookupObjectStoreAccountExportResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupObjectStoreAccountExportResult
	err := ctx.Invoke("mica:index/getObjectStoreAccountExport:getObjectStoreAccountExport", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getObjectStoreAccountExport.
type LookupObjectStoreAccountExportArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getObjectStoreAccountExport.
type LookupObjectStoreAccountExportResult struct {
	AccountName string `pulumi:"accountName"`
	Enabled     bool   `pulumi:"enabled"`
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	PolicyName  string `pulumi:"policyName"`
	ServerName  string `pulumi:"serverName"`
}

func LookupObjectStoreAccountExportOutput(ctx *pulumi.Context, args LookupObjectStoreAccountExportOutputArgs, opts ...pulumi.InvokeOption) LookupObjectStoreAccountExportResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupObjectStoreAccountExportResultOutput, error) {
			args := v.(LookupObjectStoreAccountExportArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mica:index/getObjectStoreAccountExport:getObjectStoreAccountExport", args, LookupObjectStoreAccountExportResultOutput{}, options).(LookupObjectStoreAccountExportResultOutput), nil
		}).(LookupObjectStoreAccountExportResultOutput)
}

// A collection of arguments for invoking getObjectStoreAccountExport.
type LookupObjectStoreAccountExportOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupObjectStoreAccountExportOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupObjectStoreAccountExportArgs)(nil)).Elem()
}

// A collection of values returned by getObjectStoreAccountExport.
type LookupObjectStoreAccountExportResultOutput struct{ *pulumi.OutputState }

func (LookupObjectStoreAccountExportResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupObjectStoreAccountExportResult)(nil)).Elem()
}

func (o LookupObjectStoreAccountExportResultOutput) ToLookupObjectStoreAccountExportResultOutput() LookupObjectStoreAccountExportResultOutput {
	return o
}

func (o LookupObjectStoreAccountExportResultOutput) ToLookupObjectStoreAccountExportResultOutputWithContext(ctx context.Context) LookupObjectStoreAccountExportResultOutput {
	return o
}

func (o LookupObjectStoreAccountExportResultOutput) AccountName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStoreAccountExportResult) string { return v.AccountName }).(pulumi.StringOutput)
}

func (o LookupObjectStoreAccountExportResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupObjectStoreAccountExportResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupObjectStoreAccountExportResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStoreAccountExportResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupObjectStoreAccountExportResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStoreAccountExportResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupObjectStoreAccountExportResultOutput) PolicyName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStoreAccountExportResult) string { return v.PolicyName }).(pulumi.StringOutput)
}

func (o LookupObjectStoreAccountExportResultOutput) ServerName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupObjectStoreAccountExportResult) string { return v.ServerName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupObjectStoreAccountExportResultOutput{})
}
