// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSnapshotPolicy(ctx *pulumi.Context, args *LookupSnapshotPolicyArgs, opts ...pulumi.InvokeOption) (*LookupSnapshotPolicyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSnapshotPolicyResult
	err := ctx.Invoke("mica:index/getSnapshotPolicy:getSnapshotPolicy", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSnapshotPolicy.
type LookupSnapshotPolicyArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getSnapshotPolicy.
type LookupSnapshotPolicyResult struct {
	Enabled       bool   `pulumi:"enabled"`
	Id            string `pulumi:"id"`
	IsLocal       bool   `pulumi:"isLocal"`
	Name          string `pulumi:"name"`
	PolicyType    string `pulumi:"policyType"`
	RetentionLock string `pulumi:"retentionLock"`
}

func LookupSnapshotPolicyOutput(ctx *pulumi.Context, args LookupSnapshotPolicyOutputArgs, opts ...pulumi.InvokeOption) LookupSnapshotPolicyResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSnapshotPolicyResultOutput, error) {
			args := v.(LookupSnapshotPolicyArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mica:index/getSnapshotPolicy:getSnapshotPolicy", args, LookupSnapshotPolicyResultOutput{}, options).(LookupSnapshotPolicyResultOutput), nil
		}).(LookupSnapshotPolicyResultOutput)
}

// A collection of arguments for invoking getSnapshotPolicy.
type LookupSnapshotPolicyOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupSnapshotPolicyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSnapshotPolicyArgs)(nil)).Elem()
}

// A collection of values returned by getSnapshotPolicy.
type LookupSnapshotPolicyResultOutput struct{ *pulumi.OutputState }

func (LookupSnapshotPolicyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSnapshotPolicyResult)(nil)).Elem()
}

func (o LookupSnapshotPolicyResultOutput) ToLookupSnapshotPolicyResultOutput() LookupSnapshotPolicyResultOutput {
	return o
}

func (o LookupSnapshotPolicyResultOutput) ToLookupSnapshotPolicyResultOutputWithContext(ctx context.Context) LookupSnapshotPolicyResultOutput {
	return o
}

func (o LookupSnapshotPolicyResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSnapshotPolicyResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupSnapshotPolicyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSnapshotPolicyResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSnapshotPolicyResultOutput) IsLocal() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSnapshotPolicyResult) bool { return v.IsLocal }).(pulumi.BoolOutput)
}

func (o LookupSnapshotPolicyResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSnapshotPolicyResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSnapshotPolicyResultOutput) PolicyType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSnapshotPolicyResult) string { return v.PolicyType }).(pulumi.StringOutput)
}

func (o LookupSnapshotPolicyResultOutput) RetentionLock() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSnapshotPolicyResult) string { return v.RetentionLock }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSnapshotPolicyResultOutput{})
}
