// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSyslogServer(ctx *pulumi.Context, args *LookupSyslogServerArgs, opts ...pulumi.InvokeOption) (*LookupSyslogServerResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSyslogServerResult
	err := ctx.Invoke("mica:index/getSyslogServer:getSyslogServer", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSyslogServer.
type LookupSyslogServerArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getSyslogServer.
type LookupSyslogServerResult struct {
	Id       string   `pulumi:"id"`
	Name     string   `pulumi:"name"`
	Services []string `pulumi:"services"`
	Sources  []string `pulumi:"sources"`
	Uri      string   `pulumi:"uri"`
}

func LookupSyslogServerOutput(ctx *pulumi.Context, args LookupSyslogServerOutputArgs, opts ...pulumi.InvokeOption) LookupSyslogServerResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSyslogServerResultOutput, error) {
			args := v.(LookupSyslogServerArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mica:index/getSyslogServer:getSyslogServer", args, LookupSyslogServerResultOutput{}, options).(LookupSyslogServerResultOutput), nil
		}).(LookupSyslogServerResultOutput)
}

// A collection of arguments for invoking getSyslogServer.
type LookupSyslogServerOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupSyslogServerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSyslogServerArgs)(nil)).Elem()
}

// A collection of values returned by getSyslogServer.
type LookupSyslogServerResultOutput struct{ *pulumi.OutputState }

func (LookupSyslogServerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSyslogServerResult)(nil)).Elem()
}

func (o LookupSyslogServerResultOutput) ToLookupSyslogServerResultOutput() LookupSyslogServerResultOutput {
	return o
}

func (o LookupSyslogServerResultOutput) ToLookupSyslogServerResultOutputWithContext(ctx context.Context) LookupSyslogServerResultOutput {
	return o
}

func (o LookupSyslogServerResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSyslogServerResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSyslogServerResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSyslogServerResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSyslogServerResultOutput) Services() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSyslogServerResult) []string { return v.Services }).(pulumi.StringArrayOutput)
}

func (o LookupSyslogServerResultOutput) Sources() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSyslogServerResult) []string { return v.Sources }).(pulumi.StringArrayOutput)
}

func (o LookupSyslogServerResultOutput) Uri() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSyslogServerResult) string { return v.Uri }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSyslogServerResultOutput{})
}
