// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupTarget(ctx *pulumi.Context, args *LookupTargetArgs, opts ...pulumi.InvokeOption) (*LookupTargetResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupTargetResult
	err := ctx.Invoke("mica:index/getTarget:getTarget", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTarget.
type LookupTargetArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getTarget.
type LookupTargetResult struct {
	Address            string `pulumi:"address"`
	CaCertificateGroup string `pulumi:"caCertificateGroup"`
	Id                 string `pulumi:"id"`
	Name               string `pulumi:"name"`
	Status             string `pulumi:"status"`
	StatusDetails      string `pulumi:"statusDetails"`
}

func LookupTargetOutput(ctx *pulumi.Context, args LookupTargetOutputArgs, opts ...pulumi.InvokeOption) LookupTargetResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupTargetResultOutput, error) {
			args := v.(LookupTargetArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mica:index/getTarget:getTarget", args, LookupTargetResultOutput{}, options).(LookupTargetResultOutput), nil
		}).(LookupTargetResultOutput)
}

// A collection of arguments for invoking getTarget.
type LookupTargetOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupTargetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTargetArgs)(nil)).Elem()
}

// A collection of values returned by getTarget.
type LookupTargetResultOutput struct{ *pulumi.OutputState }

func (LookupTargetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTargetResult)(nil)).Elem()
}

func (o LookupTargetResultOutput) ToLookupTargetResultOutput() LookupTargetResultOutput {
	return o
}

func (o LookupTargetResultOutput) ToLookupTargetResultOutputWithContext(ctx context.Context) LookupTargetResultOutput {
	return o
}

func (o LookupTargetResultOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTargetResult) string { return v.Address }).(pulumi.StringOutput)
}

func (o LookupTargetResultOutput) CaCertificateGroup() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTargetResult) string { return v.CaCertificateGroup }).(pulumi.StringOutput)
}

func (o LookupTargetResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTargetResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupTargetResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTargetResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupTargetResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTargetResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupTargetResultOutput) StatusDetails() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTargetResult) string { return v.StatusDetails }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTargetResultOutput{})
}
