// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NfsExportPolicy struct {
	pulumi.CustomResourceState

	// If true, the policy is enabled and its rules are enforced.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// If true, the policy is local to this array (not replicated).
	IsLocal pulumi.BoolOutput `pulumi:"isLocal"`
	// The name of the NFS export policy. Can be changed in-place via PATCH (rename).
	Name pulumi.StringOutput `pulumi:"name"`
	// The type of the policy (e.g. 'nfs').
	PolicyType pulumi.StringOutput `pulumi:"policyType"`
	// The version token that changes on each policy update.
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewNfsExportPolicy registers a new resource with the given unique name, arguments, and options.
func NewNfsExportPolicy(ctx *pulumi.Context,
	name string, args *NfsExportPolicyArgs, opts ...pulumi.ResourceOption) (*NfsExportPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NfsExportPolicy
	err := ctx.RegisterResource("mica:index/nfsExportPolicy:NfsExportPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNfsExportPolicy gets an existing NfsExportPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNfsExportPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NfsExportPolicyState, opts ...pulumi.ResourceOption) (*NfsExportPolicy, error) {
	var resource NfsExportPolicy
	err := ctx.ReadResource("mica:index/nfsExportPolicy:NfsExportPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NfsExportPolicy resources.
type nfsExportPolicyState struct {
	// If true, the policy is enabled and its rules are enforced.
	Enabled *bool `pulumi:"enabled"`
	// If true, the policy is local to this array (not replicated).
	IsLocal *bool `pulumi:"isLocal"`
	// The name of the NFS export policy. Can be changed in-place via PATCH (rename).
	Name *string `pulumi:"name"`
	// The type of the policy (e.g. 'nfs').
	PolicyType *string `pulumi:"policyType"`
	// The version token that changes on each policy update.
	Version *string `pulumi:"version"`
}

type NfsExportPolicyState struct {
	// If true, the policy is enabled and its rules are enforced.
	Enabled pulumi.BoolPtrInput
	// If true, the policy is local to this array (not replicated).
	IsLocal pulumi.BoolPtrInput
	// The name of the NFS export policy. Can be changed in-place via PATCH (rename).
	Name pulumi.StringPtrInput
	// The type of the policy (e.g. 'nfs').
	PolicyType pulumi.StringPtrInput
	// The version token that changes on each policy update.
	Version pulumi.StringPtrInput
}

func (NfsExportPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*nfsExportPolicyState)(nil)).Elem()
}

type nfsExportPolicyArgs struct {
	// If true, the policy is enabled and its rules are enforced.
	Enabled *bool `pulumi:"enabled"`
	// The name of the NFS export policy. Can be changed in-place via PATCH (rename).
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a NfsExportPolicy resource.
type NfsExportPolicyArgs struct {
	// If true, the policy is enabled and its rules are enforced.
	Enabled pulumi.BoolPtrInput
	// The name of the NFS export policy. Can be changed in-place via PATCH (rename).
	Name pulumi.StringInput
}

func (NfsExportPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*nfsExportPolicyArgs)(nil)).Elem()
}

type NfsExportPolicyInput interface {
	pulumi.Input

	ToNfsExportPolicyOutput() NfsExportPolicyOutput
	ToNfsExportPolicyOutputWithContext(ctx context.Context) NfsExportPolicyOutput
}

func (*NfsExportPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**NfsExportPolicy)(nil)).Elem()
}

func (i *NfsExportPolicy) ToNfsExportPolicyOutput() NfsExportPolicyOutput {
	return i.ToNfsExportPolicyOutputWithContext(context.Background())
}

func (i *NfsExportPolicy) ToNfsExportPolicyOutputWithContext(ctx context.Context) NfsExportPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NfsExportPolicyOutput)
}

type NfsExportPolicyOutput struct{ *pulumi.OutputState }

func (NfsExportPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NfsExportPolicy)(nil)).Elem()
}

func (o NfsExportPolicyOutput) ToNfsExportPolicyOutput() NfsExportPolicyOutput {
	return o
}

func (o NfsExportPolicyOutput) ToNfsExportPolicyOutputWithContext(ctx context.Context) NfsExportPolicyOutput {
	return o
}

// If true, the policy is enabled and its rules are enforced.
func (o NfsExportPolicyOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *NfsExportPolicy) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// If true, the policy is local to this array (not replicated).
func (o NfsExportPolicyOutput) IsLocal() pulumi.BoolOutput {
	return o.ApplyT(func(v *NfsExportPolicy) pulumi.BoolOutput { return v.IsLocal }).(pulumi.BoolOutput)
}

// The name of the NFS export policy. Can be changed in-place via PATCH (rename).
func (o NfsExportPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NfsExportPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The type of the policy (e.g. 'nfs').
func (o NfsExportPolicyOutput) PolicyType() pulumi.StringOutput {
	return o.ApplyT(func(v *NfsExportPolicy) pulumi.StringOutput { return v.PolicyType }).(pulumi.StringOutput)
}

// The version token that changes on each policy update.
func (o NfsExportPolicyOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *NfsExportPolicy) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NfsExportPolicyInput)(nil)).Elem(), &NfsExportPolicy{})
	pulumi.RegisterOutputType(NfsExportPolicyOutput{})
}
