// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Server struct {
	pulumi.CustomResourceState

	// List of export names to cascade-delete when destroying this server. Used only on delete, not stored in API state.
	CascadeDeletes pulumi.StringArrayOutput `pulumi:"cascadeDeletes"`
	// Unix timestamp (milliseconds) when the server was created.
	Created pulumi.IntOutput `pulumi:"created"`
	// List of directory service names associated with this server.
	DirectoryServices pulumi.StringArrayOutput `pulumi:"directoryServices"`
	// List of DNS configuration names associated with this server.
	Dns pulumi.StringArrayOutput `pulumi:"dns"`
	// The name of the server. Changing this forces a new resource.
	Name pulumi.StringOutput `pulumi:"name"`
	// Names of network interfaces (VIPs) attached to this server. Discovered automatically from the array.
	NetworkInterfaces pulumi.StringArrayOutput `pulumi:"networkInterfaces"`
}

// NewServer registers a new resource with the given unique name, arguments, and options.
func NewServer(ctx *pulumi.Context,
	name string, args *ServerArgs, opts ...pulumi.ResourceOption) (*Server, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Server
	err := ctx.RegisterResource("mica:index/server:Server", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServer gets an existing Server resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServer(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServerState, opts ...pulumi.ResourceOption) (*Server, error) {
	var resource Server
	err := ctx.ReadResource("mica:index/server:Server", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Server resources.
type serverState struct {
	// List of export names to cascade-delete when destroying this server. Used only on delete, not stored in API state.
	CascadeDeletes []string `pulumi:"cascadeDeletes"`
	// Unix timestamp (milliseconds) when the server was created.
	Created *int `pulumi:"created"`
	// List of directory service names associated with this server.
	DirectoryServices []string `pulumi:"directoryServices"`
	// List of DNS configuration names associated with this server.
	Dns []string `pulumi:"dns"`
	// The name of the server. Changing this forces a new resource.
	Name *string `pulumi:"name"`
	// Names of network interfaces (VIPs) attached to this server. Discovered automatically from the array.
	NetworkInterfaces []string `pulumi:"networkInterfaces"`
}

type ServerState struct {
	// List of export names to cascade-delete when destroying this server. Used only on delete, not stored in API state.
	CascadeDeletes pulumi.StringArrayInput
	// Unix timestamp (milliseconds) when the server was created.
	Created pulumi.IntPtrInput
	// List of directory service names associated with this server.
	DirectoryServices pulumi.StringArrayInput
	// List of DNS configuration names associated with this server.
	Dns pulumi.StringArrayInput
	// The name of the server. Changing this forces a new resource.
	Name pulumi.StringPtrInput
	// Names of network interfaces (VIPs) attached to this server. Discovered automatically from the array.
	NetworkInterfaces pulumi.StringArrayInput
}

func (ServerState) ElementType() reflect.Type {
	return reflect.TypeOf((*serverState)(nil)).Elem()
}

type serverArgs struct {
	// List of export names to cascade-delete when destroying this server. Used only on delete, not stored in API state.
	CascadeDeletes []string `pulumi:"cascadeDeletes"`
	// List of DNS configuration names associated with this server.
	Dns []string `pulumi:"dns"`
	// The name of the server. Changing this forces a new resource.
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a Server resource.
type ServerArgs struct {
	// List of export names to cascade-delete when destroying this server. Used only on delete, not stored in API state.
	CascadeDeletes pulumi.StringArrayInput
	// List of DNS configuration names associated with this server.
	Dns pulumi.StringArrayInput
	// The name of the server. Changing this forces a new resource.
	Name pulumi.StringInput
}

func (ServerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serverArgs)(nil)).Elem()
}

type ServerInput interface {
	pulumi.Input

	ToServerOutput() ServerOutput
	ToServerOutputWithContext(ctx context.Context) ServerOutput
}

func (*Server) ElementType() reflect.Type {
	return reflect.TypeOf((**Server)(nil)).Elem()
}

func (i *Server) ToServerOutput() ServerOutput {
	return i.ToServerOutputWithContext(context.Background())
}

func (i *Server) ToServerOutputWithContext(ctx context.Context) ServerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerOutput)
}

type ServerOutput struct{ *pulumi.OutputState }

func (ServerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Server)(nil)).Elem()
}

func (o ServerOutput) ToServerOutput() ServerOutput {
	return o
}

func (o ServerOutput) ToServerOutputWithContext(ctx context.Context) ServerOutput {
	return o
}

// List of export names to cascade-delete when destroying this server. Used only on delete, not stored in API state.
func (o ServerOutput) CascadeDeletes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Server) pulumi.StringArrayOutput { return v.CascadeDeletes }).(pulumi.StringArrayOutput)
}

// Unix timestamp (milliseconds) when the server was created.
func (o ServerOutput) Created() pulumi.IntOutput {
	return o.ApplyT(func(v *Server) pulumi.IntOutput { return v.Created }).(pulumi.IntOutput)
}

// List of directory service names associated with this server.
func (o ServerOutput) DirectoryServices() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Server) pulumi.StringArrayOutput { return v.DirectoryServices }).(pulumi.StringArrayOutput)
}

// List of DNS configuration names associated with this server.
func (o ServerOutput) Dns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Server) pulumi.StringArrayOutput { return v.Dns }).(pulumi.StringArrayOutput)
}

// The name of the server. Changing this forces a new resource.
func (o ServerOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Server) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Names of network interfaces (VIPs) attached to this server. Discovered automatically from the array.
func (o ServerOutput) NetworkInterfaces() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Server) pulumi.StringArrayOutput { return v.NetworkInterfaces }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServerInput)(nil)).Elem(), &Server{})
	pulumi.RegisterOutputType(ServerOutput{})
}
