// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SnapshotPolicy struct {
	pulumi.CustomResourceState

	// If true, the policy is enabled and its rules are enforced.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// If true, the policy is local to this array (not replicated).
	IsLocal pulumi.BoolOutput `pulumi:"isLocal"`
	// The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
	Name pulumi.StringOutput `pulumi:"name"`
	// The type of the policy (e.g. 'snapshot').
	PolicyType pulumi.StringOutput `pulumi:"policyType"`
	// The retention lock mode of the policy (e.g. 'none', 'ratcheted').
	RetentionLock pulumi.StringOutput `pulumi:"retentionLock"`
}

// NewSnapshotPolicy registers a new resource with the given unique name, arguments, and options.
func NewSnapshotPolicy(ctx *pulumi.Context,
	name string, args *SnapshotPolicyArgs, opts ...pulumi.ResourceOption) (*SnapshotPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SnapshotPolicy
	err := ctx.RegisterResource("mica:index/snapshotPolicy:SnapshotPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSnapshotPolicy gets an existing SnapshotPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSnapshotPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SnapshotPolicyState, opts ...pulumi.ResourceOption) (*SnapshotPolicy, error) {
	var resource SnapshotPolicy
	err := ctx.ReadResource("mica:index/snapshotPolicy:SnapshotPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SnapshotPolicy resources.
type snapshotPolicyState struct {
	// If true, the policy is enabled and its rules are enforced.
	Enabled *bool `pulumi:"enabled"`
	// If true, the policy is local to this array (not replicated).
	IsLocal *bool `pulumi:"isLocal"`
	// The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
	Name *string `pulumi:"name"`
	// The type of the policy (e.g. 'snapshot').
	PolicyType *string `pulumi:"policyType"`
	// The retention lock mode of the policy (e.g. 'none', 'ratcheted').
	RetentionLock *string `pulumi:"retentionLock"`
}

type SnapshotPolicyState struct {
	// If true, the policy is enabled and its rules are enforced.
	Enabled pulumi.BoolPtrInput
	// If true, the policy is local to this array (not replicated).
	IsLocal pulumi.BoolPtrInput
	// The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
	Name pulumi.StringPtrInput
	// The type of the policy (e.g. 'snapshot').
	PolicyType pulumi.StringPtrInput
	// The retention lock mode of the policy (e.g. 'none', 'ratcheted').
	RetentionLock pulumi.StringPtrInput
}

func (SnapshotPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*snapshotPolicyState)(nil)).Elem()
}

type snapshotPolicyArgs struct {
	// If true, the policy is enabled and its rules are enforced.
	Enabled *bool `pulumi:"enabled"`
	// The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a SnapshotPolicy resource.
type SnapshotPolicyArgs struct {
	// If true, the policy is enabled and its rules are enforced.
	Enabled pulumi.BoolPtrInput
	// The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
	Name pulumi.StringInput
}

func (SnapshotPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*snapshotPolicyArgs)(nil)).Elem()
}

type SnapshotPolicyInput interface {
	pulumi.Input

	ToSnapshotPolicyOutput() SnapshotPolicyOutput
	ToSnapshotPolicyOutputWithContext(ctx context.Context) SnapshotPolicyOutput
}

func (*SnapshotPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**SnapshotPolicy)(nil)).Elem()
}

func (i *SnapshotPolicy) ToSnapshotPolicyOutput() SnapshotPolicyOutput {
	return i.ToSnapshotPolicyOutputWithContext(context.Background())
}

func (i *SnapshotPolicy) ToSnapshotPolicyOutputWithContext(ctx context.Context) SnapshotPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SnapshotPolicyOutput)
}

type SnapshotPolicyOutput struct{ *pulumi.OutputState }

func (SnapshotPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SnapshotPolicy)(nil)).Elem()
}

func (o SnapshotPolicyOutput) ToSnapshotPolicyOutput() SnapshotPolicyOutput {
	return o
}

func (o SnapshotPolicyOutput) ToSnapshotPolicyOutputWithContext(ctx context.Context) SnapshotPolicyOutput {
	return o
}

// If true, the policy is enabled and its rules are enforced.
func (o SnapshotPolicyOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *SnapshotPolicy) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// If true, the policy is local to this array (not replicated).
func (o SnapshotPolicyOutput) IsLocal() pulumi.BoolOutput {
	return o.ApplyT(func(v *SnapshotPolicy) pulumi.BoolOutput { return v.IsLocal }).(pulumi.BoolOutput)
}

// The name of the snapshot policy. Changing this forces a new resource. Snapshot policy names cannot be renamed in-place (API limitation).
func (o SnapshotPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SnapshotPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The type of the policy (e.g. 'snapshot').
func (o SnapshotPolicyOutput) PolicyType() pulumi.StringOutput {
	return o.ApplyT(func(v *SnapshotPolicy) pulumi.StringOutput { return v.PolicyType }).(pulumi.StringOutput)
}

// The retention lock mode of the policy (e.g. 'none', 'ratcheted').
func (o SnapshotPolicyOutput) RetentionLock() pulumi.StringOutput {
	return o.ApplyT(func(v *SnapshotPolicy) pulumi.StringOutput { return v.RetentionLock }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SnapshotPolicyInput)(nil)).Elem(), &SnapshotPolicy{})
	pulumi.RegisterOutputType(SnapshotPolicyOutput{})
}
