// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mica

import (
	"context"
	"reflect"

	"errors"
	"github.com/numberly/terraform-provider-mica/pulumi/sdk/go/mica/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type TlsPolicy struct {
	pulumi.CustomResourceState

	// The name of the certificate used by the appliance for TLS connections.
	ApplianceCertificate pulumi.StringPtrOutput `pulumi:"applianceCertificate"`
	// When true, clients must present a certificate for mTLS. Defaults to false.
	ClientCertificatesRequired pulumi.BoolOutput `pulumi:"clientCertificatesRequired"`
	// List of TLS cipher suites to disable.
	DisabledTlsCiphers pulumi.StringArrayOutput `pulumi:"disabledTlsCiphers"`
	// Whether the TLS policy is enabled. Defaults to true.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// List of explicitly enabled TLS cipher suites.
	EnabledTlsCiphers pulumi.StringArrayOutput `pulumi:"enabledTlsCiphers"`
	// Whether this TLS policy is local to the array.
	IsLocal pulumi.BoolOutput `pulumi:"isLocal"`
	// The minimum TLS version required (e.g. TLSv1.2, TLSv1.3).
	MinTlsVersion pulumi.StringOutput `pulumi:"minTlsVersion"`
	// The name of the TLS policy. Changing this forces a new resource.
	Name pulumi.StringOutput `pulumi:"name"`
	// The type of the TLS policy.
	PolicyType pulumi.StringOutput `pulumi:"policyType"`
	// The name of the certificate authority used to verify client certificates for mTLS.
	TrustedClientCertificateAuthority pulumi.StringOutput `pulumi:"trustedClientCertificateAuthority"`
	// When true, client certificates are verified against the trusted CA.
	VerifyClientCertificateTrust pulumi.BoolOutput `pulumi:"verifyClientCertificateTrust"`
}

// NewTlsPolicy registers a new resource with the given unique name, arguments, and options.
func NewTlsPolicy(ctx *pulumi.Context,
	name string, args *TlsPolicyArgs, opts ...pulumi.ResourceOption) (*TlsPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TlsPolicy
	err := ctx.RegisterResource("mica:index/tlsPolicy:TlsPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTlsPolicy gets an existing TlsPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTlsPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TlsPolicyState, opts ...pulumi.ResourceOption) (*TlsPolicy, error) {
	var resource TlsPolicy
	err := ctx.ReadResource("mica:index/tlsPolicy:TlsPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TlsPolicy resources.
type tlsPolicyState struct {
	// The name of the certificate used by the appliance for TLS connections.
	ApplianceCertificate *string `pulumi:"applianceCertificate"`
	// When true, clients must present a certificate for mTLS. Defaults to false.
	ClientCertificatesRequired *bool `pulumi:"clientCertificatesRequired"`
	// List of TLS cipher suites to disable.
	DisabledTlsCiphers []string `pulumi:"disabledTlsCiphers"`
	// Whether the TLS policy is enabled. Defaults to true.
	Enabled *bool `pulumi:"enabled"`
	// List of explicitly enabled TLS cipher suites.
	EnabledTlsCiphers []string `pulumi:"enabledTlsCiphers"`
	// Whether this TLS policy is local to the array.
	IsLocal *bool `pulumi:"isLocal"`
	// The minimum TLS version required (e.g. TLSv1.2, TLSv1.3).
	MinTlsVersion *string `pulumi:"minTlsVersion"`
	// The name of the TLS policy. Changing this forces a new resource.
	Name *string `pulumi:"name"`
	// The type of the TLS policy.
	PolicyType *string `pulumi:"policyType"`
	// The name of the certificate authority used to verify client certificates for mTLS.
	TrustedClientCertificateAuthority *string `pulumi:"trustedClientCertificateAuthority"`
	// When true, client certificates are verified against the trusted CA.
	VerifyClientCertificateTrust *bool `pulumi:"verifyClientCertificateTrust"`
}

type TlsPolicyState struct {
	// The name of the certificate used by the appliance for TLS connections.
	ApplianceCertificate pulumi.StringPtrInput
	// When true, clients must present a certificate for mTLS. Defaults to false.
	ClientCertificatesRequired pulumi.BoolPtrInput
	// List of TLS cipher suites to disable.
	DisabledTlsCiphers pulumi.StringArrayInput
	// Whether the TLS policy is enabled. Defaults to true.
	Enabled pulumi.BoolPtrInput
	// List of explicitly enabled TLS cipher suites.
	EnabledTlsCiphers pulumi.StringArrayInput
	// Whether this TLS policy is local to the array.
	IsLocal pulumi.BoolPtrInput
	// The minimum TLS version required (e.g. TLSv1.2, TLSv1.3).
	MinTlsVersion pulumi.StringPtrInput
	// The name of the TLS policy. Changing this forces a new resource.
	Name pulumi.StringPtrInput
	// The type of the TLS policy.
	PolicyType pulumi.StringPtrInput
	// The name of the certificate authority used to verify client certificates for mTLS.
	TrustedClientCertificateAuthority pulumi.StringPtrInput
	// When true, client certificates are verified against the trusted CA.
	VerifyClientCertificateTrust pulumi.BoolPtrInput
}

func (TlsPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*tlsPolicyState)(nil)).Elem()
}

type tlsPolicyArgs struct {
	// The name of the certificate used by the appliance for TLS connections.
	ApplianceCertificate *string `pulumi:"applianceCertificate"`
	// When true, clients must present a certificate for mTLS. Defaults to false.
	ClientCertificatesRequired *bool `pulumi:"clientCertificatesRequired"`
	// List of TLS cipher suites to disable.
	DisabledTlsCiphers []string `pulumi:"disabledTlsCiphers"`
	// Whether the TLS policy is enabled. Defaults to true.
	Enabled *bool `pulumi:"enabled"`
	// List of explicitly enabled TLS cipher suites.
	EnabledTlsCiphers []string `pulumi:"enabledTlsCiphers"`
	// The minimum TLS version required (e.g. TLSv1.2, TLSv1.3).
	MinTlsVersion *string `pulumi:"minTlsVersion"`
	// The name of the TLS policy. Changing this forces a new resource.
	Name string `pulumi:"name"`
	// The name of the certificate authority used to verify client certificates for mTLS.
	TrustedClientCertificateAuthority *string `pulumi:"trustedClientCertificateAuthority"`
	// When true, client certificates are verified against the trusted CA.
	VerifyClientCertificateTrust *bool `pulumi:"verifyClientCertificateTrust"`
}

// The set of arguments for constructing a TlsPolicy resource.
type TlsPolicyArgs struct {
	// The name of the certificate used by the appliance for TLS connections.
	ApplianceCertificate pulumi.StringPtrInput
	// When true, clients must present a certificate for mTLS. Defaults to false.
	ClientCertificatesRequired pulumi.BoolPtrInput
	// List of TLS cipher suites to disable.
	DisabledTlsCiphers pulumi.StringArrayInput
	// Whether the TLS policy is enabled. Defaults to true.
	Enabled pulumi.BoolPtrInput
	// List of explicitly enabled TLS cipher suites.
	EnabledTlsCiphers pulumi.StringArrayInput
	// The minimum TLS version required (e.g. TLSv1.2, TLSv1.3).
	MinTlsVersion pulumi.StringPtrInput
	// The name of the TLS policy. Changing this forces a new resource.
	Name pulumi.StringInput
	// The name of the certificate authority used to verify client certificates for mTLS.
	TrustedClientCertificateAuthority pulumi.StringPtrInput
	// When true, client certificates are verified against the trusted CA.
	VerifyClientCertificateTrust pulumi.BoolPtrInput
}

func (TlsPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*tlsPolicyArgs)(nil)).Elem()
}

type TlsPolicyInput interface {
	pulumi.Input

	ToTlsPolicyOutput() TlsPolicyOutput
	ToTlsPolicyOutputWithContext(ctx context.Context) TlsPolicyOutput
}

func (*TlsPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**TlsPolicy)(nil)).Elem()
}

func (i *TlsPolicy) ToTlsPolicyOutput() TlsPolicyOutput {
	return i.ToTlsPolicyOutputWithContext(context.Background())
}

func (i *TlsPolicy) ToTlsPolicyOutputWithContext(ctx context.Context) TlsPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TlsPolicyOutput)
}

type TlsPolicyOutput struct{ *pulumi.OutputState }

func (TlsPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TlsPolicy)(nil)).Elem()
}

func (o TlsPolicyOutput) ToTlsPolicyOutput() TlsPolicyOutput {
	return o
}

func (o TlsPolicyOutput) ToTlsPolicyOutputWithContext(ctx context.Context) TlsPolicyOutput {
	return o
}

// The name of the certificate used by the appliance for TLS connections.
func (o TlsPolicyOutput) ApplianceCertificate() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TlsPolicy) pulumi.StringPtrOutput { return v.ApplianceCertificate }).(pulumi.StringPtrOutput)
}

// When true, clients must present a certificate for mTLS. Defaults to false.
func (o TlsPolicyOutput) ClientCertificatesRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v *TlsPolicy) pulumi.BoolOutput { return v.ClientCertificatesRequired }).(pulumi.BoolOutput)
}

// List of TLS cipher suites to disable.
func (o TlsPolicyOutput) DisabledTlsCiphers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *TlsPolicy) pulumi.StringArrayOutput { return v.DisabledTlsCiphers }).(pulumi.StringArrayOutput)
}

// Whether the TLS policy is enabled. Defaults to true.
func (o TlsPolicyOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *TlsPolicy) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// List of explicitly enabled TLS cipher suites.
func (o TlsPolicyOutput) EnabledTlsCiphers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *TlsPolicy) pulumi.StringArrayOutput { return v.EnabledTlsCiphers }).(pulumi.StringArrayOutput)
}

// Whether this TLS policy is local to the array.
func (o TlsPolicyOutput) IsLocal() pulumi.BoolOutput {
	return o.ApplyT(func(v *TlsPolicy) pulumi.BoolOutput { return v.IsLocal }).(pulumi.BoolOutput)
}

// The minimum TLS version required (e.g. TLSv1.2, TLSv1.3).
func (o TlsPolicyOutput) MinTlsVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *TlsPolicy) pulumi.StringOutput { return v.MinTlsVersion }).(pulumi.StringOutput)
}

// The name of the TLS policy. Changing this forces a new resource.
func (o TlsPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *TlsPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The type of the TLS policy.
func (o TlsPolicyOutput) PolicyType() pulumi.StringOutput {
	return o.ApplyT(func(v *TlsPolicy) pulumi.StringOutput { return v.PolicyType }).(pulumi.StringOutput)
}

// The name of the certificate authority used to verify client certificates for mTLS.
func (o TlsPolicyOutput) TrustedClientCertificateAuthority() pulumi.StringOutput {
	return o.ApplyT(func(v *TlsPolicy) pulumi.StringOutput { return v.TrustedClientCertificateAuthority }).(pulumi.StringOutput)
}

// When true, client certificates are verified against the trusted CA.
func (o TlsPolicyOutput) VerifyClientCertificateTrust() pulumi.BoolOutput {
	return o.ApplyT(func(v *TlsPolicy) pulumi.BoolOutput { return v.VerifyClientCertificateTrust }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TlsPolicyInput)(nil)).Elem(), &TlsPolicy{})
	pulumi.RegisterOutputType(TlsPolicyOutput{})
}
